In [1]:
import os

from io import StringIO
from google.cloud import storage
from dotenv import load_dotenv

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import torch
import torch.nn.functional as F

from transformers import AutoModelForCausalLM
from transformers import AutoTokenizer, EsmForMaskedLM
from tokenizers import Tokenizer
from peft import get_peft_model, LoraConfig, TaskType

/opt/anaconda3/envs/MachLearn/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
from plm_compare_progen2 import *
from plm_compare_esm import *
from protein_data import *
from pro_gen2_lora import *

In [3]:
load_dotenv()
cred_path = os.getenv('GOOGLE_APPLICATION_CREDENTIALS')

os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = cred_path

client = storage.Client()
bucket = client.bucket('domainome-data')
blob = bucket.blob('SupplementaryTable2.txt')

df = pd.read_csv(StringIO(blob.download_as_text()), sep='\t')

In [7]:
df.head()

,domain_ID,uniprot_ID,aa_seq,wt_aa,position,mut_aa,STOP,input_count_rep1,input_count_rep2,input_count_rep3,output_count_rep1,output_count_rep2,output_count_rep3,mean_input_count,fitness,fitness_sigma,normalized_fitness,normalized_fitness_sigma,quality_rank,pfam_ID
0,A0A2R8Y422_PF00240_2,A0A2R8Y422,*IFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2.0,*,True,118.0,113.0,62.0,10.0,29.0,2.0,97.66667,0.030945,0.014885,-0.819050,0.208478,339,PF00240
1,A0A2R8Y422_PF00240_2,A0A2R8Y422,AIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2.0,A,False,219.0,277.0,217.0,86.0,225.0,137.0,237.66670,0.069376,0.006673,-0.280790,0.093461,339,PF00240
2,A0A2R8Y422_PF00240_2,A0A2R8Y422,CIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2.0,C,False,706.0,726.0,459.0,768.0,507.0,616.0,630.33330,0.082052,0.004141,-0.103250,0.057995,339,PF00240
3,A0A2R8Y422_PF00240_2,A0A2R8Y422,DIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2.0,D,False,407.0,431.0,323.0,508.0,159.0,111.0,387.00000,0.071003,0.005162,-0.258003,0.072296,339,PF00240
4,A0A2R8Y422_PF00240_2,A0A2R8Y422,EIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2.0,E,False,37.0,56.0,37.0,201.0,102.0,95.0,43.33333,0.116326,0.012085,0.376783,0.169263,339,PF00240

In [22]:
df[df['pfam_ID']=='O14901']

Empty DataFrame
Columns: [domain_ID, uniprot_ID, aa_seq, wt_aa, position, mut_aa, STOP, input_count_rep1, input_count_rep2, input_count_rep3, output_count_rep1, output_count_rep2, output_count_rep3, mean_input_count, fitness, fitness_sigma, normalized_fitness, normalized_fitness_sigma, quality_rank, pfam_ID]
Index: []

In [23]:
pfam_dict={}

In [36]:
for x in df['pfam_ID'].unique():
    print(x)
    uid_list = list(df[df['pfam_ID']==x]['uniprot_ID'])
    uid_list = list(set(uid_list))
    print(uid_list)
    pfam_dict[x] = dict.fromkeys(uid_list, None)

PF00240
['A0A2R8Y422']
PF00096
['Q9NSC2', 'Q9UQR1', 'O43167', 'O60281', 'Q9Y2G7', 'P51508', 'Q9HC78', 'P37275', 'P25490', 'Q9H9D4', 'Q9BRP0', 'P08151', 'O14901', 'Q9NU63', 'Q99684', 'Q8NEA6', 'A0PJY2', 'Q5VTD9', 'P57071', 'Q9NQX1', 'Q9Y462', 'Q9NQV8', 'P10071', 'Q8TDD2', 'P10070', 'Q9UJQ4', 'O60481', 'Q9HAZ2']
PF00018
['Q7Z6B7', 'P07751', 'Q9UNF0', 'A1X283', 'Q15811', 'O15259', 'P02549', 'P51451', 'Q06187', 'Q12929', 'P19878', 'Q6XZF7', 'P12931', 'P08631', 'P62993', 'P14598', 'P15498', 'Q12965', 'P20936', 'P06239', 'Q5HYK7', 'Q08881', 'Q9Y5K6', 'O43295', 'O43586', 'P06241', 'Q8N157', 'P16885', 'P00519']
PF01846
['O75400', 'Q6NWY9', 'A2RRE5', 'O14776', 'Q5VWI1']
PF07525
['A6NK59', 'Q9NYS7']
rockdoms
['EHEE-rd1-0882', 'HHH-rd1-0142', 'EEHEE-rd3-0037']
PF00397
['O95817', 'Q96J02', 'Q6ZWJ1', 'Q96PU5', 'Q9H0M0', 'Q13526', 'Q5TCQ9', 'Q86UL8', 'Q9BYW2', 'O75400', 'Q8N3X1', 'Q9P2P5', 'Q9HAU4', 'Q96QZ7', 'P39940', 'Q9GZV5', 'P46934', 'O00308', 'P46937']
PF02817
['O00330', 'P11961', 'P11182']
PF02376
['Q01826', 'Q9UPW6', 'P39880', 'O14529']
PF00595
['Q8TEW0', 'Q61234', 'Q92796', 'O75112', 'O14640', 'Q86UL8', 'Q13368', 'Q13424', 'Q9UPQ7', 'Q9ULL8', 'Q9UDY2', 'O14936', 'Q14160', 'Q13009', 'Q9Y6N9', 'P78352', 'O75970', 'Q9Y3R0', 'Q14CM0', 'Q96RT1', 'Q8TEW8']
PF00778
['Q92997', 'O14640']
PF00046
['Q86UP3', 'Q9BZM3', 'P23759', 'Q9H2P0', 'P14653', 'O95475', 'Q15911', 'Q8NFW5', 'P26367', 'P49335', 'O14813', 'P39880', 'P20264', 'Q9H161', 'Q96QS3', 'P78424', 'P32243', 'P54821', 'O95076', 'Q15475', 'Q5SQQ9', 'P20265', 'Q9UBX0', 'O95343', 'O43186', 'O75360', 'Q9C0A1', 'P28360', 'O15266', 'P35548', 'P56915', 'Q9NPC8', 'Q15699']
PF00641
['O15151', 'Q8TAT5', 'O75808', 'O95218', 'Q00987', 'P98175', 'P49792']
PF08313
['O15265']
PF00643
['Q9NQ86', 'Q12899', 'Q2Q1W2', 'O75382', 'O15344', 'Q96DX7', 'Q9UJV3', 'Q9C030', 'P0CI26']
PF07647
['Q8WWH4', 'Q9ULJ8', 'O15350', 'Q5K651', 'Q9H3D4']
PF00505
['P35716', 'Q05066', 'Q9NP66', 'O15405', 'Q969G3', 'P17480', 'P48431', 'P35712', 'P54277', 'O94993', 'Q06945', 'Q9H6I2', 'P35713', 'Q86U86', 'P35711', 'P41225', 'P57073']
PF00642
['Q96K80', 'P26651', 'Q96GM8', 'Q9H000', 'P47974', 'Q9UHC7', 'Q8IWR0', 'O15541']
PF00619
['Q9ULZ3', 'O43353']
PF00779
['O43374']
PF01480
['O43395']
PF10650
['O60293']
PF04433
['O75478', 'O60341']
PF17035
['O60885']
PF02209
['P09327', 'P02640', 'O75366']
PF00630
['O75369']
PF00313
['Q9Y2T7', 'P32081', 'P67809', 'P16989', 'P41016', 'O75534', 'P0A9X9']
PF06220
['O75554']
PF00226
['Q7Z6W7', 'Q99615', 'O75953', 'Q9UBS4', 'Q9H3Z4', 'P25685']
PF00536
['Q68DC2', 'Q7Z6G8', 'O94885', 'Q9NYL2', 'O94830', 'Q8WXI2']
PF00412
['Q96JY6', 'Q13642', 'Q14192', 'Q7Z4I7', 'O94929', 'Q15942']
PF04564
['O95155']
PF00130
['Q05655', 'Q8N1W1', 'O95267']
PF18366
['O95409']
PF11515
['O95714', 'Q8IWT3']
PF00105
['P08235', 'O95718', 'P04150', 'P10826', 'Q14995', 'Q03181', 'P43354', 'P10589', 'P19793', 'P10275']
PF06467
['O95789', 'Q14202', 'Q9UJ78', 'Q9UBW7']
PF00035
['P78563', 'O95793']
PF00627
['P54727', 'Q9H347', 'P22681', 'P61086', 'Q7Z6Z7', 'O95835']
PF00280
['P01053', 'P19873']
PF01281
['P02417']
PF13499
['Q96GE6', 'P02585', 'Q13813', 'P13796', 'Q9NPB3']
PF01023
['P02633']
PF01381
['P03034']
PF02196
['P04049', 'P10398', 'P15056']
PF00030
['P11844', 'P07316', 'P07320', 'Q8N1P7', 'P07315', 'P43320', 'P22914', 'P53673', 'P05813', 'P53674']
PF00458
['P07814', 'P12081']
PF00157
['Q01860', 'P28069', 'P20264', 'P14859', 'Q01851', 'Q14863', 'Q12837', 'Q15319', 'Q9UKI9', 'P09086', 'Q03052', 'P20265']
PF00249
['Q8TAQ2', 'Q6P0N0', 'Q9UKL0', 'Q9Y618', 'Q92922', 'Q99543', 'Q8IYH5', 'Q9BTC8', 'Q9Y222', 'P10242', 'Q96KC8', 'Q9P2K3', 'Q5VVJ2', 'Q15554']
PF02198
['P14921', 'Q9UKW6', 'Q01543', 'Q06546', 'P78545', 'P11308']
PF02037
['Q8IV48', 'Q1KMD3', 'Q6ZN01', 'Q9BUJ2', 'Q8IX12', 'P82979', 'P12956', 'Q15424', 'Q969V6', 'Q9NWH9', 'Q14151', 'Q8IZQ8', 'P40040', 'Q00839']
PF02270
['P13984']
PF00531
['Q12955', 'P16157', 'Q01484']
PF00564
['P19878', 'Q13163', 'Q92734']
PF14604
['Q9BY11', 'P20929', 'Q9NZM3', 'Q9Y5K6', 'Q6XZF7', 'Q9UKS6', 'Q86WN1']
PF00538
['P22492']
PF00533
['P35251']
PF02845
['Q8N5C8', 'P36075']
PF00646
['Q8NEZ5', 'P41002']
PF00628
['Q9BTC0', 'Q96CB8', 'Q12873', 'Q14839', 'Q12830', 'Q13263', 'P41229', 'Q9UIF8', 'Q8TDI0']
PF00831
['P42766']
PF00385
['P45973', 'Q14839']
PF00010
['P50539', 'Q05195']
PF07533
['P51532', 'Q9P2D1']
PF01429
['P51608']
PF00173
['P51687']
PF13639
['P53804', 'Q6ZSG1']
PF02359
['P55072']
PF02295
['P55265']
PF13341
['P55895']
PF05129
['P60002']
PF05741
['P60321']
PF01111
['P61024']
PF03671
['P61960']
PF00013
['P61978', 'Q96I24', 'Q15365', 'Q92945', 'Q86XN8', 'Q06787', 'Q96AE4', 'Q5U5Q3']
PF16557
['Q01826']
PF02008
['Q03164']
PF16558
['Q05086']
PF02172
['Q09472']
PF04855
['Q12824']
PF18016
['Q12929']
PF18694
['Q13148']
PF01335
['Q13158']
PF06839
['Q13472']
PF00569
['Q13501', 'Q9Y4J8']
PF16577
['Q13501']
PF00789
['Q14CS0']
PF07653
['Q15811']
PF02185
['Q16512']
PF08711
['Q3SY89', 'Q8N8B7']
PF12171
['Q9HA38', 'Q5F1R6']
PF02257
['Q68CP9']
PF10264
['Q6ZVD7', 'Q9P2F5']
PF09329
['Q7L590']
PF01363
['Q7Z3T8', 'Q96T51']
PF16366
['Q7Z5Q1']
PF18112
['Q86VP1']
PF02207
['Q86XK2']
PF18346
['Q86YT6']
PF01485
['Q9BYM8', 'Q8IWT3']
PF00612
['Q9H0A6', 'Q8IZT6']
PF07496
['Q8NB78']
PF12701
['Q8ND56']
PF16866
['Q8NHM5']
PF08073
['Q8TDI0']
PF18044
['Q8WU90']
PF00320
['Q8WXI9', 'Q9P2R6']
PF05207
['Q96FX2']
PF05225
['Q96JN0']
PF09011
['Q96JY0']
PF00787
['Q96L93']
PF02187
['Q99501']
PF14369
['Q9BV68']
PF12202
['Q9H4A3']
PF00567
['Q9H7E2']
PF13891
['Q9H9L4']
PF11722
['Q9NUP7']
PF11793
['Q9NW38']
PF05605
['Q9P0J7']
PF12678
['Q9UBF6']
PF01246
['Q9UHA3']
PF02017
['Q9UHD4']
PF18387
['Q9UKY1']
PF02179
['Q9UL15']
PF18410
['Q9ULT8']
PF03638
['Q9Y4I5']
PF05715
['Q9Y6V0']

{'PF00240': {'A0A2R8Y422': None},
 'PF00096': {'Q9NSC2': None,
  'Q9UQR1': None,
  'O43167': None,
  'O60281': None,
  'Q9Y2G7': None,
  'P51508': None,
  'Q9HC78': None,
  'P37275': None,
  'P25490': None,
  'Q9H9D4': None,
  'Q9BRP0': None,
  'P08151': None,
  'O14901': None,
  'Q9NU63': None,
  'Q99684': None,
  'Q8NEA6': None,
  'A0PJY2': None,
  'Q5VTD9': None,
  'P57071': None,
  'Q9NQX1': None,
  'Q9Y462': None,
  'Q9NQV8': None,
  'P10071': None,
  'Q8TDD2': None,
  'P10070': None,
  'Q9UJQ4': None,
  'O60481': None,
  'Q9HAZ2': None},
 'PF00018': {'Q7Z6B7': None,
  'P07751': None,
  'Q9UNF0': None,
  'A1X283': None,
  'Q15811': None,
  'O15259': None,
  'P02549': None,
  'P51451': None,
  'Q06187': None,
  'Q12929': None,
  'P19878': None,
  'Q6XZF7': None,
  'P12931': None,
  'P08631': None,
  'P62993': None,
  'P14598': None,
  'P15498': None,
  'Q12965': None,
  'P20936': None,
  'P06239': None,
  'Q5HYK7': None,
  'Q08881': None,
  'Q9Y5K6': None,
  'O43295': None,
  'O43586': None,
  'P06241': None,
  'Q8N157': None,
  'P16885': None,
  'P00519': None},
 'PF01846': {'O75400': None,
  'Q6NWY9': None,
  'A2RRE5': None,
  'O14776': None,
  'Q5VWI1': None},
 'PF07525': {'A6NK59': None, 'Q9NYS7': None},
 'rockdoms': {'EHEE-rd1-0882': None,
  'HHH-rd1-0142': None,
  'EEHEE-rd3-0037': None},
 'PF00397': {'O95817': None,
  'Q96J02': None,
  'Q6ZWJ1': None,
  'Q96PU5': None,
  'Q9H0M0': None,
  'Q13526': None,
  'Q5TCQ9': None,
  'Q86UL8': None,
  'Q9BYW2': None,
  'O75400': None,
  'Q8N3X1': None,
  'Q9P2P5': None,
  'Q9HAU4': None,
  'Q96QZ7': None,
  'P39940': None,
  'Q9GZV5': None,
  'P46934': None,
  'O00308': None,
  'P46937': None},
 'PF02817': {'O00330': None, 'P11961': None, 'P11182': None},
 'PF02376': {'Q01826': None, 'Q9UPW6': None, 'P39880': None, 'O14529': None},
 'PF00595': {'Q8TEW0': None,
  'Q61234': None,
  'Q92796': None,
  'O75112': None,
  'O14640': None,
  'Q86UL8': None,
  'Q13368': None,
  'Q13424': None,
  'Q9UPQ7': None,
  'Q9ULL8': None,
  'Q9UDY2': None,
  'O14936': None,
  'Q14160': None,
  'Q13009': None,
  'Q9Y6N9': None,
  'P78352': None,
  'O75970': None,
  'Q9Y3R0': None,
  'Q14CM0': None,
  'Q96RT1': None,
  'Q8TEW8': None},
 'PF00778': {'Q92997': None, 'O14640': None},
 'PF00046': {'Q86UP3': None,
  'Q9BZM3': None,
  'P23759': None,
  'Q9H2P0': None,
  'P14653': None,
  'O95475': None,
  'Q15911': None,
  'Q8NFW5': None,
  'P26367': None,
  'P49335': None,
  'O14813': None,
  'P39880': None,
  'P20264': None,
  'Q9H161': None,
  'Q96QS3': None,
  'P78424': None,
  'P32243': None,
  'P54821': None,
  'O95076': None,
  'Q15475': None,
  'Q5SQQ9': None,
  'P20265': None,
  'Q9UBX0': None,
  'O95343': None,
  'O43186': None,
  'O75360': None,
  'Q9C0A1': None,
  'P28360': None,
  'O15266': None,
  'P35548': None,
  'P56915': None,
  'Q9NPC8': None,
  'Q15699': None},
 'PF00641': {'O15151': None,
  'Q8TAT5': None,
  'O75808': None,
  'O95218': None,
  'Q00987': None,
  'P98175': None,
  'P49792': None},
 'PF08313': {'O15265': None},
 'PF00643': {'Q9NQ86': None,
  'Q12899': None,
  'Q2Q1W2': None,
  'O75382': None,
  'O15344': None,
  'Q96DX7': None,
  'Q9UJV3': None,
  'Q9C030': None,
  'P0CI26': None},
 'PF07647': {'Q8WWH4': None,
  'Q9ULJ8': None,
  'O15350': None,
  'Q5K651': None,
  'Q9H3D4': None},
 'PF00505': {'P35716': None,
  'Q05066': None,
  'Q9NP66': None,
  'O15405': None,
  'Q969G3': None,
  'P17480': None,
  'P48431': None,
  'P35712': None,
  'P54277': None,
  'O94993': None,
  'Q06945': None,
  'Q9H6I2': None,
  'P35713': None,
  'Q86U86': None,
  'P35711': None,
  'P41225': None,
  'P57073': None},
 'PF00642': {'Q96K80': None,
  'P26651': None,
  'Q96GM8': None,
  'Q9H000': None,
  'P47974': None,
  'Q9UHC7': None,
  'Q8IWR0': None,
  'O15541': None},
 'PF00619': {'Q9ULZ3': None, 'O43353': None},
 'PF00779': {'O43374': None},
 'PF01480': {'O43395': None},
 'PF10650': {'O60293': None},
 'PF04433': {'O75478': None, 'O60341': None},
 'PF17035': {'O60885': None},
 'PF02209': {'P09327': None, 'P02640': None, 'O75366': None},
 'PF00630': {'O75369': None},
 'PF00313': {'Q9Y2T7': None,
  'P32081': None,
  'P67809': None,
  'P16989': None,
  'P41016': None,
  'O75534': None,
  'P0A9X9': None},
 'PF06220': {'O75554': None},
 'PF00226': {'Q7Z6W7': None,
  'Q99615': None,
  'O75953': None,
  'Q9UBS4': None,
  'Q9H3Z4': None,
  'P25685': None},
 'PF00536': {'Q68DC2': None,
  'Q7Z6G8': None,
  'O94885': None,
  'Q9NYL2': None,
  'O94830': None,
  'Q8WXI2': None},
 'PF00412': {'Q96JY6': None,
  'Q13642': None,
  'Q14192': None,
  'Q7Z4I7': None,
  'O94929': None,
  'Q15942': None},
 'PF04564': {'O95155': None},
 'PF00130': {'Q05655': None, 'Q8N1W1': None, 'O95267': None},
 'PF18366': {'O95409': None},
 'PF11515': {'O95714': None, 'Q8IWT3': None},
 'PF00105': {'P08235': None,
  'O95718': None,
  'P04150': None,
  'P10826': None,
  'Q14995': None,
  'Q03181': None,
  'P43354': None,
  'P10589': None,
  'P19793': None,
  'P10275': None},
 'PF06467': {'O95789': None, 'Q14202': None, 'Q9UJ78': None, 'Q9UBW7': None},
 'PF00035': {'P78563': None, 'O95793': None},
 'PF00627': {'P54727': None,
  'Q9H347': None,
  'P22681': None,
  'P61086': None,
  'Q7Z6Z7': None,
  'O95835': None},
 'PF00280': {'P01053': None, 'P19873': None},
 'PF01281': {'P02417': None},
 'PF13499': {'Q96GE6': None,
  'P02585': None,
  'Q13813': None,
  'P13796': None,
  'Q9NPB3': None},
 'PF01023': {'P02633': None},
 'PF01381': {'P03034': None},
 'PF02196': {'P04049': None, 'P10398': None, 'P15056': None},
 'PF00030': {'P11844': None,
  'P07316': None,
  'P07320': None,
  'Q8N1P7': None,
  'P07315': None,
  'P43320': None,
  'P22914': None,
  'P53673': None,
  'P05813': None,
  'P53674': None},
 'PF00458': {'P07814': None, 'P12081': None},
 'PF00157': {'Q01860': None,
  'P28069': None,
  'P20264': None,
  'P14859': None,
  'Q01851': None,
  'Q14863': None,
  'Q12837': None,
  'Q15319': None,
  'Q9UKI9': None,
  'P09086': None,
  'Q03052': None,
  'P20265': None},
 'PF00249': {'Q8TAQ2': None,
  'Q6P0N0': None,
  'Q9UKL0': None,
  'Q9Y618': None,
  'Q92922': None,
  'Q99543': None,
  'Q8IYH5': None,
  'Q9BTC8': None,
  'Q9Y222': None,
  'P10242': None,
  'Q96KC8': None,
  'Q9P2K3': None,
  'Q5VVJ2': None,
  'Q15554': None},
 'PF02198': {'P14921': None,
  'Q9UKW6': None,
  'Q01543': None,
  'Q06546': None,
  'P78545': None,
  'P11308': None},
 'PF02037': {'Q8IV48': None,
  'Q1KMD3': None,
  'Q6ZN01': None,
  'Q9BUJ2': None,
  'Q8IX12': None,
  'P82979': None,
  'P12956': None,
  'Q15424': None,
  'Q969V6': None,
  'Q9NWH9': None,
  'Q14151': None,
  'Q8IZQ8': None,
  'P40040': None,
  'Q00839': None},
 'PF02270': {'P13984': None},
 'PF00531': {'Q12955': None, 'P16157': None, 'Q01484': None},
 'PF00564': {'P19878': None, 'Q13163': None, 'Q92734': None},
 'PF14604': {'Q9BY11': None,
  'P20929': None,
  'Q9NZM3': None,
  'Q9Y5K6': None,
  'Q6XZF7': None,
  'Q9UKS6': None,
  'Q86WN1': None},
 'PF00538': {'P22492': None},
 'PF00533': {'P35251': None},
 'PF02845': {'Q8N5C8': None, 'P36075': None},
 'PF00646': {'Q8NEZ5': None, 'P41002': None},
 'PF00628': {'Q9BTC0': None,
  'Q96CB8': None,
  'Q12873': None,
  'Q14839': None,
  'Q12830': None,
  'Q13263': None,
  'P41229': None,
  'Q9UIF8': None,
  'Q8TDI0': None},
 'PF00831': {'P42766': None},
 'PF00385': {'P45973': None, 'Q14839': None},
 'PF00010': {'P50539': None, 'Q05195': None},
 'PF07533': {'P51532': None, 'Q9P2D1': None},
 'PF01429': {'P51608': None},
 'PF00173': {'P51687': None},
 'PF13639': {'P53804': None, 'Q6ZSG1': None},
 'PF02359': {'P55072': None},
 'PF02295': {'P55265': None},
 'PF13341': {'P55895': None},
 'PF05129': {'P60002': None},
 'PF05741': {'P60321': None},
 'PF01111': {'P61024': None},
 'PF03671': {'P61960': None},
 'PF00013': {'P61978': None,
  'Q96I24': None,
  'Q15365': None,
  'Q92945': None,
  'Q86XN8': None,
  'Q06787': None,
  'Q96AE4': None,
  'Q5U5Q3': None},
 'PF16557': {'Q01826': None},
 'PF02008': {'Q03164': None},
 'PF16558': {'Q05086': None},
 'PF02172': {'Q09472': None},
 'PF04855': {'Q12824': None},
 'PF18016': {'Q12929': None},
 'PF18694': {'Q13148': None},
 'PF01335': {'Q13158': None},
 'PF06839': {'Q13472': None},
 'PF00569': {'Q13501': None, 'Q9Y4J8': None},
 'PF16577': {'Q13501': None},
 'PF00789': {'Q14CS0': None},
 'PF07653': {'Q15811': None},
 'PF02185': {'Q16512': None},
 'PF08711': {'Q3SY89': None, 'Q8N8B7': None},
 'PF12171': {'Q9HA38': None, 'Q5F1R6': None},
 'PF02257': {'Q68CP9': None},
 'PF10264': {'Q6ZVD7': None, 'Q9P2F5': None},
 'PF09329': {'Q7L590': None},
 'PF01363': {'Q7Z3T8': None, 'Q96T51': None},
 'PF16366': {'Q7Z5Q1': None},
 'PF18112': {'Q86VP1': None},
 'PF02207': {'Q86XK2': None},
 'PF18346': {'Q86YT6': None},
 'PF01485': {'Q9BYM8': None, 'Q8IWT3': None},
 'PF00612': {'Q9H0A6': None, 'Q8IZT6': None},
 'PF07496': {'Q8NB78': None},
 'PF12701': {'Q8ND56': None},
 'PF16866': {'Q8NHM5': None},
 'PF08073': {'Q8TDI0': None},
 'PF18044': {'Q8WU90': None},
 'PF00320': {'Q8WXI9': None, 'Q9P2R6': None},
 'PF05207': {'Q96FX2': None},
 'PF05225': {'Q96JN0': None},
 'PF09011': {'Q96JY0': None},
 'PF00787': {'Q96L93': None},
 'PF02187': {'Q99501': None},
 'PF14369': {'Q9BV68': None},
 'PF12202': {'Q9H4A3': None},
 'PF00567': {'Q9H7E2': None},
 'PF13891': {'Q9H9L4': None},
 'PF11722': {'Q9NUP7': None},
 'PF11793': {'Q9NW38': None},
 'PF05605': {'Q9P0J7': None},
 'PF12678': {'Q9UBF6': None},
 'PF01246': {'Q9UHA3': None},
 'PF02017': {'Q9UHD4': None},
 'PF18387': {'Q9UKY1': None},
 'PF02179': {'Q9UL15': None},
 'PF18410': {'Q9ULT8': None},
 'PF03638': {'Q9Y4I5': None},
 'PF05715': {'Q9Y6V0': None}}

In [ ]:
for x in pfam_dict.keys():
    pfam_dict[x] =

ValueError: dictionary update sequence element #0 has length 10; 2 is required

In [29]:
pfam_dict

{'PF00240': ['A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  'A0A2R8Y422',
  ...],
 'PF00096': ['A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',
  'A0PJY2',

In [15]:
domainome_ids = set(df['uniprot_ID'])

In [19]:
for x in domainome_ids:
    if 'A' in x:
        print(x)

A2RRE5
Q9C0A1
A0PJY2
Q9H0A6
A6NK59
Q96AE4
Q9H4A3
Q8TAQ2
Q9HA38
Q9UHA3
A1X283
P0A9X9
A0A2R8Y422
Q9HAU4
Q8NEA6
Q8TAT5
Q9HAZ2

In [ ]:
# # Load environment variables
# load_dotenv()
# cred_path = os.getenv('GOOGLE_APPLICATION_CREDENTIALS')
# os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = cred_path

# # Connect to GCP bucket
# client = storage.Client()
# bucket = client.bucket('domainome-data')
# blob = bucket.blob('uniprot_sprot.fasta')  # replace with your FASTA file name

# # Download FASTA as text
# fasta_text = blob.download_as_text()

# # List of UniProt IDs you want
# desired_ids = domainome_ids  # example, use a set for fast lookup

# # Dictionary to store sequences
# uniprot_dict = {}
# current_id = None
# current_seq = []

# # Parse FASTA line by line
# for line in fasta_text.splitlines():
#     if line.startswith('>'):
#         if current_id and current_id in desired_ids:
#             # Save previous sequence if in desired list
#             uniprot_dict[current_id] = ''.join(current_seq)
#         # Extract UniProt ID
#         uniprot_id = line.split('|')[1]  # standard UniProt header: >sp|P12345|PROT_HUMAN ...
#         if uniprot_id in desired_ids:
#             current_id = uniprot_id
#             current_seq = []
#         else:
#             current_id = None  # skip sequences we don't care about
#             current_seq = []
#     else:
#         if current_id:  # only accumulate if ID is in desired list
#             current_seq.append(line.strip())

# # Save the last sequence if it was desired
# if current_id and current_id in desired_ids:
#     uniprot_dict[current_id] = ''.join(current_seq)

# print(f"Retrieved {len(uniprot_dict)} sequences from FASTA")
# print(list(uniprot_dict.items())[:5])

Retrieved 428 sequences from FASTA
[('P00519', 'MLEICLKLVGCKSKKGLSSSSSCYLEEALQRPVASDFEPQGLSEAARWNSKENLLAGPSENDPNLFVALYDFVASGDNTLSITKGEKLRVLGYNHNGEWCEAQTKNGQGWVPSNYITPVNSLEKHSWYHGPVSRNAAEYLLSSGINGSFLVRESESSPGQRSISLRYEGRVYHYRINTASDGKLYVSSESRFNTLAELVHHHSTVADGLITTLHYPAPKRNKPTVYGVSPNYDKWEMERTDITMKHKLGGGQYGEVYEGVWKKYSLTVAVKTLKEDTMEVEEFLKEAAVMKEIKHPNLVQLLGVCTREPPFYIITEFMTYGNLLDYLRECNRQEVNAVVLLYMATQISSAMEYLEKKNFIHRDLAARNCLVGENHLVKVADFGLSRLMTGDTYTAHAGAKFPIKWTAPESLAYNKFSIKSDVWAFGVLLWEIATYGMSPYPGIDLSQVYELLEKDYRMERPEGCPEKVYELMRACWQWNPSDRPSFAEIHQAFETMFQESSISDEVEKELGKQGVRGAVSTLLQAPELPTKTRTSRRAAEHRDTTDVPEMPHSKGQGESDPLDHEPAVSPLLPRKERGPPEGGLNEDERLLPKDKKTNLFSALIKKKKKTAPTPPKRSSSFREMDGQPERRGAGEEEGRDISNGALAFTPLDTADPAKSPKPSNGAGVPNGALRESGGSGFRSPHLWKKSSTLTSSRLATGEEEGGGSSSKRFLRSCSASCVPHGAKDTEWRSVTLPRDLQSTGRQFDSSTFGGHKSEKPALPRKRAGENRSDQVTRGTVTPPPRLVKKNEEAADEVFKDIMESSPGSSPPNLTPKPLRRQVTVAPASGLPHKEEAGKGSALGTPAAAEPVTPTSKAGSGAPGGTSKGPAEESRVRRHKHSSESPGRDKGKLSRLKPAPPPPPAASAGKAGGKPSQSPSQEAAGEAVLGAKTKATSLVDAVNSDAAKPSQPGEGLKKPVLPATPKPQSAKPSGTPISPAPVPSTLPSASSALAGDQPSSTAFIPLISTRVSLRKTRQPPERIASGAITKGVVLDSTEALCLAISRNSEQMASHSAVLEAGKNLYTFCVSYVDSIQQMRNKFAFREAINKLENNLRELQICPATAGSGPAATQDFSKLLSSVKEISDIVQR'), ('O94929', 'MNTSIPYQQNPYNPRGSSNVIQCYRCGDTCKGEVVRVHNNHFHIRCFTCQVCGCGLAQSGFFFKNQEYICTQDYQQLYGTRCDSCRDFITGEVISALGRTYHPKCFVCSLCRKPFPIGDKVTFSGKECVCQTCSQSMASSKPIKIRGPSHCAGCKEEIKHGQSLLALDKQWHVSCFKCQTCSVILTGEYISKDGVPYCESDYHAQFGIKCETCDRYISGRVLEAGGKHYHPTCARCVRCHQMFTEGEEMYLTGSEVWHPICKQAARAEKKLKHRRTSETSISPPGSSIGSPNRVICAKVDNEILNYKDLAALPKVKSIYEVQRPDLISYEPHSRYMSDEMLERCGYGESLGTLSPYSQDIYENLDLRQRRASSPGYIDSPTYSRQGMSPTFSRSPHHYYRSGPESGRSSPYHSQLDVRSSTPTSYQAPKHFHIPAGDSNIYRKPPIYKRHGDLSTATKSKTSEDISQTSKYSPIYSPDPYYASESEYWTYHGSPKVPRARRFSSGGEEDDFDRSMHKLQSGIGRLILKEEMKARSSSYADPWTPPRSSTSSREALHTAGYEMSLNGSPRSHYLADSDPLISKSASLPAYRRNGLHRTPSADLFHYDSMNAVNWGMREYKIYPYELLLVTTRGRNRLPKDVDRTRLERHLSQEEFYQVFGMTISEFDRLALWKRNELKKQARLF'), ('Q9H2P0', 'MFQLPVNNLGSLRKARKTVKKILSDIGLEYCKEHIEDFKQFEPNDFYLKNTTWEDVGLWDPSLTKNQDYRTKPFCCSACPFSSKFFSAYKSHFRNVHSEDFENRILLNCPYCTFNADKKTLETHIKIFHAPNASAPSSSLSTFKDKNKNDGLKPKQADSVEQAVYYCKKCTYRDPLYEIVRKHIYREHFQHVAAPYIAKAGEKSLNGAVPLGSNAREESSIHCKRCLFMPKSYEALVQHVIEDHERIGYQVTAMIGHTNVVVPRSKPLMLIAPKPQDKKSMGLPPRIGSLASGNVRSLPSQQMVNRLSIPKPNLNSTGVNMMSSVHLQQNNYGVKSVGQGYSVGQSMRLGLGGNAPVSIPQQSQSVKQLLPSGNGRSYGLGSEQRSQAPARYSLQSANASSLSSGQLKSPSLSQSQASRVLGQSSSKPAAAATGPPPGNTSSTQKWKICTICNELFPENVYSVHFEKEHKAEKVPAVANYIMKIHNFTSKCLYCNRYLPTDTLLNHMLIHGLSCPYCRSTFNDVEKMAAHMRMVHIDEEMGPKTDSTLSFDLTLQQGSHTNIHLLVTTYNLRDAPAESVAYHAQNNPPVPPKPQPKVQEKADIPVKSSPQAAVPYKKDVGKTLCPLCFSILKGPISDALAHHLRERHQVIQTVHPVEKKLTYKCIHCLGVYTSNMTASTITLHLVHCRGVGKTQNGQDKTNAPSRLNQSPSLAPVKRTYEQMEFPLLKKRKLDDDSDSPSFFEEKPEEPVVLALDPKGHEDDSYEARKSFLTKYFNKQPYPTRREIEKLAASLWLWKSDIASHFSNKRKKCVRDCEKYKPGVLLGFNMKELNKVKHEMDFDAEWLFENHDEKDSRVNASKTADKKLNLGKEDDSSSDSFENLEEESNESGSPFDPVFEVEPKISNDNPEEHVLKVIPEDASESEEKLDQKEDGSKYETIHLTEEPTKLMHNASDSEVDQDDVVEWKDGASPSESGPGSQQVSDFEDNTCEMKPGTWSDESSQSEDARSSKPAAKKKATMQGDREQLKWKNSSYGKVEGFWSKDQSQWKNASENDERLSNPQIEWQNSTIDSEDGEQFDNMTDGVAEPMHGSLAGVKLSSQQA'), ('Q8N157', 'MPTAESEAKVKTKVRFEELLKTHSDLMREKKKLKKKLVRSEENISPDTIRSNLHYMKETTSDDPDTIRSNLPHIKETTSDDVSAANTNNLKKSTRVTKNKLRNTQLATENPNGDASVEEDKQGKPNKKVIKTVPQLTTQDLKPETPENKVDSTHQKTHTKPQPGVDHQKSEKANEGREETDLEEDEELMQAYQCHVTEEMAKEIKRKIRKKLKEQLTYFPSDTLFHDDKLSSEKRKKKKEVPVFSKAETSTLTISGDTVEGEQKKESSVRSVSSDSHQDDEISSMEQSTEDSMQDDTKPKPKKTKKKTKAVADNNEDVDGDGVHEITSRDSPVYPKCLLDDDLVLGVYIHRTDRLKSDFMISHPMVKIHVVDEHTGQYVKKDDSGRPVSSYYEKENVDYILPIMTQPYDFKQLKSRLPEWEEQIVFNENFPYLLRGSDESPKVILFFEILDFLSVDEIKNNSEVQNQECGFRKIAWAFLKLLGANGNANINSKLRLQLYYPPTKPRSPLSVVEAFEWWSKCPRNHYPSTLYVTVRGLKVPDCIKPSYRSMMALQEEKGKPVHCERHHESSSVDTEPGLEESKEVIKWKRLPGQACRIPNKHLFSLNAGERGCFCLDFSHNGRILAAACASRDGYPIILYEIPSGRFMRELCGHLNIIYDLSWSKDDHYILTSSSDGTARIWKNEINNTNTFRVLPHPSFVYTAKFHPAVRELVVTGCYDSMIRIWKVEMREDSAILVRQFDVHKSFINSLCFDTEGHHMYSGDCTGVIVVWNTYVKINDLEHSVHHWTINKEIKETEFKGIPISYLEIHPNGKRLLIHTKDSTLRIMDLRILVARKFVGAANYREKIHSTLTPCGTFLFAGSEDGIVYVWNPETGEQVAMYSDLPFKSPIRDISYHPFENMVAFCAFGQNEPILLYIYDFHVAQQEAEMFKRYNGTFPLPGIHQSQDALCTCPKLPHQGSFQIDEFVHTESSSTKMQLVKQRLETVTEVIRSCAAKVNKNLSFTSPPAVSSQQSKLKQSNMLTAQEILHQFGFTQTGIISIERKPCNHQVDTAPTVVALYDYTANRSDELTIHRGDIIRVFFKDNEDWWYGSIGKGQEGYFPANHVASETLYQELPPEIKERSPPLSPEEKTKIEKSPAPQKQSINKNKSQDFRLGSESMTHSEMRKEQSHEDQGHIMDTRMRKNKQAGRKVTLIE'), ('Q15699', 'MEFLSEKFALKSPPSKNSDFYMGAGGPLEHVMETLDNESFYSKASAGKCVQAFGPLPRAEHHVRLERTSPCQDSSVNYGITKVEGQPLHTELNRAMDNCNSLRMSPVKGMQEKGELDELGDKCDSNVSSSKKRRHRTTFTSLQLEELEKVFQKTHYPDVYVREQLALRTELTEARVQVWFQNRRAKWRKRERYGQIQQAKSHFAATYDISVLPRTDSYPQIQNNLWAGNASGGSVVTSCMLPRDTSSCMTPYSHSPRTDSSYTGFSNHQNQFSHVPLNNFFTDSLLTGATNGHAFETKPEFERRSSSIAVLRMKAKEHTANISWAM')]

In [ ]:
# path = '/Users/johnhutchens/Desktop/Practicum/Data/Domainome/'
# with open(path+"dict_domainome_uniprot.pkl", "wb") as f:
#     pickle.dump(uniprot_dict, f)

In [10]:
def make_mutation_csv(domain_id):

    domain_id_list=domain_id.split("_")
    dom_pos = float(domain_id_list[-1])

    load_dotenv()
    cred_path = os.getenv('GOOGLE_APPLICATION_CREDENTIALS')

    os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = cred_path

    client = storage.Client()
    bucket = client.bucket('domainome-data')
    blob = bucket.blob('SupplementaryTable2.txt')

    df = pd.read_csv(StringIO(blob.download_as_text()), sep='\t')

    df_one_protein = df.where(df['domain_ID'] == domain_id).dropna()

    dom_position = df_one_protein['position'] - dom_pos
    df_one_protein.insert(loc=0, column='real_position', value=dom_position)
    df_one_protein_ns = df_one_protein[df_one_protein['mut_aa'] != '*'].copy()

    df_one_protein_ns['wt_seq'] = df_one_protein_ns.apply(lambda row: 
                                                      insert_wt(row['aa_seq'], row['real_position'], row['wt_aa']),
                                                      axis=1)
    
    df_mutation = df_one_protein_ns[['wt_seq','real_position','mut_aa','normalized_fitness']]
    df_mutation
    df_mutation.to_csv("mutation_"+domain_id+".csv")

In [11]:
make_mutation_csv('A0A2R8Y422_PF00240_2')

In [3]:
load_dotenv()
cred_path = os.getenv('GOOGLE_APPLICATION_CREDENTIALS')

os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = cred_path

client = storage.Client()
bucket = client.bucket('domainome-data')
blob = bucket.blob('SupplementaryTable2.txt')

df = pd.read_csv(StringIO(blob.download_as_text()), sep='\t')

In [23]:
df.head()

,domain_ID,uniprot_ID,aa_seq,wt_aa,position,mut_aa,STOP,input_count_rep1,input_count_rep2,input_count_rep3,output_count_rep1,output_count_rep2,output_count_rep3,mean_input_count,fitness,fitness_sigma,normalized_fitness,normalized_fitness_sigma,quality_rank
0,A0A2R8Y422_PF00240_2,A0A2R8Y422,*IFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2.0,*,True,118.0,113.0,62.0,10.0,29.0,2.0,97.66667,0.030945,0.014885,-0.819050,0.208478,339
1,A0A2R8Y422_PF00240_2,A0A2R8Y422,AIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2.0,A,False,219.0,277.0,217.0,86.0,225.0,137.0,237.66670,0.069376,0.006673,-0.280790,0.093461,339
2,A0A2R8Y422_PF00240_2,A0A2R8Y422,CIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2.0,C,False,706.0,726.0,459.0,768.0,507.0,616.0,630.33330,0.082052,0.004141,-0.103250,0.057995,339
3,A0A2R8Y422_PF00240_2,A0A2R8Y422,DIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2.0,D,False,407.0,431.0,323.0,508.0,159.0,111.0,387.00000,0.071003,0.005162,-0.258003,0.072296,339
4,A0A2R8Y422_PF00240_2,A0A2R8Y422,EIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2.0,E,False,37.0,56.0,37.0,201.0,102.0,95.0,43.33333,0.116326,0.012085,0.376783,0.169263,339

Get data for one domain.  In this case Q8N1P7_PF00030_1358.  Translate position by initial domain position.

In [4]:
df_one_protein = df.where(df['domain_ID'] == 'Q8N1P7_PF00030_1358').dropna()

dom_position = df_one_protein['position'] - 1358.0
df_one_protein.insert(loc=0, column='real_position', value=dom_position)
df_one_protein_ns = df_one_protein[df_one_protein['mut_aa'] != '*'].copy()

df_one_protein_ns.head()

,real_position,domain_ID,uniprot_ID,aa_seq,wt_aa,position,mut_aa,STOP,input_count_rep1,input_count_rep2,input_count_rep3,output_count_rep1,output_count_rep2,output_count_rep3,mean_input_count,fitness,fitness_sigma,normalized_fitness,normalized_fitness_sigma,quality_rank
433445,0.0,Q8N1P7_PF00030_1358,Q8N1P7,AQLFSRPDFLGDHFSFEDDQAALPASFRPQSCRVHGGSWILFDETN...,I,1358.0,A,False,75.0,38.0,108.0,4.0,2.0,1.0,73.666667,0.001176,0.035376,-0.914642,0.168991,53.0
433446,0.0,Q8N1P7_PF00030_1358,Q8N1P7,CQLFSRPDFLGDHFSFEDDQAALPASFRPQSCRVHGGSWILFDETN...,I,1358.0,C,False,57.0,30.0,50.0,2.0,5.0,0.0,45.666667,0.035269,0.037827,-0.751780,0.180697,53.0
433447,0.0,Q8N1P7_PF00030_1358,Q8N1P7,DQLFSRPDFLGDHFSFEDDQAALPASFRPQSCRVHGGSWILFDETN...,I,1358.0,D,False,64.0,49.0,72.0,2.0,4.0,0.0,61.666670,0.016447,0.036889,-0.841690,0.176217,53.0
433448,0.0,Q8N1P7_PF00030_1358,Q8N1P7,EQLFSRPDFLGDHFSFEDDQAALPASFRPQSCRVHGGSWILFDETN...,I,1358.0,E,False,121.0,98.0,62.0,3.0,6.0,0.0,93.666670,0.006830,0.029177,-0.887631,0.139376,53.0
433449,0.0,Q8N1P7_PF00030_1358,Q8N1P7,FQLFSRPDFLGDHFSFEDDQAALPASFRPQSCRVHGGSWILFDETN...,I,1358.0,F,False,69.0,8.0,45.0,1.0,4.0,14.0,40.666670,0.067566,0.029007,-0.597499,0.138567,53.0

In [5]:
df_one_protein_ns['wt_seq'] = df_one_protein_ns.apply(lambda row: 
                                                      insert_wt(row['aa_seq'], row['real_position'], row['wt_aa']),
                                                      axis=1)

In [6]:
df_mutation = df_one_protein_ns[['wt_seq','real_position','mut_aa','normalized_fitness']]
df_mutation
df_mutation.to_csv("mutation_Q8N1P7.csv")

In [7]:
df_mutation.head()

,wt_seq,real_position,mut_aa,normalized_fitness
433445,IQLFSRPDFLGDHFSFEDDQAALPASFRPQSCRVHGGSWILFDETN...,0.0,A,-0.914642
433446,IQLFSRPDFLGDHFSFEDDQAALPASFRPQSCRVHGGSWILFDETN...,0.0,C,-0.751780
433447,IQLFSRPDFLGDHFSFEDDQAALPASFRPQSCRVHGGSWILFDETN...,0.0,D,-0.841690
433448,IQLFSRPDFLGDHFSFEDDQAALPASFRPQSCRVHGGSWILFDETN...,0.0,E,-0.887631
433449,IQLFSRPDFLGDHFSFEDDQAALPASFRPQSCRVHGGSWILFDETN...,0.0,F,-0.597499

Get data for one domain.  In this case P07316_PF00030_87.  Translate position by initial domain position.

In [4]:
df_one_protein = df.where(df['domain_ID'] == 'P07316_PF00030_87').dropna()

dom_position = df_one_protein['position'] - 87.0
df_one_protein.insert(loc=0, column='real_position', value=dom_position)
df_one_protein_ns = df_one_protein[df_one_protein['mut_aa'] != '*'].copy()

df_one_protein_ns.head()

,real_position,domain_ID,uniprot_ID,aa_seq,wt_aa,position,mut_aa,STOP,input_count_rep1,input_count_rep2,input_count_rep3,output_count_rep1,output_count_rep2,output_count_rep3,mean_input_count,fitness,fitness_sigma,normalized_fitness,normalized_fitness_sigma,quality_rank
121785,0.0,P07316_PF00030_87,P07316,AAYRMKIYDRDELRGQMSELTDDCISVQDRFHLTEIHSLNVLEGSW...,G,87.0,A,False,645.0,476.0,327.0,202.0,183.0,264.0,482.6667,0.067864,0.006483,0.163960,0.070917,385.0
121786,0.0,P07316_PF00030_87,P07316,CAYRMKIYDRDELRGQMSELTDDCISVQDRFHLTEIHSLNVLEGSW...,G,87.0,C,False,1155.0,733.0,502.0,198.0,257.0,578.0,796.6667,0.061549,0.005723,0.094874,0.062609,385.0
121787,0.0,P07316_PF00030_87,P07316,DAYRMKIYDRDELRGQMSELTDDCISVQDRFHLTEIHSLNVLEGSW...,G,87.0,D,False,1079.0,784.0,566.0,197.0,220.0,399.0,809.6667,0.054534,0.006000,0.018137,0.065632,385.0
121788,0.0,P07316_PF00030_87,P07316,EAYRMKIYDRDELRGQMSELTDDCISVQDRFHLTEIHSLNVLEGSW...,G,87.0,E,False,305.0,251.0,187.0,75.0,94.0,182.0,247.6667,0.067474,0.008372,0.159687,0.091586,385.0
121789,0.0,P07316_PF00030_87,P07316,FAYRMKIYDRDELRGQMSELTDDCISVQDRFHLTEIHSLNVLEGSW...,G,87.0,F,False,803.0,628.0,463.0,241.0,412.0,729.0,631.3333,0.083318,0.004906,0.333017,0.053670,385.0

Insert mutation into correct position of protein sequence.

In [7]:
df_one_protein_ns['wt_seq'] = df_one_protein_ns.apply(lambda row: 
                                                      insert_wt(row['aa_seq'], row['real_position'], row['wt_aa']),
                                                      axis=1)

In [8]:
df_mutation = df_one_protein_ns[['wt_seq','real_position','mut_aa','normalized_fitness']]
df_mutation
df_mutation.to_csv("mutation.csv")

In [9]:
df_mutation = pd.read_csv('mutation.csv')

Initializing base model Pro Gen 2

In [24]:
# device = "cuda" if torch.cuda.is_available() else "cpu"
device = 'cpu'
print(f"Using {device} device")

model_name = "hugohrban/progen2-medium"
base_model, tokenizer = initialize_progen2_noeval(model_name)

Using cpu device

Initializing LoRA

In [7]:
for name, module in base_model.named_modules():
    print(name)

transformer
transformer.wte
transformer.drop
transformer.h
transformer.h.0
transformer.h.0.ln_1
transformer.h.0.attn
transformer.h.0.attn.attn_dropout
transformer.h.0.attn.resid_dropout
transformer.h.0.attn.qkv_proj
transformer.h.0.attn.out_proj
transformer.h.0.mlp
transformer.h.0.mlp.fc_in
transformer.h.0.mlp.fc_out
transformer.h.0.mlp.act
transformer.h.0.mlp.dropout
transformer.h.1
transformer.h.1.ln_1
transformer.h.1.attn
transformer.h.1.attn.attn_dropout
transformer.h.1.attn.resid_dropout
transformer.h.1.attn.qkv_proj
transformer.h.1.attn.out_proj
transformer.h.1.mlp
transformer.h.1.mlp.fc_in
transformer.h.1.mlp.fc_out
transformer.h.1.mlp.act
transformer.h.1.mlp.dropout
transformer.h.2
transformer.h.2.ln_1
transformer.h.2.attn
transformer.h.2.attn.attn_dropout
transformer.h.2.attn.resid_dropout
transformer.h.2.attn.qkv_proj
transformer.h.2.attn.out_proj
transformer.h.2.mlp
transformer.h.2.mlp.fc_in
transformer.h.2.mlp.fc_out
transformer.h.2.mlp.act
transformer.h.2.mlp.dropout
transformer.h.3
transformer.h.3.ln_1
transformer.h.3.attn
transformer.h.3.attn.attn_dropout
transformer.h.3.attn.resid_dropout
transformer.h.3.attn.qkv_proj
transformer.h.3.attn.out_proj
transformer.h.3.mlp
transformer.h.3.mlp.fc_in
transformer.h.3.mlp.fc_out
transformer.h.3.mlp.act
transformer.h.3.mlp.dropout
transformer.h.4
transformer.h.4.ln_1
transformer.h.4.attn
transformer.h.4.attn.attn_dropout
transformer.h.4.attn.resid_dropout
transformer.h.4.attn.qkv_proj
transformer.h.4.attn.out_proj
transformer.h.4.mlp
transformer.h.4.mlp.fc_in
transformer.h.4.mlp.fc_out
transformer.h.4.mlp.act
transformer.h.4.mlp.dropout
transformer.h.5
transformer.h.5.ln_1
transformer.h.5.attn
transformer.h.5.attn.attn_dropout
transformer.h.5.attn.resid_dropout
transformer.h.5.attn.qkv_proj
transformer.h.5.attn.out_proj
transformer.h.5.mlp
transformer.h.5.mlp.fc_in
transformer.h.5.mlp.fc_out
transformer.h.5.mlp.act
transformer.h.5.mlp.dropout
transformer.h.6
transformer.h.6.ln_1
transformer.h.6.attn
transformer.h.6.attn.attn_dropout
transformer.h.6.attn.resid_dropout
transformer.h.6.attn.qkv_proj
transformer.h.6.attn.out_proj
transformer.h.6.mlp
transformer.h.6.mlp.fc_in
transformer.h.6.mlp.fc_out
transformer.h.6.mlp.act
transformer.h.6.mlp.dropout
transformer.h.7
transformer.h.7.ln_1
transformer.h.7.attn
transformer.h.7.attn.attn_dropout
transformer.h.7.attn.resid_dropout
transformer.h.7.attn.qkv_proj
transformer.h.7.attn.out_proj
transformer.h.7.mlp
transformer.h.7.mlp.fc_in
transformer.h.7.mlp.fc_out
transformer.h.7.mlp.act
transformer.h.7.mlp.dropout
transformer.h.8
transformer.h.8.ln_1
transformer.h.8.attn
transformer.h.8.attn.attn_dropout
transformer.h.8.attn.resid_dropout
transformer.h.8.attn.qkv_proj
transformer.h.8.attn.out_proj
transformer.h.8.mlp
transformer.h.8.mlp.fc_in
transformer.h.8.mlp.fc_out
transformer.h.8.mlp.act
transformer.h.8.mlp.dropout
transformer.h.9
transformer.h.9.ln_1
transformer.h.9.attn
transformer.h.9.attn.attn_dropout
transformer.h.9.attn.resid_dropout
transformer.h.9.attn.qkv_proj
transformer.h.9.attn.out_proj
transformer.h.9.mlp
transformer.h.9.mlp.fc_in
transformer.h.9.mlp.fc_out
transformer.h.9.mlp.act
transformer.h.9.mlp.dropout
transformer.h.10
transformer.h.10.ln_1
transformer.h.10.attn
transformer.h.10.attn.attn_dropout
transformer.h.10.attn.resid_dropout
transformer.h.10.attn.qkv_proj
transformer.h.10.attn.out_proj
transformer.h.10.mlp
transformer.h.10.mlp.fc_in
transformer.h.10.mlp.fc_out
transformer.h.10.mlp.act
transformer.h.10.mlp.dropout
transformer.h.11
transformer.h.11.ln_1
transformer.h.11.attn
transformer.h.11.attn.attn_dropout
transformer.h.11.attn.resid_dropout
transformer.h.11.attn.qkv_proj
transformer.h.11.attn.out_proj
transformer.h.11.mlp
transformer.h.11.mlp.fc_in
transformer.h.11.mlp.fc_out
transformer.h.11.mlp.act
transformer.h.11.mlp.dropout
transformer.h.12
transformer.h.12.ln_1
transformer.h.12.attn
transformer.h.12.attn.attn_dropout
transformer.h.12.attn.resid_dropout
transformer.h.12.attn.qkv_proj
transformer.h.12.attn.out_proj
transformer.h.12.mlp
transformer.h.12.mlp.fc_in
transformer.h.12.mlp.fc_out
transformer.h.12.mlp.act
transformer.h.12.mlp.dropout
transformer.h.13
transformer.h.13.ln_1
transformer.h.13.attn
transformer.h.13.attn.attn_dropout
transformer.h.13.attn.resid_dropout
transformer.h.13.attn.qkv_proj
transformer.h.13.attn.out_proj
transformer.h.13.mlp
transformer.h.13.mlp.fc_in
transformer.h.13.mlp.fc_out
transformer.h.13.mlp.act
transformer.h.13.mlp.dropout
transformer.h.14
transformer.h.14.ln_1
transformer.h.14.attn
transformer.h.14.attn.attn_dropout
transformer.h.14.attn.resid_dropout
transformer.h.14.attn.qkv_proj
transformer.h.14.attn.out_proj
transformer.h.14.mlp
transformer.h.14.mlp.fc_in
transformer.h.14.mlp.fc_out
transformer.h.14.mlp.act
transformer.h.14.mlp.dropout
transformer.h.15
transformer.h.15.ln_1
transformer.h.15.attn
transformer.h.15.attn.attn_dropout
transformer.h.15.attn.resid_dropout
transformer.h.15.attn.qkv_proj
transformer.h.15.attn.out_proj
transformer.h.15.mlp
transformer.h.15.mlp.fc_in
transformer.h.15.mlp.fc_out
transformer.h.15.mlp.act
transformer.h.15.mlp.dropout
transformer.h.16
transformer.h.16.ln_1
transformer.h.16.attn
transformer.h.16.attn.attn_dropout
transformer.h.16.attn.resid_dropout
transformer.h.16.attn.qkv_proj
transformer.h.16.attn.out_proj
transformer.h.16.mlp
transformer.h.16.mlp.fc_in
transformer.h.16.mlp.fc_out
transformer.h.16.mlp.act
transformer.h.16.mlp.dropout
transformer.h.17
transformer.h.17.ln_1
transformer.h.17.attn
transformer.h.17.attn.attn_dropout
transformer.h.17.attn.resid_dropout
transformer.h.17.attn.qkv_proj
transformer.h.17.attn.out_proj
transformer.h.17.mlp
transformer.h.17.mlp.fc_in
transformer.h.17.mlp.fc_out
transformer.h.17.mlp.act
transformer.h.17.mlp.dropout
transformer.h.18
transformer.h.18.ln_1
transformer.h.18.attn
transformer.h.18.attn.attn_dropout
transformer.h.18.attn.resid_dropout
transformer.h.18.attn.qkv_proj
transformer.h.18.attn.out_proj
transformer.h.18.mlp
transformer.h.18.mlp.fc_in
transformer.h.18.mlp.fc_out
transformer.h.18.mlp.act
transformer.h.18.mlp.dropout
transformer.h.19
transformer.h.19.ln_1
transformer.h.19.attn
transformer.h.19.attn.attn_dropout
transformer.h.19.attn.resid_dropout
transformer.h.19.attn.qkv_proj
transformer.h.19.attn.out_proj
transformer.h.19.mlp
transformer.h.19.mlp.fc_in
transformer.h.19.mlp.fc_out
transformer.h.19.mlp.act
transformer.h.19.mlp.dropout
transformer.h.20
transformer.h.20.ln_1
transformer.h.20.attn
transformer.h.20.attn.attn_dropout
transformer.h.20.attn.resid_dropout
transformer.h.20.attn.qkv_proj
transformer.h.20.attn.out_proj
transformer.h.20.mlp
transformer.h.20.mlp.fc_in
transformer.h.20.mlp.fc_out
transformer.h.20.mlp.act
transformer.h.20.mlp.dropout
transformer.h.21
transformer.h.21.ln_1
transformer.h.21.attn
transformer.h.21.attn.attn_dropout
transformer.h.21.attn.resid_dropout
transformer.h.21.attn.qkv_proj
transformer.h.21.attn.out_proj
transformer.h.21.mlp
transformer.h.21.mlp.fc_in
transformer.h.21.mlp.fc_out
transformer.h.21.mlp.act
transformer.h.21.mlp.dropout
transformer.h.22
transformer.h.22.ln_1
transformer.h.22.attn
transformer.h.22.attn.attn_dropout
transformer.h.22.attn.resid_dropout
transformer.h.22.attn.qkv_proj
transformer.h.22.attn.out_proj
transformer.h.22.mlp
transformer.h.22.mlp.fc_in
transformer.h.22.mlp.fc_out
transformer.h.22.mlp.act
transformer.h.22.mlp.dropout
transformer.h.23
transformer.h.23.ln_1
transformer.h.23.attn
transformer.h.23.attn.attn_dropout
transformer.h.23.attn.resid_dropout
transformer.h.23.attn.qkv_proj
transformer.h.23.attn.out_proj
transformer.h.23.mlp
transformer.h.23.mlp.fc_in
transformer.h.23.mlp.fc_out
transformer.h.23.mlp.act
transformer.h.23.mlp.dropout
transformer.h.24
transformer.h.24.ln_1
transformer.h.24.attn
transformer.h.24.attn.attn_dropout
transformer.h.24.attn.resid_dropout
transformer.h.24.attn.qkv_proj
transformer.h.24.attn.out_proj
transformer.h.24.mlp
transformer.h.24.mlp.fc_in
transformer.h.24.mlp.fc_out
transformer.h.24.mlp.act
transformer.h.24.mlp.dropout
transformer.h.25
transformer.h.25.ln_1
transformer.h.25.attn
transformer.h.25.attn.attn_dropout
transformer.h.25.attn.resid_dropout
transformer.h.25.attn.qkv_proj
transformer.h.25.attn.out_proj
transformer.h.25.mlp
transformer.h.25.mlp.fc_in
transformer.h.25.mlp.fc_out
transformer.h.25.mlp.act
transformer.h.25.mlp.dropout
transformer.h.26
transformer.h.26.ln_1
transformer.h.26.attn
transformer.h.26.attn.attn_dropout
transformer.h.26.attn.resid_dropout
transformer.h.26.attn.qkv_proj
transformer.h.26.attn.out_proj
transformer.h.26.mlp
transformer.h.26.mlp.fc_in
transformer.h.26.mlp.fc_out
transformer.h.26.mlp.act
transformer.h.26.mlp.dropout
transformer.ln_f
lm_head

In [25]:
lora_config = LoraConfig(
    r=8,
    lora_alpha=32,
    # target_modules=["query", "key", "value", "output.dense"],
    target_modules=["qkv_proj", "out_proj"],
    lora_dropout=0.1,
    bias="none",
    task_type=TaskType.FEATURE_EXTRACTION
    # task_type=TaskType.CAUSAL_LM
)
model = get_peft_model(base_model, lora_config)

In [26]:
for name, module in base_model.named_modules():
    if "qkv_proj" in name or "out_proj" in name:
        print(name, module)

transformer.h.0.attn.qkv_proj lora.Linear(
  (base_layer): Linear(in_features=1536, out_features=4608, bias=False)
  (lora_dropout): ModuleDict(
    (default): Dropout(p=0.1, inplace=False)
  )
  (lora_A): ModuleDict(
    (default): Linear(in_features=1536, out_features=8, bias=False)
  )
  (lora_B): ModuleDict(
    (default): Linear(in_features=8, out_features=4608, bias=False)
  )
  (lora_embedding_A): ParameterDict()
  (lora_embedding_B): ParameterDict()
  (lora_magnitude_vector): ModuleDict()
)
transformer.h.0.attn.qkv_proj.base_layer Linear(in_features=1536, out_features=4608, bias=False)
transformer.h.0.attn.qkv_proj.lora_dropout ModuleDict(
  (default): Dropout(p=0.1, inplace=False)
)
transformer.h.0.attn.qkv_proj.lora_dropout.default Dropout(p=0.1, inplace=False)
transformer.h.0.attn.qkv_proj.lora_A ModuleDict(
  (default): Linear(in_features=1536, out_features=8, bias=False)
)
transformer.h.0.attn.qkv_proj.lora_A.default Linear(in_features=1536, out_features=8, bias=False)
transformer.h.0.attn.qkv_proj.lora_B ModuleDict(
  (default): Linear(in_features=8, out_features=4608, bias=False)
)
transformer.h.0.attn.qkv_proj.lora_B.default Linear(in_features=8, out_features=4608, bias=False)
transformer.h.0.attn.qkv_proj.lora_embedding_A ParameterDict()
transformer.h.0.attn.qkv_proj.lora_embedding_B ParameterDict()
transformer.h.0.attn.qkv_proj.lora_magnitude_vector ModuleDict()
transformer.h.0.attn.out_proj lora.Linear(
  (base_layer): Linear(in_features=1536, out_features=1536, bias=False)
  (lora_dropout): ModuleDict(
    (default): Dropout(p=0.1, inplace=False)
  )
  (lora_A): ModuleDict(
    (default): Linear(in_features=1536, out_features=8, bias=False)
  )
  (lora_B): ModuleDict(
    (default): Linear(in_features=8, out_features=1536, bias=False)
  )
  (lora_embedding_A): ParameterDict()
  (lora_embedding_B): ParameterDict()
  (lora_magnitude_vector): ModuleDict()
)
transformer.h.0.attn.out_proj.base_layer Linear(in_features=1536, out_features=1536, bias=False)
transformer.h.0.attn.out_proj.lora_dropout ModuleDict(
  (default): Dropout(p=0.1, inplace=False)
)
transformer.h.0.attn.out_proj.lora_dropout.default Dropout(p=0.1, inplace=False)
transformer.h.0.attn.out_proj.lora_A ModuleDict(
  (default): Linear(in_features=1536, out_features=8, bias=False)
)
transformer.h.0.attn.out_proj.lora_A.default Linear(in_features=1536, out_features=8, bias=False)
transformer.h.0.attn.out_proj.lora_B ModuleDict(
  (default): Linear(in_features=8, out_features=1536, bias=False)
)
transformer.h.0.attn.out_proj.lora_B.default Linear(in_features=8, out_features=1536, bias=False)
transformer.h.0.attn.out_proj.lora_embedding_A ParameterDict()
transformer.h.0.attn.out_proj.lora_embedding_B ParameterDict()
transformer.h.0.attn.out_proj.lora_magnitude_vector ModuleDict()
transformer.h.1.attn.qkv_proj lora.Linear(
  (base_layer): Linear(in_features=1536, out_features=4608, bias=False)
  (lora_dropout): ModuleDict(
    (default): Dropout(p=0.1, inplace=False)
  )
  (lora_A): ModuleDict(
    (default): Linear(in_features=1536, out_features=8, bias=False)
  )
  (lora_B): ModuleDict(
    (default): Linear(in_features=8, out_features=4608, bias=False)
  )
  (lora_embedding_A): ParameterDict()
  (lora_embedding_B): ParameterDict()
  (lora_magnitude_vector): ModuleDict()
)
transformer.h.1.attn.qkv_proj.base_layer Linear(in_features=1536, out_features=4608, bias=False)
transformer.h.1.attn.qkv_proj.lora_dropout ModuleDict(
  (default): Dropout(p=0.1, inplace=False)
)
transformer.h.1.attn.qkv_proj.lora_dropout.default Dropout(p=0.1, inplace=False)
transformer.h.1.attn.qkv_proj.lora_A ModuleDict(
  (default): Linear(in_features=1536, out_features=8, bias=False)
)
transformer.h.1.attn.qkv_proj.lora_A.default Linear(in_features=1536, out_features=8, bias=False)
transformer.h.1.attn.qkv_proj.lora_B ModuleDict(
  (default): Linear(in_features=8, out_features=4608, bias=False)
)
transformer.h.1.attn.qkv_proj.lora_B.default Linear(in_features=8, out_features=4608, bias=False)
transformer.h.1.attn.qkv_proj.lora_embedding_A ParameterDict()
transformer.h.1.attn.qkv_proj.lora_embedding_B ParameterDict()
transformer.h.1.attn.qkv_proj.lora_magnitude_vector ModuleDict()
transformer.h.1.attn.out_proj lora.Linear(
  (base_layer): Linear(in_features=1536, out_features=1536, bias=False)
  (lora_dropout): ModuleDict(
    (default): Dropout(p=0.1, inplace=False)
  )
  (lora_A): ModuleDict(
    (default): Linear(in_features=1536, out_features=8, bias=False)
  )
  (lora_B): ModuleDict(
    (default): Linear(in_features=8, out_features=1536, bias=False)
  )
  (lora_embedding_A): ParameterDict()
  (lora_embedding_B): ParameterDict()
  (lora_magnitude_vector): ModuleDict()
)
transformer.h.1.attn.out_proj.base_layer Linear(in_features=1536, out_features=1536, bias=False)
transformer.h.1.attn.out_proj.lora_dropout ModuleDict(
  (default): Dropout(p=0.1, inplace=False)
)
transformer.h.1.attn.out_proj.lora_dropout.default Dropout(p=0.1, inplace=False)
transformer.h.1.attn.out_proj.lora_A ModuleDict(
  (default): Linear(in_features=1536, out_features=8, bias=False)
)
transformer.h.1.attn.out_proj.lora_A.default Linear(in_features=1536, out_features=8, bias=False)
transformer.h.1.attn.out_proj.lora_B ModuleDict(
  (default): Linear(in_features=8, out_features=1536, bias=False)
)
transformer.h.1.attn.out_proj.lora_B.default Linear(in_features=8, out_features=1536, bias=False)
transformer.h.1.attn.out_proj.lora_embedding_A ParameterDict()
transformer.h.1.attn.out_proj.lora_embedding_B ParameterDict()
transformer.h.1.attn.out_proj.lora_magnitude_vector ModuleDict()
transformer.h.2.attn.qkv_proj lora.Linear(
  (base_layer): Linear(in_features=1536, out_features=4608, bias=False)
  (lora_dropout): ModuleDict(
    (default): Dropout(p=0.1, inplace=False)
  )
  (lora_A): ModuleDict(
    (default): Linear(in_features=1536, out_features=8, bias=False)
  )
  (lora_B): ModuleDict(
    (default): Linear(in_features=8, out_features=4608, bias=False)
  )
  (lora_embedding_A): ParameterDict()
  (lora_embedding_B): ParameterDict()
  (lora_magnitude_vector): ModuleDict()
)
transformer.h.2.attn.qkv_proj.base_layer Linear(in_features=1536, out_features=4608, bias=False)
transformer.h.2.attn.qkv_proj.lora_dropout ModuleDict(
  (default): Dropout(p=0.1, inplace=False)
)
transformer.h.2.attn.qkv_proj.lora_dropout.default Dropout(p=0.1, inplace=False)
transformer.h.2.attn.qkv_proj.lora_A ModuleDict(
  (default): Linear(in_features=1536, out_features=8, bias=False)
)
transformer.h.2.attn.qkv_proj.lora_A.default Linear(in_features=1536, out_features=8, bias=False)
transformer.h.2.attn.qkv_proj.lora_B ModuleDict(
  (default): Linear(in_features=8, out_features=4608, bias=False)
)
transformer.h.2.attn.qkv_proj.lora_B.default Linear(in_features=8, out_features=4608, bias=False)
transformer.h.2.attn.qkv_proj.lora_embedding_A ParameterDict()
transformer.h.2.attn.qkv_proj.lora_embedding_B ParameterDict()
transformer.h.2.attn.qkv_proj.lora_magnitude_vector ModuleDict()
transformer.h.2.attn.out_proj lora.Linear(
  (base_layer): Linear(in_features=1536, out_features=1536, bias=False)
  (lora_dropout): ModuleDict(
    (default): Dropout(p=0.1, inplace=False)
  )
  (lora_A): ModuleDict(
    (default): Linear(in_features=1536, out_features=8, bias=False)
  )
  (lora_B): ModuleDict(
    (default): Linear(in_features=8, out_features=1536, bias=False)
  )
  (lora_embedding_A): ParameterDict()
  (lora_embedding_B): ParameterDict()
  (lora_magnitude_vector): ModuleDict()
)
transformer.h.2.attn.out_proj.base_layer Linear(in_features=1536, out_features=1536, bias=False)
transformer.h.2.attn.out_proj.lora_dropout ModuleDict(
  (default): Dropout(p=0.1, inplace=False)
)
transformer.h.2.attn.out_proj.lora_dropout.default Dropout(p=0.1, inplace=False)
transformer.h.2.attn.out_proj.lora_A ModuleDict(
  (default): Linear(in_features=1536, out_features=8, bias=False)
)
transformer.h.2.attn.out_proj.lora_A.default Linear(in_features=1536, out_features=8, bias=False)
transformer.h.2.attn.out_proj.lora_B ModuleDict(
  (default): Linear(in_features=8, out_features=1536, bias=False)
)
transformer.h.2.attn.out_proj.lora_B.default Linear(in_features=8, out_features=1536, bias=False)
transformer.h.2.attn.out_proj.lora_embedding_A ParameterDict()
transformer.h.2.attn.out_proj.lora_embedding_B ParameterDict()
transformer.h.2.attn.out_proj.lora_magnitude_vector ModuleDict()
transformer.h.3.attn.qkv_proj lora.Linear(
  (base_layer): Linear(in_features=1536, out_features=4608, bias=False)
  (lora_dropout): ModuleDict(
    (default): Dropout(p=0.1, inplace=False)
  )
  (lora_A): ModuleDict(
    (default): Linear(in_features=1536, out_features=8, bias=False)
  )
  (lora_B): ModuleDict(
    (default): Linear(in_features=8, out_features=4608, bias=False)
  )
  (lora_embedding_A): ParameterDict()
  (lora_embedding_B): ParameterDict()
  (lora_magnitude_vector): ModuleDict()
)
transformer.h.3.attn.qkv_proj.base_layer Linear(in_features=1536, out_features=4608, bias=False)
transformer.h.3.attn.qkv_proj.lora_dropout ModuleDict(
  (default): Dropout(p=0.1, inplace=False)
)
transformer.h.3.attn.qkv_proj.lora_dropout.default Dropout(p=0.1, inplace=False)
transformer.h.3.attn.qkv_proj.lora_A ModuleDict(
  (default): Linear(in_features=1536, out_features=8, bias=False)
)
transformer.h.3.attn.qkv_proj.lora_A.default Linear(in_features=1536, out_features=8, bias=False)
transformer.h.3.attn.qkv_proj.lora_B ModuleDict(
  (default): Linear(in_features=8, out_features=4608, bias=False)
)
transformer.h.3.attn.qkv_proj.lora_B.default Linear(in_features=8, out_features=4608, bias=False)
transformer.h.3.attn.qkv_proj.lora_embedding_A ParameterDict()
transformer.h.3.attn.qkv_proj.lora_embedding_B ParameterDict()
transformer.h.3.attn.qkv_proj.lora_magnitude_vector ModuleDict()
transformer.h.3.attn.out_proj lora.Linear(
  (base_layer): Linear(in_features=1536, out_features=1536, bias=False)
  (lora_dropout): ModuleDict(
    (default): Dropout(p=0.1, inplace=False)
  )
  (lora_A): ModuleDict(
    (default): Linear(in_features=1536, out_features=8, bias=False)
  )
  (lora_B): ModuleDict(
    (default): Linear(in_features=8, out_features=1536, bias=False)
  )
  (lora_embedding_A): ParameterDict()
  (lora_embedding_B): ParameterDict()
  (lora_magnitude_vector): ModuleDict()
)
transformer.h.3.attn.out_proj.base_layer Linear(in_features=1536, out_features=1536, bias=False)
transformer.h.3.attn.out_proj.lora_dropout ModuleDict(
  (default): Dropout(p=0.1, inplace=False)
)
transformer.h.3.attn.out_proj.lora_dropout.default Dropout(p=0.1, inplace=False)
transformer.h.3.attn.out_proj.lora_A ModuleDict(
  (default): Linear(in_features=1536, out_features=8, bias=False)
)
transformer.h.3.attn.out_proj.lora_A.default Linear(in_features=1536, out_features=8, bias=False)
transformer.h.3.attn.out_proj.lora_B ModuleDict(
  (default): Linear(in_features=8, out_features=1536, bias=False)
)
transformer.h.3.attn.out_proj.lora_B.default Linear(in_features=8, out_features=1536, bias=False)
transformer.h.3.attn.out_proj.lora_embedding_A ParameterDict()
transformer.h.3.attn.out_proj.lora_embedding_B ParameterDict()
transformer.h.3.attn.out_proj.lora_magnitude_vector ModuleDict()
transformer.h.4.attn.qkv_proj lora.Linear(
  (base_layer): Linear(in_features=1536, out_features=4608, bias=False)
  (lora_dropout): ModuleDict(
    (default): Dropout(p=0.1, inplace=False)
  )
  (lora_A): ModuleDict(
    (default): Linear(in_features=1536, out_features=8, bias=False)
  )
  (lora_B): ModuleDict(
    (default): Linear(in_features=8, out_features=4608, bias=False)
  )
  (lora_embedding_A): ParameterDict()
  (lora_embedding_B): ParameterDict()
  (lora_magnitude_vector): ModuleDict()
)
transformer.h.4.attn.qkv_proj.base_layer Linear(in_features=1536, out_features=4608, bias=False)
transformer.h.4.attn.qkv_proj.lora_dropout ModuleDict(
  (default): Dropout(p=0.1, inplace=False)
)
transformer.h.4.attn.qkv_proj.lora_dropout.default Dropout(p=0.1, inplace=False)
transformer.h.4.attn.qkv_proj.lora_A ModuleDict(
  (default): Linear(in_features=1536, out_features=8, bias=False)
)
transformer.h.4.attn.qkv_proj.lora_A.default Linear(in_features=1536, out_features=8, bias=False)
transformer.h.4.attn.qkv_proj.lora_B ModuleDict(
  (default): Linear(in_features=8, out_features=4608, bias=False)
)
transformer.h.4.attn.qkv_proj.lora_B.default Linear(in_features=8, out_features=4608, bias=False)
transformer.h.4.attn.qkv_proj.lora_embedding_A ParameterDict()
transformer.h.4.attn.qkv_proj.lora_embedding_B ParameterDict()
transformer.h.4.attn.qkv_proj.lora_magnitude_vector ModuleDict()
transformer.h.4.attn.out_proj lora.Linear(
  (base_layer): Linear(in_features=1536, out_features=1536, bias=False)
  (lora_dropout): ModuleDict(
    (default): Dropout(p=0.1, inplace=False)
  )
  (lora_A): ModuleDict(
    (default): Linear(in_features=1536, out_features=8, bias=False)
  )
  (lora_B): ModuleDict(
    (default): Linear(in_features=8, out_features=1536, bias=False)
  )
  (lora_embedding_A): ParameterDict()
  (lora_embedding_B): ParameterDict()
  (lora_magnitude_vector): ModuleDict()
)
transformer.h.4.attn.out_proj.base_layer Linear(in_features=1536, out_features=1536, bias=False)
transformer.h.4.attn.out_proj.lora_dropout ModuleDict(
  (default): Dropout(p=0.1, inplace=False)
)
transformer.h.4.attn.out_proj.lora_dropout.default Dropout(p=0.1, inplace=False)
transformer.h.4.attn.out_proj.lora_A ModuleDict(
  (default): Linear(in_features=1536, out_features=8, bias=False)
)
transformer.h.4.attn.out_proj.lora_A.default Linear(in_features=1536, out_features=8, bias=False)
transformer.h.4.attn.out_proj.lora_B ModuleDict(
  (default): Linear(in_features=8, out_features=1536, bias=False)
)
transformer.h.4.attn.out_proj.lora_B.default Linear(in_features=8, out_features=1536, bias=False)
transformer.h.4.attn.out_proj.lora_embedding_A ParameterDict()
transformer.h.4.attn.out_proj.lora_embedding_B ParameterDict()
transformer.h.4.attn.out_proj.lora_magnitude_vector ModuleDict()
transformer.h.5.attn.qkv_proj lora.Linear(
  (base_layer): Linear(in_features=1536, out_features=4608, bias=False)
  (lora_dropout): ModuleDict(
    (default): Dropout(p=0.1, inplace=False)
  )
  (lora_A): ModuleDict(
    (default): Linear(in_features=1536, out_features=8, bias=False)
  )
  (lora_B): ModuleDict(
    (default): Linear(in_features=8, out_features=4608, bias=False)
  )
  (lora_embedding_A): ParameterDict()
  (lora_embedding_B): ParameterDict()
  (lora_magnitude_vector): ModuleDict()
)
transformer.h.5.attn.qkv_proj.base_layer Linear(in_features=1536, out_features=4608, bias=False)
transformer.h.5.attn.qkv_proj.lora_dropout ModuleDict(
  (default): Dropout(p=0.1, inplace=False)
)
transformer.h.5.attn.qkv_proj.lora_dropout.default Dropout(p=0.1, inplace=False)
transformer.h.5.attn.qkv_proj.lora_A ModuleDict(
  (default): Linear(in_features=1536, out_features=8, bias=False)
)
transformer.h.5.attn.qkv_proj.lora_A.default Linear(in_features=1536, out_features=8, bias=False)
transformer.h.5.attn.qkv_proj.lora_B ModuleDict(
  (default): Linear(in_features=8, out_features=4608, bias=False)
)
transformer.h.5.attn.qkv_proj.lora_B.default Linear(in_features=8, out_features=4608, bias=False)
transformer.h.5.attn.qkv_proj.lora_embedding_A ParameterDict()
transformer.h.5.attn.qkv_proj.lora_embedding_B ParameterDict()
transformer.h.5.attn.qkv_proj.lora_magnitude_vector ModuleDict()
transformer.h.5.attn.out_proj lora.Linear(
  (base_layer): Linear(in_features=1536, out_features=1536, bias=False)
  (lora_dropout): ModuleDict(
    (default): Dropout(p=0.1, inplace=False)
  )
  (lora_A): ModuleDict(
    (default): Linear(in_features=1536, out_features=8, bias=False)
  )
  (lora_B): ModuleDict(
    (default): Linear(in_features=8, out_features=1536, bias=False)
  )
  (lora_embedding_A): ParameterDict()
  (lora_embedding_B): ParameterDict()
  (lora_magnitude_vector): ModuleDict()
)
transformer.h.5.attn.out_proj.base_layer Linear(in_features=1536, out_features=1536, bias=False)
transformer.h.5.attn.out_proj.lora_dropout ModuleDict(
  (default): Dropout(p=0.1, inplace=False)
)
transformer.h.5.attn.out_proj.lora_dropout.default Dropout(p=0.1, inplace=False)
transformer.h.5.attn.out_proj.lora_A ModuleDict(
  (default): Linear(in_features=1536, out_features=8, bias=False)
)
transformer.h.5.attn.out_proj.lora_A.default Linear(in_features=1536, out_features=8, bias=False)
transformer.h.5.attn.out_proj.lora_B ModuleDict(
  (default): Linear(in_features=8, out_features=1536, bias=False)
)
transformer.h.5.attn.out_proj.lora_B.default Linear(in_features=8, out_features=1536, bias=False)
transformer.h.5.attn.out_proj.lora_embedding_A ParameterDict()
transformer.h.5.attn.out_proj.lora_embedding_B ParameterDict()
transformer.h.5.attn.out_proj.lora_magnitude_vector ModuleDict()
transformer.h.6.attn.qkv_proj lora.Linear(
  (base_layer): Linear(in_features=1536, out_features=4608, bias=False)
  (lora_dropout): ModuleDict(
    (default): Dropout(p=0.1, inplace=False)
  )
  (lora_A): ModuleDict(
    (default): Linear(in_features=1536, out_features=8, bias=False)
  )
  (lora_B): ModuleDict(
    (default): Linear(in_features=8, out_features=4608, bias=False)
  )
  (lora_embedding_A): ParameterDict()
  (lora_embedding_B): ParameterDict()
  (lora_magnitude_vector): ModuleDict()
)
transformer.h.6.attn.qkv_proj.base_layer Linear(in_features=1536, out_features=4608, bias=False)
transformer.h.6.attn.qkv_proj.lora_dropout ModuleDict(
  (default): Dropout(p=0.1, inplace=False)
)
transformer.h.6.attn.qkv_proj.lora_dropout.default Dropout(p=0.1, inplace=False)
transformer.h.6.attn.qkv_proj.lora_A ModuleDict(
  (default): Linear(in_features=1536, out_features=8, bias=False)
)
transformer.h.6.attn.qkv_proj.lora_A.default Linear(in_features=1536, out_features=8, bias=False)
transformer.h.6.attn.qkv_proj.lora_B ModuleDict(
  (default): Linear(in_features=8, out_features=4608, bias=False)
)
transformer.h.6.attn.qkv_proj.lora_B.default Linear(in_features=8, out_features=4608, bias=False)
transformer.h.6.attn.qkv_proj.lora_embedding_A ParameterDict()
transformer.h.6.attn.qkv_proj.lora_embedding_B ParameterDict()
transformer.h.6.attn.qkv_proj.lora_magnitude_vector ModuleDict()
transformer.h.6.attn.out_proj lora.Linear(
  (base_layer): Linear(in_features=1536, out_features=1536, bias=False)
  (lora_dropout): ModuleDict(
    (default): Dropout(p=0.1, inplace=False)
  )
  (lora_A): ModuleDict(
    (default): Linear(in_features=1536, out_features=8, bias=False)
  )
  (lora_B): ModuleDict(
    (default): Linear(in_features=8, out_features=1536, bias=False)
  )
  (lora_embedding_A): ParameterDict()
  (lora_embedding_B): ParameterDict()
  (lora_magnitude_vector): ModuleDict()
)
transformer.h.6.attn.out_proj.base_layer Linear(in_features=1536, out_features=1536, bias=False)
transformer.h.6.attn.out_proj.lora_dropout ModuleDict(
  (default): Dropout(p=0.1, inplace=False)
)
transformer.h.6.attn.out_proj.lora_dropout.default Dropout(p=0.1, inplace=False)
transformer.h.6.attn.out_proj.lora_A ModuleDict(
  (default): Linear(in_features=1536, out_features=8, bias=False)
)
transformer.h.6.attn.out_proj.lora_A.default Linear(in_features=1536, out_features=8, bias=False)
transformer.h.6.attn.out_proj.lora_B ModuleDict(
  (default): Linear(in_features=8, out_features=1536, bias=False)
)
transformer.h.6.attn.out_proj.lora_B.default Linear(in_features=8, out_features=1536, bias=False)
transformer.h.6.attn.out_proj.lora_embedding_A ParameterDict()
transformer.h.6.attn.out_proj.lora_embedding_B ParameterDict()
transformer.h.6.attn.out_proj.lora_magnitude_vector ModuleDict()
transformer.h.7.attn.qkv_proj lora.Linear(
  (base_layer): Linear(in_features=1536, out_features=4608, bias=False)
  (lora_dropout): ModuleDict(
    (default): Dropout(p=0.1, inplace=False)
  )
  (lora_A): ModuleDict(
    (default): Linear(in_features=1536, out_features=8, bias=False)
  )
  (lora_B): ModuleDict(

Set device and optimizer

In [27]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
optimizer = torch.optim.AdamW(model.parameters(), lr=1e-5)
# optimizer = torch.optim.AdamW(
#     filter(lambda p: p.requires_grad, model.parameters()), lr=1e-2
# )

Load protein sequence and experimental data

In [28]:
protein_seq = 'EDGINLEEIREFAKNFKIRRLSLGLTQTQVGQALTATEGPAYSQSAICRFEKLDITPKSAQKLKPVLEKWLNEAELRNQEGQQNLMEFVG'
fitness_data = df_mutation

In [12]:
len(protein_seq)

90

Making experimental tensor

In [29]:
fitness_data.reset_index(drop=True, inplace=True)

positions = np.arange(len(protein_seq))
# amino_acids = ['L', 'A', 'G', 'V', 'S', 'E', 'R', 'T', 'I',
#                'D', 'P', 'K', 'Q', 'N', 'F', 'Y', 'M', 'H', 'W', 'C']

amino_acids = 'ACDEFGHIKLMNPQRSTVWY'
aa_token_ids = [tokenizer.convert_tokens_to_ids(aa) for aa in amino_acids]

Construct df2.  Mutation and real position in the domain.

In [30]:
positions_col = np.repeat(positions, len(amino_acids))
amino_acids_col = np.tile(list(amino_acids), len(positions))
df2 = pd.DataFrame({'real_position': positions_col, 'mut_aa': amino_acids_col})

In [31]:
df2.tail()

      real_position mut_aa
1795             89      S
1796             89      T
1797             89      V
1798             89      W
1799             89      Y

In [32]:
df_merged = df2.merge(
    fitness_data,
    on=['real_position', 'mut_aa'],
    how='left')

Construct experimental tensor

In [18]:
fitness_list = df_merged['normalized_fitness'].tolist()
fitness_tensor = torch.tensor(fitness_list)
exp_tensor = fitness_tensor
seq_len = exp_tensor.shape[0]

Set up train, validate, test

In [33]:
all_indices = torch.randperm(seq_len)

num_train = int(seq_len * 0.5)
num_val   = int(seq_len * 0.25)
num_test  = seq_len - num_train - num_val

train_indices = all_indices[:num_train] # len 900
val_indices   = all_indices[num_train:num_train + num_val]
test_indices  = all_indices[num_train + num_val:]

In [44]:
torch.isnan(ft_tensor).sum().item()
len(ft_tensor)

1800

Fine-tuning model

In [46]:
train_losses = []
val_losses = []
early_stop_count = 0


vocab_dict = tokenizer.get_vocab()
seq_list = list(protein_seq)
inputs = tokenizer(protein_seq, return_tensors="pt").to(device)

for epoch in range(5):
    model.train()
    outputs = model(**inputs)
    logits = outputs.logits.squeeze(0)  # (seq_len, vocab_size)


    # Compute LLR ----
    # wt_logits = torch.log_softmax(logits, dim=-1)
    # wt_logits = wt_logits[1:-1, :]

    wt_logits = torch.log_softmax(logits, dim=-1)
    # wt_logits = wt_logits[1:-1, :]

    residue_indices = torch.arange(len(protein_seq))


    # ignoring BOS token
    seq_indices = [vocab_dict[aa] for aa in seq_list]
    wt_norm_tensor = wt_logits[residue_indices, seq_indices].unsqueeze(-1)
    LLR_tensor = wt_logits - wt_norm_tensor
    LLR_tensor_aa_only = LLR_tensor[:, aa_token_ids]

    #flatten the LLR_tensor
    flattened_LLR_tensor = LLR_tensor_aa_only.flatten()
    flattened_exp_tensor = exp_tensor.to(device)
    flattened_LLR_tensor = flattened_LLR_tensor.to(device)

    #to stack
    combined = torch.stack([flattened_LLR_tensor, flattened_exp_tensor], dim=0)
    ft_tensor = torch.transpose(combined, 0, 1)

    predicted_scores = []
    experimental_values = []

    train_tensor = ft_tensor[train_indices]

    #drop nan
    train_tensor = train_tensor[~torch.any(train_tensor.isnan(), dim=1)]

    num_samples = 45
    positions = train_tensor[torch.randperm(len(train_tensor))[:num_samples]]

    predicts = positions[:, 0] #LLR
    targets = positions[:, 1] #exp

# Compute loss with predicts and targets
    loss = listwise_ranking_loss(predicts, targets)
    # log_probs = torch.log_softmax(logits, dim=-1)
    # loss = -log_probs[torch.arange(len(seq_indices)), seq_indices].mean() # needs to be difference of predict/target
    loss.backward()
    # for name, param in model.named_parameters():
    #     if param.requires_grad:
    #         print(name, param.grad.abs().mean())
    optimizer.step()
    optimizer.zero_grad()

    train_losses.append(loss.item())

    # ----------- VALIDATION (no backprop) -----------
    model.eval()
    with torch.no_grad():
      val_tensor = ft_tensor[val_indices]
      val_tensor = val_tensor [~torch.any(val_tensor.isnan(), dim=1)]

      num_samples = 45
      positions = val_tensor[torch.randperm(len(val_tensor))[:num_samples]]

      predicts = positions[:, 0] #LLR
      targets = positions[:, 1] #exp

      val_loss = listwise_ranking_loss(predicts, targets)
    #   val_log_probs = torch.log_softmax(logits, dim=-1)
    #   val_loss = -log_probs[torch.arange(len(seq_indices)), seq_indices].mean()
      val_losses.append(val_loss.item())


    print(f"Epoch {epoch+1} - Training Loss: {loss.item():.4f} | Validation Loss: {val_loss.item():.4f}")

    if val_loss.item() > loss.item():
        early_stop_count += 1
    else:
        early_stop_count = 0

    # if early_stop_count > 2:
    #     print("Validation loss exceeded training loss 3 times — early stopping.")
    #     break
    print(early_stop_count)

Epoch 1 - Training Loss: 4.0722 | Validation Loss: 3.8892
0
Epoch 2 - Training Loss: 6.2683 | Validation Loss: 7.6440
1
Epoch 3 - Training Loss: 4.7224 | Validation Loss: 8.7543
2
Epoch 4 - Training Loss: 6.2425 | Validation Loss: 3.9620
0
Epoch 5 - Training Loss: 8.6166 | Validation Loss: 5.2189
0

In [46]:
#claude version

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
optimizer = torch.optim.AdamW(model.parameters(), lr=1e-2)

train_losses = []
val_losses = []
early_stop_count = 0
# patience = 3  # stop if validation loss worse than training for 3 epochs

vocab_dict = tokenizer.get_vocab()
seq_list = list(protein_seq)
inputs = tokenizer(protein_seq, return_tensors="pt").to(device)

for epoch in range(25):
    # -------------------- TRAINING --------------------
    model.train()
    outputs = model(**inputs)
    logits = outputs.logits.squeeze(0)  # (seq_len, vocab_size)

    # Compute log-softmax
    wt_logits = torch.log_softmax(logits, dim=-1)
    seq_indices = torch.tensor([vocab_dict[aa] for aa in seq_list], device=device)

    # Compute LLR
    wt_norm_tensor = wt_logits[torch.arange(len(seq_indices)), seq_indices].unsqueeze(-1)
    LLR_tensor = wt_logits - wt_norm_tensor
    LLR_tensor_aa_only = LLR_tensor[:, aa_token_ids]  # only relevant positions

    # Flatten LLR and stack with experimental values
    flattened_LLR = LLR_tensor_aa_only.flatten()
    flattened_exp = exp_tensor.to(device).flatten()
    combined = torch.stack([flattened_LLR, flattened_exp], dim=0).T  # shape (num_positions, 2)

    # ----- TRAINING SAMPLE -----
    train_tensor = combined[train_indices]
    train_tensor = train_tensor[~torch.any(torch.isnan(train_tensor), dim=1)]
    num_samples = min(20, len(train_tensor))  # sample at most 20
    positions = train_tensor[torch.randperm(len(train_tensor))[:num_samples]]

    predicts = positions[:, 0]  # LLR (model output)
    targets  = positions[:, 1]  # experimental values

    # Compute loss and update model
    # loss = listwise_ranking_loss(predicts, targets)
    log_probs = torch.log_softmax(logits, dim=-1)
    loss = -log_probs[torch.arange(len(seq_indices)), seq_indices].mean()

    loss.backward()
    optimizer.step()
    optimizer.zero_grad()

    train_losses.append(loss.item())

    # -------------------- VALIDATION --------------------
    model.eval()
    with torch.no_grad():
        val_tensor = combined[val_indices]
        val_tensor = val_tensor[~torch.any(torch.isnan(val_tensor), dim=1)]
        num_samples = min(20, len(val_tensor))
        positions = val_tensor[torch.randperm(len(val_tensor))[:num_samples]]

        predicts = positions[:, 0]  # LLR (model output)
        targets  = positions[:, 1]  # experimental values

        val_loss = listwise_ranking_loss(predicts, targets)
        val_losses.append(val_loss.item())

    print(f"Epoch {epoch+1}: Train Loss={loss.item():.4f}, Val Loss={val_loss.item():.4f}")

    # -------------------- EARLY STOPPING --------------------
    if val_loss.item() > loss.item():
        early_stop_count += 1
    else:
        early_stop_count = 0

    # if early_stop_count >= patience:
        # print(f"Validation loss worse than training for {patience} epochs — stopping early.")
        # break

Epoch 1: Train Loss=2.8409, Val Loss=3.2123
Epoch 2: Train Loss=2.5069, Val Loss=3.5412
Epoch 3: Train Loss=2.7355, Val Loss=3.5857
Epoch 4: Train Loss=2.6267, Val Loss=2.9759
Epoch 5: Train Loss=2.5131, Val Loss=3.6371
Epoch 6: Train Loss=2.5017, Val Loss=3.2982
Epoch 7: Train Loss=2.5060, Val Loss=2.8247
Epoch 8: Train Loss=2.5434, Val Loss=5.1258
Epoch 9: Train Loss=2.5262, Val Loss=3.3827
Epoch 10: Train Loss=2.5601, Val Loss=3.5680
Epoch 11: Train Loss=2.5698, Val Loss=2.7012
Epoch 12: Train Loss=2.5365, Val Loss=2.8318
Epoch 13: Train Loss=2.5141, Val Loss=4.9416
Epoch 14: Train Loss=2.4272, Val Loss=3.6623
Epoch 15: Train Loss=2.3071, Val Loss=2.9301
Epoch 16: Train Loss=2.2520, Val Loss=3.8477
Epoch 17: Train Loss=2.2393, Val Loss=3.8944
Epoch 18: Train Loss=2.2191, Val Loss=2.9857
Epoch 19: Train Loss=2.2761, Val Loss=3.5107
Epoch 20: Train Loss=2.2045, Val Loss=4.0313
Epoch 21: Train Loss=2.2986, Val Loss=3.2254
Epoch 22: Train Loss=2.4294, Val Loss=2.8606
Epoch 23: Train Loss=2.4031, Val Loss=4.4345
Epoch 24: Train Loss=2.5932, Val Loss=3.2221
Epoch 25: Train Loss=2.2662, Val Loss=3.3524

In [45]:
# chat gpt version
# Make sure model and base_model are on the same device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
base_model.to(device)

# Tokenize input sequence
inputs = tokenizer(protein_seq, return_tensors="pt").to(device)

# Compute logits for the base model (for comparison)
with torch.no_grad():
    out_base = base_model(**inputs).logits

# Make a single training step for PEFT model
model.train()
optimizer = torch.optim.AdamW(model.parameters(), lr=1e-2)  # small step

# Forward pass
outputs = model(**inputs)
logits = outputs.logits.squeeze(0)

# Example: compute simple loss to make gradients nonzero
# Here, let's just use negative log-likelihood for the sequence
vocab_dict = tokenizer.get_vocab()
seq_indices = torch.tensor([vocab_dict[aa] for aa in protein_seq], device=device)
log_probs = torch.log_softmax(logits, dim=-1)
loss = -log_probs[torch.arange(len(seq_indices)), seq_indices].mean()

# Backprop and one optimizer step
loss.backward()
optimizer.step()
optimizer.zero_grad()

# Compare outputs after one step
with torch.no_grad():
    out_peft = model(**inputs).logits
    diff = out_peft - out_base
    print("Max absolute difference:", diff.abs().max().item())
    print("First 10 tokens diff:", diff[0, :10])

Max absolute difference: 16.70229148864746
First 10 tokens diff: tensor([[ 2.3636e-01,  2.3524e-01, -2.4843e-02, -1.1305e-01,  6.3858e-02,
         -7.0484e-02,  4.4346e-01, -6.5460e-03,  2.5834e-01,  2.2706e-01,
         -1.2011e+00,  1.8514e-01,  2.7653e-02, -3.8088e-01, -2.3570e-01,
         -3.0223e-01, -2.4527e-01,  9.7426e-01,  7.4787e-02, -4.2507e-02,
          1.9923e-01, -3.2951e-02, -7.8927e-01, -1.4070e-01,  5.7520e-01,
         -1.9855e-01, -3.1161e-01, -8.5537e-02, -6.6688e-01,  2.2422e-01,
          2.3516e-01,  2.3354e-01],
        [ 2.4007e-01,  2.3892e-01, -2.0220e-02, -1.1382e-01,  5.5347e-02,
         -8.0799e-02,  4.5126e-01, -8.7547e-03,  2.5403e-01,  2.1624e-01,
         -1.2114e+00,  1.7251e-01,  2.6264e-02, -3.8932e-01, -2.4163e-01,
         -3.1277e-01, -2.4706e-01,  9.7871e-01,  7.9323e-02, -5.3619e-02,
          1.9191e-01, -4.7081e-02, -7.9730e-01, -1.4660e-01,  5.7718e-01,
         -2.0702e-01, -3.2552e-01, -9.1362e-02, -6.6901e-01,  2.2364e-01,
          2.3882e-01,  2.3719e-01],
        [ 2.3267e-01,  2.3143e-01, -2.9675e-02, -1.1543e-01,  4.4601e-02,
         -8.0658e-02,  4.7861e-01, -2.6012e-02,  2.7898e-01,  2.2466e-01,
         -1.1969e+00,  1.8551e-01,  2.0298e-02, -3.7013e-01, -2.6107e-01,
         -3.2640e-01, -2.6191e-01,  9.9488e-01,  8.7631e-02, -7.0774e-02,
          1.5960e-01, -5.1601e-02, -8.0155e-01, -1.6240e-01,  5.7355e-01,
         -2.1185e-01, -3.2742e-01, -9.0652e-02, -6.5535e-01,  2.1594e-01,
          2.3144e-01,  2.2986e-01],
        [ 2.1213e-01,  2.1104e-01, -5.5506e-02, -1.2605e-01,  2.9095e-02,
         -8.8459e-02,  4.2775e-01, -3.5381e-02,  2.5355e-01,  2.2525e-01,
         -1.2070e+00,  1.6628e-01,  1.4732e-02, -3.7740e-01, -2.6407e-01,
         -3.1832e-01, -2.5478e-01,  9.8796e-01,  6.5273e-02, -6.6391e-02,
          1.7532e-01, -5.9765e-02, -8.0894e-01, -1.5815e-01,  5.2280e-01,
         -2.1827e-01, -3.4889e-01, -1.0612e-01, -6.7173e-01,  1.9365e-01,
          2.1089e-01,  2.0942e-01],
        [-4.1661e-01, -4.1595e-01,  1.4634e-01, -1.1597e-02,  3.4573e-01,
          2.7184e-02, -1.3027e+00,  4.5612e-01, -1.5068e+00, -9.0873e-01,
          1.6345e+00, -1.1384e+00, -2.2598e-01, -2.8391e-01,  5.9258e-01,
          5.8894e-01,  4.4892e-01, -3.2155e+00, -3.2376e-01, -3.3117e-01,
          1.5796e-01,  4.6115e-01,  7.2646e-01, -7.9395e-02, -1.3412e-01,
          2.1268e-01,  4.3222e-01,  1.1297e-01,  8.8936e-01,  2.5681e-02,
         -4.1500e-01, -4.1466e-01],
        [ 5.9264e-01,  5.9263e-01,  7.0150e-02,  4.5700e-03, -2.1838e-01,
         -6.4014e-02,  1.5466e+00, -4.8079e-01,  1.4800e+00,  7.7018e-01,
         -1.7518e+00,  1.0539e+00,  2.5291e-01,  6.6189e-02, -5.1168e-01,
         -5.9787e-01, -4.1571e-01,  3.2595e+00,  4.4002e-01,  3.4518e-01,
         -1.5924e-01, -4.9058e-01, -7.5438e-01,  7.6813e-02,  4.0976e-01,
         -2.6690e-01, -1.7090e-01, -6.3057e-02, -8.6740e-01,  1.5902e-01,
          5.9144e-01,  5.8989e-01],
        [ 5.6227e-01,  5.6223e-01,  2.4868e-02,  7.3204e-03, -2.3753e-01,
         -5.9158e-02,  1.5194e+00, -4.9125e-01,  1.4895e+00,  7.9595e-01,
         -1.7256e+00,  1.0602e+00,  2.4072e-01,  9.6817e-02, -5.4576e-01,
         -5.9580e-01, -4.2037e-01,  3.2384e+00,  4.2476e-01,  3.2115e-01,
         -1.9103e-01, -4.9520e-01, -7.5379e-01,  6.9878e-02,  3.5553e-01,
         -2.6479e-01, -2.0132e-01, -6.7280e-02, -8.6095e-01,  1.2629e-01,
          5.6102e-01,  5.5962e-01],
        [ 6.1508e-01,  6.1509e-01,  8.4066e-02,  5.1117e-04, -2.2185e-01,
         -8.5800e-02,  1.5742e+00, -4.7632e-01,  1.4695e+00,  7.2430e-01,
         -1.7331e+00,  1.0073e+00,  2.2094e-01,  1.8581e-02, -5.6978e-01,
         -6.0793e-01, -4.2765e-01,  3.1729e+00,  4.5252e-01,  2.8511e-01,
         -2.4812e-01, -5.2527e-01, -7.8097e-01,  4.0089e-02,  4.5197e-01,
         -2.8952e-01, -1.2800e-01, -6.7924e-02, -8.7132e-01,  1.4994e-01,
          6.1401e-01,  6.1215e-01],
        [ 5.9182e-01,  5.9164e-01,  3.5366e-02,  6.5002e-03, -2.3231e-01,
         -6.0204e-02,  1.5472e+00, -4.8285e-01,  1.4945e+00,  7.6357e-01,
         -1.7241e+00,  1.0423e+00,  2.3754e-01,  7.1579e-02, -5.6895e-01,
         -6.2016e-01, -4.3250e-01,  3.2076e+00,  4.4564e-01,  2.9181e-01,
         -2.2779e-01, -5.0467e-01, -7.6186e-01,  5.5058e-02,  4.0693e-01,
         -2.7546e-01, -1.6160e-01, -6.6437e-02, -8.6698e-01,  1.2991e-01,
          5.9058e-01,  5.8893e-01],
        [ 5.5621e-01,  5.5625e-01,  2.1391e-02, -2.4643e-03, -2.4697e-01,
         -6.9637e-02,  1.5216e+00, -4.9243e-01,  1.4708e+00,  7.5922e-01,
         -1.7400e+00,  1.0274e+00,  2.3094e-01,  6.0852e-02, -5.5888e-01,
         -5.8097e-01, -4.0549e-01,  3.2456e+00,  4.2341e-01,  3.0377e-01,
         -2.1883e-01, -5.2514e-01, -7.6497e-01,  7.1106e-02,  3.6486e-01,
         -2.7406e-01, -1.9598e-01, -8.9970e-02, -8.6228e-01,  1.0352e-01,
          5.5516e-01,  5.5336e-01]])

In [20]:
type(model)

peft.peft_model.PeftModelForCausalLM

In [22]:
names = list(pg_dict.keys())

In [36]:
# name = 'PAI1_HUMAN'
name = 'S22A1_HUMAN'
pg_dict[name]
# pg_dict['S22A1_HUMAN']

{'sequence': 'PTVDDILEQVGESGWFQKQAFLILCLLSAAFAPICVGIVFLGFTPDHHCQSPGVAELSQRCGWSPAEELNYTVPGLGPAGEAFLGQCRRYEVDWNQSALSCVDPLASLATNRSHLPLGPCQDGWVYDTPGSSIVTEFNLVCADSWKLDLFQSCLNAGFLFGSLGVGYFADRFGRKLCLLGTVLVNAVSGVLMAFSPNYMSMLLFRLLQGLVSKGNWMAGYTLITEFVGSGSRRTVAIMYQMAFTVGLVALTGLAYALPHWRWLQLAVSLPTFLFLLYYWCVPESPRWLLSQKRNTEAIKIMDHIAQKNGKLPPADLKMLSLEEDVTEKLSPSFADLFRTPRLRKRTFILMYLWFTDSVLYQGLILHMGATSGNLYLDFLYSALVEIPGAFIALITIDRVGRIYPMAMSNLLAGAACLVMIFISPDLHWLNIIIMCVGRMGITIAIQMICLVNAELYPTFVRNLGVMVCSSLCDIGGIITPFIVFRLREVWQALPLILFAVLGLLAAGVTLLLPETKGVALPETMKDAENLGRKAKPKENTIYLKVQTSEPSGT',
 'DMS': array([[ 0.29803039,         nan, -0.02282262, ...,         nan,
                 nan, -0.40331238],
        [-0.0186989 , -0.9664416 ,  0.0705317 , ..., -0.81024862,
         -1.36953997,         nan],
        [-1.3560825 , -0.87940227, -2.38607073, ...,         nan,
         -0.20007489,  0.23612909],
        ...,
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan]], shape=(553, 20)),
 'log_probs': array([[-2.115878 , -4.763095 , -5.8257475, ..., -3.1382017, -5.240115 ,
         -4.972911 ],
        [-2.4704216, -4.5449915, -3.9992301, ..., -4.363641 , -7.107171 ,
         -5.6235895],
        [-2.8370202, -4.774276 , -4.7136984, ..., -2.3746636, -5.4226904,
         -4.024169 ],
        ...,
        [-2.682618 , -3.988488 , -2.876664 , ..., -2.9054878, -4.7014704,
         -3.9416206],
        [-2.6449132, -4.083321 , -2.870255 , ..., -2.851441 , -4.7234197,
         -3.9793477],
        [-2.6710882, -4.125266 , -2.6983404, ..., -2.9770117, -4.709655 ,
         -3.891654 ]], shape=(553, 20), dtype=float32),
 'ref_log_probs': array([[-1.72781658e+00],
        [-1.14319682e+00],
        [-2.37466359e+00],
        [-9.14941013e-01],
        [-7.86413372e-01],
        [-1.23373675e+00],
        [-3.60046029e-01],
        [-1.75209951e+00],
        [-2.74027157e+00],
        [-8.81756127e-01],
        [-1.35926771e+00],
        [-2.59460521e+00],
        [-3.87218761e+00],
        [-6.72169030e-01],
        [-4.14110661e+00],
        [-1.41866767e+00],
        [-1.85550824e-01],
        [-4.59984362e-01],
        [-1.51691484e+00],
        [-2.32663679e+00],
        [-8.47038448e-01],
        [-1.18899548e+00],
        [-2.38541222e+00],
        [-4.73899633e-01],
        [-1.22726560e+00],
        [-9.06077147e-01],
        [-9.97479737e-01],
        [-1.04159546e+00],
        [-1.90459466e+00],
        [-1.48792577e+00],
        [-8.88456345e-01],
        [-1.07316446e+00],
        [-2.29058290e+00],
        [-9.12965834e-01],
        [-3.41148400e+00],
        [-6.11232758e-01],
        [-1.79863468e-01],
        [-2.81073987e-01],
        [-1.79362327e-01],
        [-5.61959520e-02],
        [-7.77965128e-01],
        [-1.80166751e-01],
        [-4.72164527e-02],
        [-5.98195255e-01],
        [-1.08948154e-02],
        [-4.47941840e-01],
        [-2.17481807e-01],
        [-2.49755621e+00],
        [-1.32532476e-03],
        [-3.00135756e+00],
        [-1.93519369e-01],
        [-5.43392710e-02],
        [-7.10841566e-02],
        [-1.58153370e-01],
        [-1.43353209e-01],
        [-9.79542360e-02],
        [-3.59914303e-02],
        [-6.45487607e-01],
        [-6.08196437e-01],
        [-4.07048374e-01],
        [-1.95014931e-03],
        [-1.58540025e-01],
        [-3.95080000e-02],
        [-2.00600356e-01],
        [-1.55995417e+00],
        [-5.20338953e-01],
        [-1.22622646e-01],
        [-3.70510072e-02],
        [-2.41462186e-01],
        [-1.42425865e-01],
        [-1.54222265e-01],
        [-4.36250307e-02],
        [-5.82683563e-01],
        [-1.63641777e-02],
        [-1.37672856e-01],
        [-1.87113440e+00],
        [-2.86052674e-01],
        [-1.56522799e+00],
        [-2.71774220e+00],
        [-7.80610323e-01],
        [-1.63774240e+00],
        [-1.49482453e+00],
        [-2.27053952e+00],
        [-2.19084144e+00],
        [-3.02490306e+00],
        [-9.22482252e-01],
        [-9.02300980e-03],
        [-4.93268847e-01],
        [-2.85530895e-01],
        [-7.58382306e-02],
        [-2.87854105e-01],
        [-6.84767812e-02],
        [-3.04258484e-02],
        [-2.15250882e-03],
        [-2.57199369e-02],
        [-2.34984589e+00],
        [-2.44243339e-01],
        [-1.92455006e+00],
        [-1.78056240e-01],
        [-7.35776007e-01],
        [-1.80272595e-03],
        [-3.39338511e-01],
        [-2.15374678e-02],
        [-1.53670833e-02],
        [-1.88266039e-02],
        [-1.57017565e+00],
        [-1.17832029e+00],
        [-1.19538615e-02],
        [-3.07275623e-01],
        [-3.13609481e+00],
        [-1.89757496e-02],
        [-1.64090544e-01],
        [-3.24050933e-02],
        [-1.35463488e+00],
        [-5.29674947e-01],
        [-1.66851774e-01],
        [-3.51403147e-01],
        [-1.45264816e+00],
        [-4.19174910e-01],
        [-7.12082582e-03],
        [-4.86048043e-01],
        [-2.28201962e+00],
        [-8.73506442e-03],
        [-9.78825148e-04],
        [-2.74759948e-01],
        [-7.20930174e-02],
        [-8.22530836e-02],
        [-5.55450737e-01],
        [-1.42328262e-01],
        [-1.59383133e-01],
        [-3.38018119e-01],
        [-6.05819859e-02],
        [-5.38437188e-01],
        [-9.09855962e-02],
        [-4.27225009e-02],
        [-3.26971523e-02],
        [-7.01577440e-02],
        [-2.09519476e-01],
        [-7.90290255e-03],
        [-2.19994877e-02],
        [-2.05294020e-03],
        [-1.45917213e+00],
        [-2.09949687e-01],
        [-2.76364207e-01],
        [-4.76036081e-03],
        [-2.64981706e-02],
        [-2.51189411e-01],
        [-3.37413214e-02],
        [-2.02161178e-01],
        [-1.43573597e-01],
        [-1.37221338e-02],
        [-8.84605497e-02],
        [-2.54047722e-01],
        [-2.75160718e+00],
        [-1.43284619e-01],
        [-3.02599144e+00],
        [-6.53961115e-03],
        [-1.39604490e-02],
        [-4.40237236e+00],
        [-3.76045012e+00],
        [-1.91896614e-02],
        [-3.20322573e-01],
        [-6.86887145e-01],
        [-1.31005824e+00],
        [-8.26328397e-01],
        [-3.43780196e-03],
        [-2.52410591e-01],
        [-4.84495354e+00],
        [-5.80506548e-02],
        [-4.79120761e-03],
        [-7.28979558e-02],
        [-2.48632833e-01],
        [-1.79641915e-03],
        [-2.28382437e-03],
        [-2.33809009e-01],
        [-6.13533556e-01],
        [-4.18603331e-01],
        [-2.83010781e-01],
        [-3.28303933e-01],
        [-2.92037773e+00],
        [-3.59415442e-01],
        [-1.28581071e+00],
        [-6.81580663e-01],
        [-1.22671580e+00],
        [-4.85147715e-01],
        [-6.60079837e-01],
        [-9.12603140e-01],
        [-1.19835424e+00],
        [-3.16821486e-02],
        [-6.82485104e-01],
        [-3.00072104e-01],
        [-2.29688692e+00],
        [-1.04658760e-01],
        [-5.74441910e-01],
        [-1.44943023e+00],
        [-9.82248783e-03],
        [-6.72314763e-01],
        [-6.58394918e-02],
        [-5.02329016e+00],
        [-1.17187643e+00],
        [-1.78818178e+00],
        [-8.84183943e-01],
        [-1.10276902e+00],
        [-3.03445011e-01],
        [-1.35566788e-02],
        [-1.03099859e+00],
        [-1.24041870e-01],
        [-7.59167671e-01],
        [-1.27353473e-02],
        [-1.10517800e+00],
        [-3.48187178e-01],
        [-4.18090791e-01],
        [-1.56365763e-02],
        [-8.90650898e-02],
        [-3.20005083e+00],
        [-9.29621682e-02],
        [-1.02026820e+00],
        [-1.28810680e+00],
        [-7.39502013e-01],
        [-1.45911381e-01],
        [-3.05659509e+00],
        [-1.20647371e-01],
        [-9.85818267e-01],
        [-3.51817787e-01],
        [-1.99880986e-03],
        [-3.41810346e-01],
        [-1.34517595e-01],
        [-1.50433825e-02],
        [-1.62808955e+00],
        [-2.41740656e+00],
        [-4.58399916e+00],
        [-2.94299498e-02],
        [-2.14882325e-02],
        [-1.16195820e-01],
        [-1.18759863e-01],
        [-9.44550991e-01],
        [-1.51417911e-01],
        [-2.68420815e+00],
        [-1.84887856e-01],
        [-5.70370927e-02],
        [-2.25181484e+00],
        [-5.65240562e-01],
        [-1.14587046e-01],
        [-2.08618924e-01],
        [-7.84099579e-01],
        [-1.19189946e-02],
        [-2.66927034e-01],
        [-2.07343102e+00],
        [-1.98585308e+00],
        [-3.77172790e-02],
        [-2.45444202e+00],
        [-1.40656009e-01],
        [-2.19626117e+00],
        [-2.56779939e-02],
        [-6.03911132e-02],
        [-9.21594322e-01],
        [-1.72328889e+00],
        [-3.73445824e-02],
        [-3.31792116e-01],
        [-2.93313037e-03],
        [-6.09225743e-02],
        [-3.57185185e-01],
        [-5.07087968e-02],
        [-4.62086909e-02],
        [-7.53570944e-02],
        [-5.73015690e-01],
        [-2.52907634e-01],
        [-8.05399299e-01],
        [-2.49099240e-01],
        [-9.42814257e-03],
        [-2.12023306e+00],
        [-1.96923107e-01],
        [-4.90100771e-01],
        [-1.17045365e-01],
        [-1.74584270e-01],
        [-1.38050482e-01],
        [-2.50322483e-02],
        [-1.67808354e-01],
        [-3.10163479e-02],
        [-1.00693023e+00],
        [-8.92760992e-01],
        [-4.98982631e-02],
        [-4.12506238e-03],
        [-7.55441561e-03],
        [-1.73261702e-01],
        [-6.01564767e-03],
        [-1.63980911e-03],
        [-6.38693990e-03],
        [-8.92816484e-01],
        [-4.06121403e-01],
        [-7.73155540e-02],
        [-9.40502763e-01],
        [-3.19711864e-01],
        [-1.09358335e+00],
        [-3.10742378e+00],
        [-1.13383830e+00],
        [-2.50435267e-02],
        [-1.63011360e+00],
        [-1.04438221e+00],
        [-2.80227810e-01],
        [-7.51046777e-01],
        [-3.00690317e+00],
        [-2.25887489e+00],
        [-3.01247478e-01],
        [-5.51793762e-02],
        [-2.10354304e+00],
        [-3.53657097e-01],
        [-8.23022239e-03],
        [-4.63971823e-01],
        [-2.66800135e-01],
        [-1.93447709e+00],
        [-9.90572512e-01],
        [-4.58232522e-01],
        [-1.96530449e+00],
        [-2.68838501e+00],
        [-3.43669236e-01],
        [-2.15442181e+00],
        [-4.39294386e+00],
        [-1.16745377e+00],
        [-2.91085148e+00],
        [-3.03511906e+00],
        [-7.61596024e-01],
        [-9.82071161e-01],
        [-2.33550835e+00],
        [-2.39932632e+00],
        [-1.95934224e+00],
        [-1.02390730e+00],
        [-1.20316100e+00],
        [-2.38648725e+00],
        [-1.87197590e+00],
        [-2.01838923e+00],
        [-5.68954945e-01],
        [-7.26372004e-01],
        [-4.66739893e+00],
        [-7.27108568e-02],
        [-4.64892313e-02],
        [-6.54445171e-01],
        [-2.63720006e-01],
        [-1.71957970e-01],
        [-7.52143562e-02],
        [-2.77090335e+00],
        [-1.40931439e+00],
        [-1.94059834e-02],
        [-2.31939688e-01],
        [-4.00616884e+00],
        [-7.65900314e-02],
        [-1.69255733e+00],
        [-1.34408697e-01],
        [-1.65960625e-01],
        [-2.27335870e-01],
        [-2.39936903e-01],
        [-6.33626342e-01],
        [-5.95430210e-02],
        [-6.72351345e-02],
        [-5.07033348e-01],
        [-6.82702065e+00],
        [-7.91497171e-01],
        [-2.92182982e-01],
        [-5.71002483e-01],
        [-2.42634602e-02],
        [-1.62037045e-01],
        [-1.11363996e-02],
        [-2.80698650e-02],
        [-5.71089447e-01],
        [-9.19263422e-01],
        [-2.34919250e-01],
        [-2.59384251e+00],
        [-5.10475487e-02],
        [-1.81730258e+00],
        [-2.01038933e+00],
        [-1.28223825e+00],
        [-2.37136781e-01],
        [-1.47079930e-01],
        [-9.44437385e-01],
        [-7.81768262e-02],
        [-2.29038924e-01],
        [-8.08454156e-01],
        [-1.54631045e-02],
        [-1.59248805e+00],
        [-2.74613410e-01],
        [-1.52773753e-01],
        [-4.41573083e-01],
        [-5.57722569e-01],
        [-1.26614153e-01],
        [-1.66284796e-02],
        [-3.76581860e+00],
        [-1.52832614e-02],
        [-2.86940384e+00],
        [-1.68972635e+00],
        [-8.60249937e-01],
        [-1.01458073e+00],
        [-5.84350967e+00],
        [-2.72085547e+00],
        [-2.60085750e+00],
        [-7.42332101e-01],
        [-2.24490374e-01],
        [-1.83005124e-01],
        [-1.82977229e-01],
        [-1.37888896e+00],
        [-3.81878354e-02],
        [-8.59903917e-03],
        [-2.87884712e+00],
        [-1.05948305e+00],
        [-1.16811939e-01],
        [-9.34351563e-01],
        [-1.77143574e-01],
        [-3.79543209e+00],
        [-6.09356463e-01],
        [-2.39830554e-01],
        [-1.12538469e+00],
        [-1.16531467e+00],
        [-2.98468858e-01],
        [-3.37179229e-02],
        [-7.93525755e-01],
        [-3.42044860e-01],
        [-1.50348589e-01],
        [-6.34430587e-01],
        [-1.49904120e+00],
        [-3.65561581e+00],
        [-1.96478260e+00],
        [-4.77138132e-01],
        [-8.98637593e-01],
        [-2.71085238e+00],
        [-3.03164053e+00],
        [-1.18974292e+00],
        [-6.08433604e-01],
        [-1.84058559e+00],
        [-1.48496121e-01],
        [-4.25214410e-01],
        [-3.19118190e+00],
        [-1.22829425e+00],
        [-2.27678251e+00],
        [-2.15313458e+00],
        [-5.49800968e+00],
        [-2.36763924e-01],
        [-1.31675279e+00],
        [-2.30306253e-01],
        [-1.40499085e-01],
        [-6.73886836e-01],
        [-9.45946872e-02],
        [-1.99476048e-01],
        [-1.64457723e-01],
        [-6.38240635e-01],
        [-1.27881074e+00],
        [-4.89672422e+00],
        [-1.06582034e+00],
        [-2.30855659e-01],
        [-2.10580111e+00],
        [-1.47105351e-01],
        [-1.59781098e-01],
        [-1.30117670e-01],
        [-3.69959325e-01],
        [-5.92956424e-01],
        [-3.29024112e-03],
        [-4.82763648e-02],
        [-1.53370304e-02],
        [-1.27317884e-03],
        [-2.69871065e-03],
        [-1.31732076e-01],
        [-1.13671327e+00],
        [-3.73511459e-03],
        [-6.75565302e-02],
        [-3.55887353e-01],
        [-5.21825030e-02],
        [-1.30801931e-01],
        [-6.76961422e-01],
        [-5.87077618e-01],
        [-5.81801198e-02],
        [-5.33349328e-02],
        [-2.95922041e-01],
        [-4.64992672e-01],
        [-1.28328592e-01],
        [-2.73080487e-02],
        [-1.33900476e+00],
        [-2.03024615e-02],
        [-2.62411356e-01],
        [-3.21539491e-01],
        [-6.03119433e-01],
        [-5.39292097e-01],
        [-4.10309900e-03],
        [-9.86193866e-02],
        [-2.19531202e+00],
        [-3.63448352e-01],
        [-2.02412653e+00],
        [-1.27281022e+00],
        [-4.83090803e-02],
        [-5.18215847e+00],
        [-5.11242151e-01],
        [-6.41638517e-01],
        [-6.21775687e-02],
        [-1.52567053e+00],
        [-3.69031906e+00],
        [-2.83868074e-01],
        [-8.77914205e-03],
        [-2.09292457e-01],
        [-8.55214715e-01],
        [-1.12052381e+00],
        [-1.08870126e-01],
        [-9.99202609e-01],
        [-1.30704153e+00],
        [-6.06591284e-01],
        [-6.11642540e-01],
        [-9.49746251e-01],
        [-1.34333754e+00],
        [-3.88252288e-01],
        [-4.07910872e+00],
        [-7.01148689e-01],
        [-4.05884361e+00],
        [-2.15861821e+00],
        [-1.66030601e-01],
        [-9.60894153e-02],
        [-4.10786159e-02],
        [-5.38920937e-03],
        [-5.07981610e-03],
        [-3.34887691e-02],
        [-7.10736573e-01],
        [-9.06981006e-02],
        [-1.21601069e+00],
        [-1.80773318e+00],
        [-1.70498807e-02],
        [-8.20255578e-02],
        [-8.01930189e-01],
        [-4.16607201e-01],
        [-3.16794181e+00],
        [-2.78983593e+00],
        [-6.80019677e-01],
        [-1.77875280e+00],
        [-4.30940688e-01],
        [-1.76019728e+00],
        [-1.08240068e+00],
        [-1.72169971e+00],
        [-1.26082313e+00],
        [-1.74875224e+00],
        [-2.78970289e+00],
        [-1.52062666e+00],
        [-2.98602128e+00],
        [-1.90179896e+00],
        [-2.59652328e+00],
        [-2.92438531e+00],
        [-2.69482446e+00],
        [-3.31970501e+00],
        [-4.04582310e+00],
        [-2.25604463e+00],
        [-2.50586891e+00],
        [-3.09048462e+00],
        [-2.91214418e+00],
        [-2.53904080e+00],
        [-2.30098057e+00],
        [-2.43998551e+00],
        [-2.68348002e+00],
        [-2.27813792e+00],
        [-2.94143724e+00],
        [-2.78978634e+00]], dtype=float32),
 'llr_matrix': array([[-0.38806152, -3.0352783 , -4.097931  , ..., -1.4103851 ,
         -3.5122986 , -3.2450943 ],
        [-1.3272247 , -3.4017947 , -2.8560333 , ..., -3.220444  ,
         -5.963974  , -4.4803925 ],
        [-0.46235657, -2.3996122 , -2.3390348 , ...,  0.        ,
         -3.0480268 , -1.6495054 ],
        ...,
        [-0.40447998, -1.71035   , -0.598526  , ..., -0.62734985,
         -2.4233325 , -1.6634827 ],
        [ 0.29652405, -1.1418839 ,  0.07118225, ...,  0.08999634,
         -1.7819824 , -1.0379105 ],
        [ 0.11869812, -1.3354797 ,  0.09144592, ..., -0.18722534,
         -1.9198685 , -1.1018677 ]], shape=(553, 20), dtype=float32),
 'spearman_DMS': (np.float64(0.5818748160195195), np.float64(0.0)),
 'log_probs_forward': array([[-4.5067906, -5.769936 , -5.2112813, ..., -4.834809 , -6.299134 ,
         -5.9919972],
        [-2.3560817, -4.1094465, -3.1026561, ..., -2.813403 , -4.4420805,
         -3.9904354],
        [-2.2569847, -4.1859474, -3.0158577, ..., -3.0405617, -4.3585167,
         -3.7553825],
        ...,
        [-2.799604 , -3.7940116, -2.7839103, ..., -2.9978461, -5.1119742,
         -4.492147 ],
        [-2.768358 , -3.9416902, -2.794771 , ..., -2.9518754, -5.0430927,
         -4.269022 ],
        [-2.7288647, -4.2998104, -2.4301891, ..., -3.212675 , -5.2676525,
         -4.1341686]], shape=(553, 20), dtype=float32),
 'ref_log_probs_forward': array([[-4.78476763e+00],
        [-2.76164508e+00],
        [-3.04056168e+00],
        [-3.16797042e+00],
        [-2.88297534e+00],
        [-2.90662169e+00],
        [-2.25525165e+00],
        [-2.88630438e+00],
        [-3.00014329e+00],
        [-2.05542040e+00],
        [-3.36374784e+00],
        [-2.79277444e+00],
        [-2.91532540e+00],
        [-2.66719174e+00],
        [-4.37888813e+00],
        [-3.27034855e+00],
        [-1.93387330e+00],
        [-3.18841600e+00],
        [-3.16064835e+00],
        [-2.95876408e+00],
        [-2.40181160e+00],
        [-1.90332592e+00],
        [-3.08570552e+00],
        [-1.60369313e+00],
        [-3.25589371e+00],
        [-1.71712029e+00],
        [-1.67839694e+00],
        [-1.61593950e+00],
        [-1.77958679e+00],
        [-1.55407870e+00],
        [-1.59290588e+00],
        [-1.21083128e+00],
        [-3.17476153e+00],
        [-5.64297855e-01],
        [-2.62812376e+00],
        [-2.51403379e+00],
        [-1.24714136e+00],
        [-1.19404697e+00],
        [-1.00103605e+00],
        [-2.23158434e-01],
        [-2.04768801e+00],
        [-1.01921968e-01],
        [-3.59537929e-01],
        [-1.45594442e+00],
        [-1.33158669e-01],
        [-4.34275478e-01],
        [-5.99854946e-01],
        [-2.57974768e+00],
        [-1.53828505e-03],
        [-3.91936445e+00],
        [-1.31772387e+00],
        [-1.99726388e-01],
        [-1.58469319e-01],
        [-1.35664552e-01],
        [-3.27179909e-01],
        [-6.06114447e-01],
        [-1.10215575e-01],
        [-8.54414403e-01],
        [-5.51800013e-01],
        [-3.48695010e-01],
        [-2.54502408e-02],
        [-2.03261271e-01],
        [-7.61226192e-02],
        [-4.71807897e-01],
        [-2.21424961e+00],

In [37]:
sequence = pg_dict[name]['sequence']

In [47]:
model.eval()

amino_acids = 'ACDEFGHIKLMNPQRSTVWY'
aa_token_ids = [tokenizer.convert_tokens_to_ids(aa) for aa in amino_acids]

input = tokenizer(sequence, return_tensors="pt").to(device)
outputs = model(**inputs)

prompt1 = "1"+sequence  # run it forwards
prompt2 = "2"+sequence[::-1]  # run it backwards

input_ids1 = torch.tensor(tokenizer.encode(prompt1)).unsqueeze(0).to(model.device)
with torch.no_grad():
    logits1 = model(input_ids1).logits
shift_logits1 = logits1[:, :-1, :]  # remove last entry

input_ids2 =  torch.tensor(tokenizer.encode(prompt2)).unsqueeze(0).to(model.device)
with torch.no_grad():
    logits2 = model(input_ids2).logits
shift_logits2 = logits2[:, :-1, :] # remove last entry

shift_logits2 = shift_logits2[:, torch.arange(shift_logits2.size(1) - 1, -1, -1), :]

input_ids = input_ids1[:, 1:]

# take averages of matrices, 2nd one in reverse order
# to simulate BERT output

logits = (shift_logits1 + shift_logits2)/2

log_probs = F.log_softmax(logits, dim = -1)
# n = log_probs.size(1)

ref_log_probs = log_probs[0, torch.arange(input_ids.size(1)), input_ids[0]]
ref_log_probs = ref_log_probs.unsqueeze(1)


llr_matrix = log_probs - ref_log_probs
llr_matrix = llr_matrix[0][:, aa_token_ids]
log_probs = log_probs[0][:, aa_token_ids]

In [48]:
log_probs

tensor([[-2.1215, -4.7629, -5.8157,  ..., -3.1387, -5.2349, -4.9685],
        [-2.4693, -4.5426, -3.9928,  ..., -4.3566, -7.0935, -5.6114],
        [-2.8378, -4.7669, -4.7057,  ..., -2.3763, -5.4062, -4.0159],
        ...,
        [-2.6842, -3.9872, -2.8762,  ..., -2.9067, -4.6968, -3.9412],
        [-2.6455, -4.0825, -2.8709,  ..., -2.8516, -4.7201, -3.9773],
        [-2.6717, -4.1247, -2.6987,  ..., -2.9773, -4.7063, -3.8908]])

In [39]:
pg_dict[name]['log_probs']

array([[-2.115878 , -4.763095 , -5.8257475, ..., -3.1382017, -5.240115 ,
        -4.972911 ],
       [-2.4704216, -4.5449915, -3.9992301, ..., -4.363641 , -7.107171 ,
        -5.6235895],
       [-2.8370202, -4.774276 , -4.7136984, ..., -2.3746636, -5.4226904,
        -4.024169 ],
       ...,
       [-2.682618 , -3.988488 , -2.876664 , ..., -2.9054878, -4.7014704,
        -3.9416206],
       [-2.6449132, -4.083321 , -2.870255 , ..., -2.851441 , -4.7234197,
        -3.9793477],
       [-2.6710882, -4.125266 , -2.6983404, ..., -2.9770117, -4.709655 ,
        -3.891654 ]], shape=(553, 20), dtype=float32)

In [54]:
for name, param in model.named_parameters():
    if 'lora' in name or 'adapter' in name:
        print(name, param.abs().max())

base_model.model.transformer.h.0.attn.qkv_proj.lora_A.default.weight tensor(0.4325, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.0.attn.qkv_proj.lora_B.default.weight tensor(0.4395, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.0.attn.out_proj.lora_A.default.weight tensor(0.4429, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.0.attn.out_proj.lora_B.default.weight tensor(0.4115, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.1.attn.qkv_proj.lora_A.default.weight tensor(0.3172, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.1.attn.qkv_proj.lora_B.default.weight tensor(0.3424, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.1.attn.out_proj.lora_A.default.weight tensor(0.3184, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.1.attn.out_proj.lora_B.default.weight tensor(0.3570, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.2.attn.qkv_proj.lora_A.default.weight tensor(0.3330, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.2.attn.qkv_proj.lora_B.default.weight tensor(0.3615, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.2.attn.out_proj.lora_A.default.weight tensor(0.3408, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.2.attn.out_proj.lora_B.default.weight tensor(0.3595, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.3.attn.qkv_proj.lora_A.default.weight tensor(0.3408, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.3.attn.qkv_proj.lora_B.default.weight tensor(0.3588, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.3.attn.out_proj.lora_A.default.weight tensor(0.3304, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.3.attn.out_proj.lora_B.default.weight tensor(0.4018, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.4.attn.qkv_proj.lora_A.default.weight tensor(0.3687, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.4.attn.qkv_proj.lora_B.default.weight tensor(0.4090, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.4.attn.out_proj.lora_A.default.weight tensor(0.3484, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.4.attn.out_proj.lora_B.default.weight tensor(0.3620, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.5.attn.qkv_proj.lora_A.default.weight tensor(0.3155, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.5.attn.qkv_proj.lora_B.default.weight tensor(0.3519, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.5.attn.out_proj.lora_A.default.weight tensor(0.3280, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.5.attn.out_proj.lora_B.default.weight tensor(0.3682, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.6.attn.qkv_proj.lora_A.default.weight tensor(0.4008, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.6.attn.qkv_proj.lora_B.default.weight tensor(0.3945, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.6.attn.out_proj.lora_A.default.weight tensor(0.3989, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.6.attn.out_proj.lora_B.default.weight tensor(0.5281, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.7.attn.qkv_proj.lora_A.default.weight tensor(0.3579, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.7.attn.qkv_proj.lora_B.default.weight tensor(0.3984, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.7.attn.out_proj.lora_A.default.weight tensor(0.3110, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.7.attn.out_proj.lora_B.default.weight tensor(0.3441, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.8.attn.qkv_proj.lora_A.default.weight tensor(0.3715, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.8.attn.qkv_proj.lora_B.default.weight tensor(0.4006, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.8.attn.out_proj.lora_A.default.weight tensor(0.2900, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.8.attn.out_proj.lora_B.default.weight tensor(0.4552, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.9.attn.qkv_proj.lora_A.default.weight tensor(0.3395, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.9.attn.qkv_proj.lora_B.default.weight tensor(0.4154, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.9.attn.out_proj.lora_A.default.weight tensor(0.3131, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.9.attn.out_proj.lora_B.default.weight tensor(0.3366, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.10.attn.qkv_proj.lora_A.default.weight tensor(0.3131, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.10.attn.qkv_proj.lora_B.default.weight tensor(0.3575, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.10.attn.out_proj.lora_A.default.weight tensor(0.3194, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.10.attn.out_proj.lora_B.default.weight tensor(0.4134, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.11.attn.qkv_proj.lora_A.default.weight tensor(0.3485, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.11.attn.qkv_proj.lora_B.default.weight tensor(0.3643, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.11.attn.out_proj.lora_A.default.weight tensor(0.2653, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.11.attn.out_proj.lora_B.default.weight tensor(0.3979, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.12.attn.qkv_proj.lora_A.default.weight tensor(0.4431, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.12.attn.qkv_proj.lora_B.default.weight tensor(0.4516, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.12.attn.out_proj.lora_A.default.weight tensor(0.5055, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.12.attn.out_proj.lora_B.default.weight tensor(0.4329, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.13.attn.qkv_proj.lora_A.default.weight tensor(0.3698, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.13.attn.qkv_proj.lora_B.default.weight tensor(0.3768, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.13.attn.out_proj.lora_A.default.weight tensor(0.4189, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.13.attn.out_proj.lora_B.default.weight tensor(0.4292, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.14.attn.qkv_proj.lora_A.default.weight tensor(0.3615, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.14.attn.qkv_proj.lora_B.default.weight tensor(0.4065, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.14.attn.out_proj.lora_A.default.weight tensor(0.3781, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.14.attn.out_proj.lora_B.default.weight tensor(0.4115, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.15.attn.qkv_proj.lora_A.default.weight tensor(0.3454, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.15.attn.qkv_proj.lora_B.default.weight tensor(0.3591, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.15.attn.out_proj.lora_A.default.weight tensor(0.3399, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.15.attn.out_proj.lora_B.default.weight tensor(0.4500, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.16.attn.qkv_proj.lora_A.default.weight tensor(0.3430, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.16.attn.qkv_proj.lora_B.default.weight tensor(0.3963, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.16.attn.out_proj.lora_A.default.weight tensor(0.2869, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.16.attn.out_proj.lora_B.default.weight tensor(0.4142, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.17.attn.qkv_proj.lora_A.default.weight tensor(0.3476, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.17.attn.qkv_proj.lora_B.default.weight tensor(0.3878, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.17.attn.out_proj.lora_A.default.weight tensor(0.3130, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.17.attn.out_proj.lora_B.default.weight tensor(0.3508, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.18.attn.qkv_proj.lora_A.default.weight tensor(0.3730, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.18.attn.qkv_proj.lora_B.default.weight tensor(0.3499, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.18.attn.out_proj.lora_A.default.weight tensor(0.3411, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.18.attn.out_proj.lora_B.default.weight tensor(0.4599, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.19.attn.qkv_proj.lora_A.default.weight tensor(0.4050, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.19.attn.qkv_proj.lora_B.default.weight tensor(0.3808, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.19.attn.out_proj.lora_A.default.weight tensor(0.3332, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.19.attn.out_proj.lora_B.default.weight tensor(0.3879, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.20.attn.qkv_proj.lora_A.default.weight tensor(0.3298, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.20.attn.qkv_proj.lora_B.default.weight tensor(0.3694, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.20.attn.out_proj.lora_A.default.weight tensor(0.4056, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.20.attn.out_proj.lora_B.default.weight tensor(0.3880, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.21.attn.qkv_proj.lora_A.default.weight tensor(0.4260, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.21.attn.qkv_proj.lora_B.default.weight tensor(0.3731, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.21.attn.out_proj.lora_A.default.weight tensor(0.3168, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.21.attn.out_proj.lora_B.default.weight tensor(0.4476, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.22.attn.qkv_proj.lora_A.default.weight tensor(0.3463, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.22.attn.qkv_proj.lora_B.default.weight tensor(0.3700, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.22.attn.out_proj.lora_A.default.weight tensor(0.3788, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.22.attn.out_proj.lora_B.default.weight tensor(0.4488, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.23.attn.qkv_proj.lora_A.default.weight tensor(0.3479, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.23.attn.qkv_proj.lora_B.default.weight tensor(0.3815, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.23.attn.out_proj.lora_A.default.weight tensor(0.3214, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.23.attn.out_proj.lora_B.default.weight tensor(0.3773, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.24.attn.qkv_proj.lora_A.default.weight tensor(0.3115, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.24.attn.qkv_proj.lora_B.default.weight tensor(0.3704, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.24.attn.out_proj.lora_A.default.weight tensor(0.2847, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.24.attn.out_proj.lora_B.default.weight tensor(0.3761, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.25.attn.qkv_proj.lora_A.default.weight tensor(0.3802, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.25.attn.qkv_proj.lora_B.default.weight tensor(0.3735, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.25.attn.out_proj.lora_A.default.weight tensor(0.2950, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.25.attn.out_proj.lora_B.default.weight tensor(0.3768, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.26.attn.qkv_proj.lora_A.default.weight tensor(0.4207, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.26.attn.qkv_proj.lora_B.default.weight tensor(0.4270, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.26.attn.out_proj.lora_A.default.weight tensor(0.2797, grad_fn=<MaxBackward1>)
base_model.model.transformer.h.26.attn.out_proj.lora_B.default.weight tensor(0.4273, grad_fn=<MaxBackward1>)

In [29]:
model.print_trainable_parameters()

trainable params: 1,990,656 || all params: 766,794,272 || trainable%: 0.2596