In [1]:
import os

from io import StringIO
from google.cloud import storage
from dotenv import load_dotenv

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import torch
import torch.nn.functional as F

from transformers import AutoModelForCausalLM
from transformers import AutoTokenizer, EsmForMaskedLM
from tokenizers import Tokenizer
from peft import get_peft_model, LoraConfig, TaskType

/opt/anaconda3/envs/MachLearn/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
from plm_compare_progen2 import *
from plm_compare_esm import *
from protein_data import *
from pro_gen2_lora import *

In [24]:
device = 'cpu'
print(f"Using {device} device")
model_name = "hugohrban/progen2-medium"
base_model, tokenizer = initialize_progen2_noeval(model_name)

Using cpu device

In [ ]:
# filename = '/Users/johnhutchens/Desktop/Practicum/Data/Domainome/dict_domainome_uniprot.pkl'
# with open(filename, "rb") as f:
#     dict_uniprot = pickle.load(f)

In [18]:
filename = '/Users/johnhutchens/Desktop/Practicum/Data/Domainome/dict_domainome_uniprot_new.pkl'
with open(filename, "rb") as f:
    dict_uniprot = pickle.load(f)

In [9]:
load_dotenv()
cred_path = os.getenv('GOOGLE_APPLICATION_CREDENTIALS')

os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = cred_path

client = storage.Client()
bucket = client.bucket('domainome-data')
blob = bucket.blob('SupplementaryTable2.txt')

df = pd.read_csv(StringIO(blob.download_as_text()), sep='\t')

In [5]:
len(dict_uniprot.keys())

428

In [17]:
def make_mutation_fitness_df(domain_id, df):

    domain_id_list=domain_id.split("_")
    dom_pos = float(domain_id_list[-1])

    df_one_protein = df.where(df['domain_ID'] == domain_id).dropna()

    dom_position = df_one_protein['position'] - dom_pos
    df_one_protein.insert(loc=0, column='real_position', value=dom_position)
    df_one_protein_ns = df_one_protein[df_one_protein['mut_aa'] != '*'].copy()

    df_one_protein_ns['wt_seq'] = df_one_protein_ns.apply(lambda row: 
                                                      insert_wt(row['aa_seq'], row['real_position'], row['wt_aa']),
                                                      axis=1)
    
    df_mutation = df_one_protein_ns[['wt_seq','real_position','mut_aa','normalized_fitness']]

    return df_mutation

In [16]:
df.head()

,domain_ID,uniprot_ID,aa_seq,wt_aa,position,mut_aa,STOP,input_count_rep1,input_count_rep2,input_count_rep3,output_count_rep1,output_count_rep2,output_count_rep3,mean_input_count,fitness,fitness_sigma,normalized_fitness,normalized_fitness_sigma,quality_rank
0,A0A2R8Y422_PF00240_2,A0A2R8Y422,*IFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2.0,*,True,118.0,113.0,62.0,10.0,29.0,2.0,97.66667,0.030945,0.014885,-0.819050,0.208478,339
1,A0A2R8Y422_PF00240_2,A0A2R8Y422,AIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2.0,A,False,219.0,277.0,217.0,86.0,225.0,137.0,237.66670,0.069376,0.006673,-0.280790,0.093461,339
2,A0A2R8Y422_PF00240_2,A0A2R8Y422,CIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2.0,C,False,706.0,726.0,459.0,768.0,507.0,616.0,630.33330,0.082052,0.004141,-0.103250,0.057995,339
3,A0A2R8Y422_PF00240_2,A0A2R8Y422,DIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2.0,D,False,407.0,431.0,323.0,508.0,159.0,111.0,387.00000,0.071003,0.005162,-0.258003,0.072296,339
4,A0A2R8Y422_PF00240_2,A0A2R8Y422,EIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2.0,E,False,37.0,56.0,37.0,201.0,102.0,95.0,43.33333,0.116326,0.012085,0.376783,0.169263,339

In [19]:
dom_id = 'A0A2R8Y422_PF00240_2'

df_mutation = make_mutation_fitness_df(dom_id, df)

In [21]:
df_mutation.head()

,wt_seq,real_position,mut_aa,normalized_fitness
0,QIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,0.0,A,-0.280790
1,QIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,0.0,C,-0.103250
2,QIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,0.0,D,-0.258003
3,QIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,0.0,E,0.376783
4,QIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,0.0,F,0.149047

In [23]:
protein_seq = df_mutation['wt_seq'].iloc[0]
protein_seq

'QIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAGKQLEDGRTLSDYNIQKESTLHLVL'

In [61]:
dict_dn_fitness = {}

In [62]:
domain_ids = list(df['domain_ID'].unique())    

for dom_id in domain_ids:

    dict_dn_fitness[dom_id] = {}

    df_mutation = make_mutation_fitness_df(dom_id, df)
    protein_seq = df_mutation['wt_seq'].iloc[0]

    fitness_data = df_mutation
    fitness_data.reset_index(drop=True, inplace=True)
    positions = np.arange(len(protein_seq))

    amino_acids = 'ACDEFGHIKLMNPQRSTVWY'
    aa_token_ids = [tokenizer.convert_tokens_to_ids(aa) for aa in amino_acids]
    positions_col = np.repeat(positions, len(amino_acids))
    amino_acids_col = np.tile(list(amino_acids), len(positions))
    df2 = pd.DataFrame({'real_position': positions_col, 'mut_aa': amino_acids_col})
    df_merged = df2.merge(
        fitness_data,
        on=['real_position', 'mut_aa'],
        how='left')
    fitness_list = df_merged['normalized_fitness'].tolist()

    dom_data = dom_id.split("_")

    dict_dn_fitness[dom_id]['dom_seq'] = protein_seq
    dict_dn_fitness[dom_id]['uniprot_id'] = dom_data[0]
    dict_dn_fitness[dom_id]['pfam'] = dom_data[1]
    dict_dn_fitness[dom_id]['domain_start'] = dom_data[2]
    dict_dn_fitness[dom_id]['fitness'] = fitness_list

save a dictionary as pickle

In [ ]:
# path = '/Users/johnhutchens/Desktop/Practicum/Data/Domainome/'
# with open(path+"dict_dn_fitness.pkl", "wb") as f:
#     pickle.dump(dict_dn_fitness, f)

In [65]:
keys = list(dict_dn_fitness.keys())
len(keys)

522

In [64]:
i = 1
key = keys[i]

print(key)

dict_dn_fitness[key]

A0PJY2_PF00096_289

{'dom_seq': 'VCKVCGKGFRQASTLCRHKIIH',
 'uniprot_id': 'A0PJY2',
 'pfam': 'PF00096',
 'domain_start': '289',
 'fitness': [-0.252455221983102,
  -0.801102574773856,
  0.213684880185916,
  -0.170356053945728,
  -0.314743717241087,
  -0.116247484145821,
  -0.202370375840998,
  0.215030502197182,
  -0.413446276091886,
  -0.28032860376098,
  0.179151315068184,
  0.0545966957823591,
  -0.779433995993926,
  -0.496912613469845,
  -0.422941571616979,
  -0.588839353594538,
  -0.250398805949204,
  nan,
  -0.730083706100204,
  -0.119415307689338,
  -1.08948148335698,
  nan,
  -0.104814316848709,
  -0.0806045952480325,
  -0.891953096427874,
  -0.901045798421561,
  -1.21533564949891,
  -1.06967763638766,
  -0.209464941891363,
  -0.465358096198127,
  -0.916563810678981,
  -0.571248990216425,
  -0.88377958502429,
  -0.491142916082251,
  -1.00329387443099,
  -0.975046321757678,
  -0.353037192888365,
  -0.728121934752032,
  -0.586921989217069,
  -0.993158876181781,
  -0.159890352852709,
  -0.193616804104569,
  -0.0619392671009813,
  0.217698321665289,
  -0.692475408048438,
  -0.186858551336509,
  -0.630001892771969,
  0.275591424561418,
  nan,
  -0.387712823275468,
  -0.0806970838595482,
  -0.046731251982655,
  -0.0476257949360209,
  0.224910883633109,
  -0.353572476240661,
  0.101874090084278,
  0.0505253340390069,
  -0.214734871310852,
  -0.152599271484846,
  0.351107280803269,
  -0.31787141030169,
  -0.370362310288449,
  0.330561902357006,
  0.360846380766668,
  -0.728839394724292,
  0.0527326105710485,
  -0.0112393841684786,
  0.0316847048560745,
  -0.562843726764949,
  -0.340312261506314,
  -0.696893800956692,
  0.397827962948417,
  -0.662748017171307,
  -0.045513474892242,
  -0.164619330725239,
  -0.329959140678729,
  -0.435790846885693,
  nan,
  -0.740516505513629,
  0.346198626525567,
  -0.791082832352935,
  nan,
  0.167352657499743,
  -0.222705846254889,
  -0.565403090266382,
  -1.06071067706273,
  -0.836212669203786,
  0.0642077641389632,
  -0.132564874580072,
  0.184776401224789,
  -0.796605460939154,
  nan,
  -1.09783299368973,
  nan,
  -0.806287384759799,
  -1.28658625877648,
  -0.944661171389796,
  -0.794082203383198,
  -0.815296483147332,
  -1.16503547385081,
  -0.483598349643289,
  -0.351559138422635,
  -0.0365459892671543,
  0.30702284646772,
  -0.42118198131554,
  nan,
  -0.467634107137174,
  -0.222028728482403,
  nan,
  -0.406507471967666,
  0.317632747998236,
  -0.162874535463997,
  -0.667614517587259,
  0.0851777372943853,
  -0.704290818493033,
  -0.352623328875186,
  -0.0938427216299579,
  -0.0424422494207378,
  -0.371266941756369,
  -0.493764819470336,
  -0.0508558340463943,
  -0.258024032816187,
  0.183676314586501,
  0.321110129250431,
  -0.28575355396313,
  0.0145987214144334,
  0.431463030074877,
  -0.403706155708644,
  nan,
  -0.080845648971714,
  -0.0477125125705463,
  0.243009125857812,
  0.0097967375433809,
  0.101485326122848,
  0.164932099860893,
  0.133649498397189,
  0.103618060109284,
  -0.0367231196199609,
  -0.359624062095235,
  -0.084905902685355,
  0.0796947833819139,
  -0.187796606050554,
  0.403841175403821,
  0.198355879367102,
  -0.0743060409640573,
  nan,
  -0.124259203225014,
  -0.512521802357069,
  -0.42240742540426,
  -0.247238754126381,
  0.0772280782626271,
  -0.30932333883893,
  -0.385926827114395,
  0.162797220619591,
  -0.219358621249864,
  -0.203276745749278,
  0.0714008434065563,
  -0.131306954448455,
  -0.16623355341672,
  -0.342068760660654,
  -0.226617436260996,
  0.132161874633344,
  0.438914917717325,
  0.550212874751322,
  nan,
  0.0609215242235898,
  -0.371614300247904,
  -0.113355503685166,
  -0.0155281103813381,
  -0.0117891523006442,
  -0.0974518154292687,
  -0.102685194816523,
  0.210635450238062,
  0.239668876375418,
  -0.618702943465664,
  -0.175085891775084,
  -0.0500886175812631,
  -0.144302254043072,
  -0.121932921462362,
  -0.341290072535945,
  0.296530233869662,
  0.155381737458783,
  0.540436954722663,
  0.746002902328433,
  0.100954126443273,
  0.26971040925996,
  0.0450432004147584,
  0.127009732122968,
  -0.0460819063979544,
  0.122107482495753,
  0.235615961215212,
  0.792761462933359,
  -0.130780515164658,
  0.419074073664505,
  nan,
  0.350003069557395,
  0.500222737885665,
  0.287064751398537,
  0.0213575370712116,
  -0.165988238125385,
  0.0553090297854945,
  0.167092561514496,
  0.486735078103258,
  0.210824143277522,
  -0.185186878899796,
  -0.157628762552928,
  -0.294408691411469,
  -0.318483305196108,
  -0.0402165013605813,
  -0.230133432565254,
  0.184790047093794,
  0.143681902332467,
  -0.233995904618012,
  nan,
  -0.32973613330861,
  0.0600146138584368,
  -0.0126732196315652,
  -0.109939349532992,
  -0.246116564929098,
  -0.279229387886797,
  nan,
  0.258701105588508,
  0.348121522430578,
  0.596261637277637,
  -0.0297366930962464,
  0.138844341172587,
  0.391381888419881,
  0.0086227672129284,
  0.20391734895891,
  -0.0760211131294713,
  nan,
  0.28447159073244,
  0.239055065933715,
  0.155723149202462,
  -0.390193538843889,
  -0.311372307738805,
  -0.102146717549658,
  0.0068413245851362,
  0.141401003916529,
  -0.287646132752472,
  0.113129202294851,
  -0.890065054640868,
  0.361113455747391,
  -0.136844158306875,
  -0.579121429392795,
  -0.505021688371676,
  nan,
  0.0462662374942879,
  -0.58693916589944,
  -0.621689626820098,
  -0.110031899868134,
  -0.181606185266157,
  -0.401135907895594,
  -0.80230516362035,
  -0.949416422350507,
  nan,
  -0.363335422603874,
  -0.146160493167554,
  -0.503730592153571,
  -0.529895861785002,
  -0.0258213399857654,
  -0.947747918414058,
  -0.713732889221526,
  0.0824401107932356,
  -0.798512775255767,
  -0.295796101117142,
  -1.00983839827697,
  -0.538634113619919,
  -0.821757238622893,
  -0.399305775075232,
  0.289014762631257,
  0.0435986595218983,
  -0.604540768849557,
  0.0580209621331278,
  -0.751665241235331,
  -0.415539817445442,
  nan,
  -0.55249944683065,
  -1.16672579670981,
  -1.25228589278014,
  0.0469173644956229,
  -0.160389853675398,
  0.507876409680143,
  0.293575605690135,
  -0.0348725458932667,
  -0.211356402858679,
  0.0199852012797892,
  -0.102794209324176,
  -0.103543798762104,
  nan,
  -0.220785014527169,
  -0.0471016581128118,
  -0.104444028769085,
  -0.0614383102799759,
  -0.583785476859646,
  0.0444660484197186,
  -0.375262716876542,
  -0.10447339551748,
  -0.445230728416819,
  -0.218967202072155,
  -0.0618525440919212,
  nan,
  0.188789870027128,
  0.113838678588237,
  0.0841521406679899,
  0.123540501013125,
  -0.239319239681467,
  -0.145552233773313,
  -0.147898048462676,
  0.0159196720782552,
  -0.445798281781498,
  0.124794856405012,
  -0.644720080536172,
  -0.0402663387542101,
  -0.269720419526465,
  -0.182346889361415,
  -0.0440230965363782,
  0.0347815684144794,
  -0.2343950889313,
  -0.462989472236078,
  0.321499561513196,
  0.0786299459484394,
  0.577753821408959,
  0.379206288278378,
  0.312380770266737,
  0.206823889357197,
  -0.0496122817204272,
  0.0621337631055811,
  -0.238950639779037,
  0.253991732885064,
  0.427472731039924,
  0.186495803358201,
  0.117998227359578,
  0.237532427615764,
  nan,
  0.153229520136541,
  0.0876506103447198,
  -0.0783897632239088,
  -0.169148488345329,
  -0.243090486286361,
  -0.697884004453069,
  0.173805842845404,
  0.537566175952413,
  0.266509095313126,
  -0.496327379722611,
  -0.197302113503687,
  nan,
  -0.377263322374108,
  -0.495353066290763,
  -0.241857286945743,
  -0.251692222142236,
  0.356543577447394,
  -0.621372595220764,
  -0.346883667391005,
  -0.513515856334952,
  -0.239548949840169,
  -0.564330875867578,
  -0.526033707090708,
  -0.408390985817775,
  -0.261437086258329,
  0.472714599158523,
  0.412124843060886,
  0.379104910935014,
  0.408059277470146,
  -0.0687776438181888,
  0.318934986343213,
  0.276277965247034,
  -0.0941400058867234,
  nan,
  0.245521287643886,
  0.489728467534427,
  0.183127528995476,
  0.168065051204249,
  0.512058762584098,
  0.119719272649564,
  0.312417149349561,
  -0.229300198374587,
  0.309323018888076,
  -0.0606443750257987,
  0.0634732055389047,
  0.107457423334948,
  0.25805282391868,
  0.455013644340624,
  0.271676068864434,
  -0.322170751043706,
  0.0789846467336927,
  -0.182737561109111,
  nan,
  -0.925253065574212,
  -0.0695163729378698,
  -0.16230073139209,
  0.0018673109086782,
  0.154181687710653,
  0.114180885931124,
  -0.425137151127144,
  0.105151554203343,
  -0.119040232346339,
  0.172895529388763,
  0.228843756748571,
  0.217610266000738,
  -0.119733842745397,
  0.42360333726685,
  0.396801991308386,
  0.355861273494988,
  0.0057585374982641,
  0.112609474708835,
  0.12173354489894,
  nan,
  0.070843680728518,
  0.0581426375769292,
  0.203678461007222,
  0.0947747955772665,
  0.454436800363184,
  -0.0613960466003703,
  -0.0086177950294005,
  0.224767323800835,
  0.119225489145265,
  0.171518752577824,
  -0.145958217602909,
  -0.0129330345084192,
  0.263538383514649,
  -0.114269274132066,
  0.237161629727988,
  0.148937327177496,
  -0.3091089496017,
  0.16580817855111,
  nan,
  -0.560492433575576,
  -0.426287210695436,
  -0.43977739855083,
  0.110314122320367,
  0.309021730196797,
  0.0625668208946849,
  -0.670838950684092,
  -0.0299799260936009,
  0.343492087213673,
  0.153207622539266,
  -0.160965628685677,
  -0.312406786199201,
  -0.4140116020339]}