In [1]:
import os

from io import StringIO
from google.cloud import storage
from dotenv import load_dotenv

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import torch
import torch.nn.functional as F

from transformers import AutoModelForCausalLM
from transformers import AutoTokenizer, EsmForMaskedLM
from tokenizers import Tokenizer
from peft import get_peft_model, LoraConfig, TaskType

/opt/anaconda3/envs/MachLearn/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
from plm_compare_progen2 import *
from plm_compare_esm import *
from protein_data import *

In [3]:
with open('/Users/johnhutchens/Desktop/Practicum/Data/Wild_Dictionaries/pg2_ProGym_matrices.pickle',
           'rb') as f:
    pg_dict = pickle.load(f)

In [4]:
# inserts mutation amino acid in corresponding position in protein sequence
def insert_wt(seq, pos, wt_aa):
    seq_list = list(seq)
    pos = int(pos)
    if pos < len(seq_list):
        seq_list[pos] = wt_aa
    return ''.join(seq_list)

# computes the ranking loss between two iterables
def listwise_ranking_loss(preds, targets):
    indices = targets.sort(descending=True).indices
    preds = torch.gather(preds, dim=-1, index=indices)
    cumsums = preds.exp().flip(dims=[-1]).cumsum(dim=-1).flip(dims=[-1])
    loss = torch.log(cumsums + 1e-10) - preds
    return loss.mean()

In [ ]:
# load_dotenv()
# cred_path = os.getenv('GOOGLE_APPLICATION_CREDENTIALS')

# os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = cred_path

# client = storage.Client()
# bucket = client.bucket('domainome-data')
# blob = bucket.blob('SupplementaryTable2.txt')

# df = pd.read_csv(StringIO(blob.download_as_text()), sep='\t')

Get data for one domain.  In this case P07316_PF00030_87.  Translate position by initial domain position.

In [ ]:
# df_one_protein = df.where(df['domain_ID'] == 'P07316_PF00030_87').dropna()

# dom_position = df_one_protein['position'] - 87.0
# df_one_protein.insert(loc=0, column='real_position', value=dom_position)
# df_one_protein_ns = df_one_protein[df_one_protein['mut_aa'] != '*'].copy()

# df_one_protein_ns.head()

,real_position,domain_ID,uniprot_ID,aa_seq,wt_aa,position,mut_aa,STOP,input_count_rep1,input_count_rep2,input_count_rep3,output_count_rep1,output_count_rep2,output_count_rep3,mean_input_count,fitness,fitness_sigma,normalized_fitness,normalized_fitness_sigma,quality_rank
121785,0.0,P07316_PF00030_87,P07316,AAYRMKIYDRDELRGQMSELTDDCISVQDRFHLTEIHSLNVLEGSW...,G,87.0,A,False,645.0,476.0,327.0,202.0,183.0,264.0,482.6667,0.067864,0.006483,0.163960,0.070917,385.0
121786,0.0,P07316_PF00030_87,P07316,CAYRMKIYDRDELRGQMSELTDDCISVQDRFHLTEIHSLNVLEGSW...,G,87.0,C,False,1155.0,733.0,502.0,198.0,257.0,578.0,796.6667,0.061549,0.005723,0.094874,0.062609,385.0
121787,0.0,P07316_PF00030_87,P07316,DAYRMKIYDRDELRGQMSELTDDCISVQDRFHLTEIHSLNVLEGSW...,G,87.0,D,False,1079.0,784.0,566.0,197.0,220.0,399.0,809.6667,0.054534,0.006000,0.018137,0.065632,385.0
121788,0.0,P07316_PF00030_87,P07316,EAYRMKIYDRDELRGQMSELTDDCISVQDRFHLTEIHSLNVLEGSW...,G,87.0,E,False,305.0,251.0,187.0,75.0,94.0,182.0,247.6667,0.067474,0.008372,0.159687,0.091586,385.0
121789,0.0,P07316_PF00030_87,P07316,FAYRMKIYDRDELRGQMSELTDDCISVQDRFHLTEIHSLNVLEGSW...,G,87.0,F,False,803.0,628.0,463.0,241.0,412.0,729.0,631.3333,0.083318,0.004906,0.333017,0.053670,385.0

Insert mutation into correct position of protein sequence.

In [ ]:
# df_one_protein_ns['wt_seq'] = df_one_protein_ns.apply(lambda row: 
#                                                       insert_wt(row['aa_seq'], row['real_position'], row['wt_aa']),
#                                                       axis=1)

In [ ]:
# df_mutation = df_one_protein_ns[['real_position','mut_aa','normalized_fitness']]
# df_mutation
# df_mutation.to_csv("mutation.csv")

        real_position mut_aa  normalized_fitness
121785            0.0      A            0.163960
121786            0.0      C            0.094874
121787            0.0      D            0.018137
121788            0.0      E            0.159687
121789            0.0      F            0.333017
...               ...    ...                 ...
123520            0.0      S            0.000670
123521            0.0      T            0.058108
123522            0.0      V            0.049949
123523            0.0      W            0.022983
123524            0.0      Y            0.323293

[1650 rows x 3 columns]

In [5]:
df_mutation = pd.read_csv('mutation.csv')

Initializing base model Pro Gen 2

In [6]:
# device = "cuda" if torch.cuda.is_available() else "cpu"
device = 'cpu'
print(f"Using {device} device")

model_name = "hugohrban/progen2-medium"
base_model, tokenizer = initialize_progen2_noeval(model_name)

Using cpu device

Initializing LoRA

In [7]:
for name, module in base_model.named_modules():
    print(name)

transformer
transformer.wte
transformer.drop
transformer.h
transformer.h.0
transformer.h.0.ln_1
transformer.h.0.attn
transformer.h.0.attn.attn_dropout
transformer.h.0.attn.resid_dropout
transformer.h.0.attn.qkv_proj
transformer.h.0.attn.out_proj
transformer.h.0.mlp
transformer.h.0.mlp.fc_in
transformer.h.0.mlp.fc_out
transformer.h.0.mlp.act
transformer.h.0.mlp.dropout
transformer.h.1
transformer.h.1.ln_1
transformer.h.1.attn
transformer.h.1.attn.attn_dropout
transformer.h.1.attn.resid_dropout
transformer.h.1.attn.qkv_proj
transformer.h.1.attn.out_proj
transformer.h.1.mlp
transformer.h.1.mlp.fc_in
transformer.h.1.mlp.fc_out
transformer.h.1.mlp.act
transformer.h.1.mlp.dropout
transformer.h.2
transformer.h.2.ln_1
transformer.h.2.attn
transformer.h.2.attn.attn_dropout
transformer.h.2.attn.resid_dropout
transformer.h.2.attn.qkv_proj
transformer.h.2.attn.out_proj
transformer.h.2.mlp
transformer.h.2.mlp.fc_in
transformer.h.2.mlp.fc_out
transformer.h.2.mlp.act
transformer.h.2.mlp.dropout
transformer.h.3
transformer.h.3.ln_1
transformer.h.3.attn
transformer.h.3.attn.attn_dropout
transformer.h.3.attn.resid_dropout
transformer.h.3.attn.qkv_proj
transformer.h.3.attn.out_proj
transformer.h.3.mlp
transformer.h.3.mlp.fc_in
transformer.h.3.mlp.fc_out
transformer.h.3.mlp.act
transformer.h.3.mlp.dropout
transformer.h.4
transformer.h.4.ln_1
transformer.h.4.attn
transformer.h.4.attn.attn_dropout
transformer.h.4.attn.resid_dropout
transformer.h.4.attn.qkv_proj
transformer.h.4.attn.out_proj
transformer.h.4.mlp
transformer.h.4.mlp.fc_in
transformer.h.4.mlp.fc_out
transformer.h.4.mlp.act
transformer.h.4.mlp.dropout
transformer.h.5
transformer.h.5.ln_1
transformer.h.5.attn
transformer.h.5.attn.attn_dropout
transformer.h.5.attn.resid_dropout
transformer.h.5.attn.qkv_proj
transformer.h.5.attn.out_proj
transformer.h.5.mlp
transformer.h.5.mlp.fc_in
transformer.h.5.mlp.fc_out
transformer.h.5.mlp.act
transformer.h.5.mlp.dropout
transformer.h.6
transformer.h.6.ln_1
transformer.h.6.attn
transformer.h.6.attn.attn_dropout
transformer.h.6.attn.resid_dropout
transformer.h.6.attn.qkv_proj
transformer.h.6.attn.out_proj
transformer.h.6.mlp
transformer.h.6.mlp.fc_in
transformer.h.6.mlp.fc_out
transformer.h.6.mlp.act
transformer.h.6.mlp.dropout
transformer.h.7
transformer.h.7.ln_1
transformer.h.7.attn
transformer.h.7.attn.attn_dropout
transformer.h.7.attn.resid_dropout
transformer.h.7.attn.qkv_proj
transformer.h.7.attn.out_proj
transformer.h.7.mlp
transformer.h.7.mlp.fc_in
transformer.h.7.mlp.fc_out
transformer.h.7.mlp.act
transformer.h.7.mlp.dropout
transformer.h.8
transformer.h.8.ln_1
transformer.h.8.attn
transformer.h.8.attn.attn_dropout
transformer.h.8.attn.resid_dropout
transformer.h.8.attn.qkv_proj
transformer.h.8.attn.out_proj
transformer.h.8.mlp
transformer.h.8.mlp.fc_in
transformer.h.8.mlp.fc_out
transformer.h.8.mlp.act
transformer.h.8.mlp.dropout
transformer.h.9
transformer.h.9.ln_1
transformer.h.9.attn
transformer.h.9.attn.attn_dropout
transformer.h.9.attn.resid_dropout
transformer.h.9.attn.qkv_proj
transformer.h.9.attn.out_proj
transformer.h.9.mlp
transformer.h.9.mlp.fc_in
transformer.h.9.mlp.fc_out
transformer.h.9.mlp.act
transformer.h.9.mlp.dropout
transformer.h.10
transformer.h.10.ln_1
transformer.h.10.attn
transformer.h.10.attn.attn_dropout
transformer.h.10.attn.resid_dropout
transformer.h.10.attn.qkv_proj
transformer.h.10.attn.out_proj
transformer.h.10.mlp
transformer.h.10.mlp.fc_in
transformer.h.10.mlp.fc_out
transformer.h.10.mlp.act
transformer.h.10.mlp.dropout
transformer.h.11
transformer.h.11.ln_1
transformer.h.11.attn
transformer.h.11.attn.attn_dropout
transformer.h.11.attn.resid_dropout
transformer.h.11.attn.qkv_proj
transformer.h.11.attn.out_proj
transformer.h.11.mlp
transformer.h.11.mlp.fc_in
transformer.h.11.mlp.fc_out
transformer.h.11.mlp.act
transformer.h.11.mlp.dropout
transformer.h.12
transformer.h.12.ln_1
transformer.h.12.attn
transformer.h.12.attn.attn_dropout
transformer.h.12.attn.resid_dropout
transformer.h.12.attn.qkv_proj
transformer.h.12.attn.out_proj
transformer.h.12.mlp
transformer.h.12.mlp.fc_in
transformer.h.12.mlp.fc_out
transformer.h.12.mlp.act
transformer.h.12.mlp.dropout
transformer.h.13
transformer.h.13.ln_1
transformer.h.13.attn
transformer.h.13.attn.attn_dropout
transformer.h.13.attn.resid_dropout
transformer.h.13.attn.qkv_proj
transformer.h.13.attn.out_proj
transformer.h.13.mlp
transformer.h.13.mlp.fc_in
transformer.h.13.mlp.fc_out
transformer.h.13.mlp.act
transformer.h.13.mlp.dropout
transformer.h.14
transformer.h.14.ln_1
transformer.h.14.attn
transformer.h.14.attn.attn_dropout
transformer.h.14.attn.resid_dropout
transformer.h.14.attn.qkv_proj
transformer.h.14.attn.out_proj
transformer.h.14.mlp
transformer.h.14.mlp.fc_in
transformer.h.14.mlp.fc_out
transformer.h.14.mlp.act
transformer.h.14.mlp.dropout
transformer.h.15
transformer.h.15.ln_1
transformer.h.15.attn
transformer.h.15.attn.attn_dropout
transformer.h.15.attn.resid_dropout
transformer.h.15.attn.qkv_proj
transformer.h.15.attn.out_proj
transformer.h.15.mlp
transformer.h.15.mlp.fc_in
transformer.h.15.mlp.fc_out
transformer.h.15.mlp.act
transformer.h.15.mlp.dropout
transformer.h.16
transformer.h.16.ln_1
transformer.h.16.attn
transformer.h.16.attn.attn_dropout
transformer.h.16.attn.resid_dropout
transformer.h.16.attn.qkv_proj
transformer.h.16.attn.out_proj
transformer.h.16.mlp
transformer.h.16.mlp.fc_in
transformer.h.16.mlp.fc_out
transformer.h.16.mlp.act
transformer.h.16.mlp.dropout
transformer.h.17
transformer.h.17.ln_1
transformer.h.17.attn
transformer.h.17.attn.attn_dropout
transformer.h.17.attn.resid_dropout
transformer.h.17.attn.qkv_proj
transformer.h.17.attn.out_proj
transformer.h.17.mlp
transformer.h.17.mlp.fc_in
transformer.h.17.mlp.fc_out
transformer.h.17.mlp.act
transformer.h.17.mlp.dropout
transformer.h.18
transformer.h.18.ln_1
transformer.h.18.attn
transformer.h.18.attn.attn_dropout
transformer.h.18.attn.resid_dropout
transformer.h.18.attn.qkv_proj
transformer.h.18.attn.out_proj
transformer.h.18.mlp
transformer.h.18.mlp.fc_in
transformer.h.18.mlp.fc_out
transformer.h.18.mlp.act
transformer.h.18.mlp.dropout
transformer.h.19
transformer.h.19.ln_1
transformer.h.19.attn
transformer.h.19.attn.attn_dropout
transformer.h.19.attn.resid_dropout
transformer.h.19.attn.qkv_proj
transformer.h.19.attn.out_proj
transformer.h.19.mlp
transformer.h.19.mlp.fc_in
transformer.h.19.mlp.fc_out
transformer.h.19.mlp.act
transformer.h.19.mlp.dropout
transformer.h.20
transformer.h.20.ln_1
transformer.h.20.attn
transformer.h.20.attn.attn_dropout
transformer.h.20.attn.resid_dropout
transformer.h.20.attn.qkv_proj
transformer.h.20.attn.out_proj
transformer.h.20.mlp
transformer.h.20.mlp.fc_in
transformer.h.20.mlp.fc_out
transformer.h.20.mlp.act
transformer.h.20.mlp.dropout
transformer.h.21
transformer.h.21.ln_1
transformer.h.21.attn
transformer.h.21.attn.attn_dropout
transformer.h.21.attn.resid_dropout
transformer.h.21.attn.qkv_proj
transformer.h.21.attn.out_proj
transformer.h.21.mlp
transformer.h.21.mlp.fc_in
transformer.h.21.mlp.fc_out
transformer.h.21.mlp.act
transformer.h.21.mlp.dropout
transformer.h.22
transformer.h.22.ln_1
transformer.h.22.attn
transformer.h.22.attn.attn_dropout
transformer.h.22.attn.resid_dropout
transformer.h.22.attn.qkv_proj
transformer.h.22.attn.out_proj
transformer.h.22.mlp
transformer.h.22.mlp.fc_in
transformer.h.22.mlp.fc_out
transformer.h.22.mlp.act
transformer.h.22.mlp.dropout
transformer.h.23
transformer.h.23.ln_1
transformer.h.23.attn
transformer.h.23.attn.attn_dropout
transformer.h.23.attn.resid_dropout
transformer.h.23.attn.qkv_proj
transformer.h.23.attn.out_proj
transformer.h.23.mlp
transformer.h.23.mlp.fc_in
transformer.h.23.mlp.fc_out
transformer.h.23.mlp.act
transformer.h.23.mlp.dropout
transformer.h.24
transformer.h.24.ln_1
transformer.h.24.attn
transformer.h.24.attn.attn_dropout
transformer.h.24.attn.resid_dropout
transformer.h.24.attn.qkv_proj
transformer.h.24.attn.out_proj
transformer.h.24.mlp
transformer.h.24.mlp.fc_in
transformer.h.24.mlp.fc_out
transformer.h.24.mlp.act
transformer.h.24.mlp.dropout
transformer.h.25
transformer.h.25.ln_1
transformer.h.25.attn
transformer.h.25.attn.attn_dropout
transformer.h.25.attn.resid_dropout
transformer.h.25.attn.qkv_proj
transformer.h.25.attn.out_proj
transformer.h.25.mlp
transformer.h.25.mlp.fc_in
transformer.h.25.mlp.fc_out
transformer.h.25.mlp.act
transformer.h.25.mlp.dropout
transformer.h.26
transformer.h.26.ln_1
transformer.h.26.attn
transformer.h.26.attn.attn_dropout
transformer.h.26.attn.resid_dropout
transformer.h.26.attn.qkv_proj
transformer.h.26.attn.out_proj
transformer.h.26.mlp
transformer.h.26.mlp.fc_in
transformer.h.26.mlp.fc_out
transformer.h.26.mlp.act
transformer.h.26.mlp.dropout
transformer.ln_f
lm_head

In [8]:
lora_config = LoraConfig(
    r=8,
    lora_alpha=32,
    # target_modules=["query", "key", "value", "output.dense"],
    target_modules=["qkv_proj", "out_proj"],
    lora_dropout=0.1,
    bias="none",
    # task_type=TaskType.FEATURE_EXTRACTION
    task_type=TaskType.CAUSAL_LM
)
model = get_peft_model(base_model, lora_config)

In [9]:
for name, module in base_model.named_modules():
    if "qkv_proj" in name or "out_proj" in name:
        print(name, module)

transformer.h.0.attn.qkv_proj lora.Linear(
  (base_layer): Linear(in_features=1536, out_features=4608, bias=False)
  (lora_dropout): ModuleDict(
    (default): Dropout(p=0.1, inplace=False)
  )
  (lora_A): ModuleDict(
    (default): Linear(in_features=1536, out_features=8, bias=False)
  )
  (lora_B): ModuleDict(
    (default): Linear(in_features=8, out_features=4608, bias=False)
  )
  (lora_embedding_A): ParameterDict()
  (lora_embedding_B): ParameterDict()
  (lora_magnitude_vector): ModuleDict()
)
transformer.h.0.attn.qkv_proj.base_layer Linear(in_features=1536, out_features=4608, bias=False)
transformer.h.0.attn.qkv_proj.lora_dropout ModuleDict(
  (default): Dropout(p=0.1, inplace=False)
)
transformer.h.0.attn.qkv_proj.lora_dropout.default Dropout(p=0.1, inplace=False)
transformer.h.0.attn.qkv_proj.lora_A ModuleDict(
  (default): Linear(in_features=1536, out_features=8, bias=False)
)
transformer.h.0.attn.qkv_proj.lora_A.default Linear(in_features=1536, out_features=8, bias=False)
transformer.h.0.attn.qkv_proj.lora_B ModuleDict(
  (default): Linear(in_features=8, out_features=4608, bias=False)
)
transformer.h.0.attn.qkv_proj.lora_B.default Linear(in_features=8, out_features=4608, bias=False)
transformer.h.0.attn.qkv_proj.lora_embedding_A ParameterDict()
transformer.h.0.attn.qkv_proj.lora_embedding_B ParameterDict()
transformer.h.0.attn.qkv_proj.lora_magnitude_vector ModuleDict()
transformer.h.0.attn.out_proj lora.Linear(
  (base_layer): Linear(in_features=1536, out_features=1536, bias=False)
  (lora_dropout): ModuleDict(
    (default): Dropout(p=0.1, inplace=False)
  )
  (lora_A): ModuleDict(
    (default): Linear(in_features=1536, out_features=8, bias=False)
  )
  (lora_B): ModuleDict(
    (default): Linear(in_features=8, out_features=1536, bias=False)
  )
  (lora_embedding_A): ParameterDict()
  (lora_embedding_B): ParameterDict()
  (lora_magnitude_vector): ModuleDict()
)
transformer.h.0.attn.out_proj.base_layer Linear(in_features=1536, out_features=1536, bias=False)
transformer.h.0.attn.out_proj.lora_dropout ModuleDict(
  (default): Dropout(p=0.1, inplace=False)
)
transformer.h.0.attn.out_proj.lora_dropout.default Dropout(p=0.1, inplace=False)
transformer.h.0.attn.out_proj.lora_A ModuleDict(
  (default): Linear(in_features=1536, out_features=8, bias=False)
)
transformer.h.0.attn.out_proj.lora_A.default Linear(in_features=1536, out_features=8, bias=False)
transformer.h.0.attn.out_proj.lora_B ModuleDict(
  (default): Linear(in_features=8, out_features=1536, bias=False)
)
transformer.h.0.attn.out_proj.lora_B.default Linear(in_features=8, out_features=1536, bias=False)
transformer.h.0.attn.out_proj.lora_embedding_A ParameterDict()
transformer.h.0.attn.out_proj.lora_embedding_B ParameterDict()
transformer.h.0.attn.out_proj.lora_magnitude_vector ModuleDict()
transformer.h.1.attn.qkv_proj lora.Linear(
  (base_layer): Linear(in_features=1536, out_features=4608, bias=False)
  (lora_dropout): ModuleDict(
    (default): Dropout(p=0.1, inplace=False)
  )
  (lora_A): ModuleDict(
    (default): Linear(in_features=1536, out_features=8, bias=False)
  )
  (lora_B): ModuleDict(
    (default): Linear(in_features=8, out_features=4608, bias=False)
  )
  (lora_embedding_A): ParameterDict()
  (lora_embedding_B): ParameterDict()
  (lora_magnitude_vector): ModuleDict()
)
transformer.h.1.attn.qkv_proj.base_layer Linear(in_features=1536, out_features=4608, bias=False)
transformer.h.1.attn.qkv_proj.lora_dropout ModuleDict(
  (default): Dropout(p=0.1, inplace=False)
)
transformer.h.1.attn.qkv_proj.lora_dropout.default Dropout(p=0.1, inplace=False)
transformer.h.1.attn.qkv_proj.lora_A ModuleDict(
  (default): Linear(in_features=1536, out_features=8, bias=False)
)
transformer.h.1.attn.qkv_proj.lora_A.default Linear(in_features=1536, out_features=8, bias=False)
transformer.h.1.attn.qkv_proj.lora_B ModuleDict(
  (default): Linear(in_features=8, out_features=4608, bias=False)
)
transformer.h.1.attn.qkv_proj.lora_B.default Linear(in_features=8, out_features=4608, bias=False)
transformer.h.1.attn.qkv_proj.lora_embedding_A ParameterDict()
transformer.h.1.attn.qkv_proj.lora_embedding_B ParameterDict()
transformer.h.1.attn.qkv_proj.lora_magnitude_vector ModuleDict()
transformer.h.1.attn.out_proj lora.Linear(
  (base_layer): Linear(in_features=1536, out_features=1536, bias=False)
  (lora_dropout): ModuleDict(
    (default): Dropout(p=0.1, inplace=False)
  )
  (lora_A): ModuleDict(
    (default): Linear(in_features=1536, out_features=8, bias=False)
  )
  (lora_B): ModuleDict(
    (default): Linear(in_features=8, out_features=1536, bias=False)
  )
  (lora_embedding_A): ParameterDict()
  (lora_embedding_B): ParameterDict()
  (lora_magnitude_vector): ModuleDict()
)
transformer.h.1.attn.out_proj.base_layer Linear(in_features=1536, out_features=1536, bias=False)
transformer.h.1.attn.out_proj.lora_dropout ModuleDict(
  (default): Dropout(p=0.1, inplace=False)
)
transformer.h.1.attn.out_proj.lora_dropout.default Dropout(p=0.1, inplace=False)
transformer.h.1.attn.out_proj.lora_A ModuleDict(
  (default): Linear(in_features=1536, out_features=8, bias=False)
)
transformer.h.1.attn.out_proj.lora_A.default Linear(in_features=1536, out_features=8, bias=False)
transformer.h.1.attn.out_proj.lora_B ModuleDict(
  (default): Linear(in_features=8, out_features=1536, bias=False)
)
transformer.h.1.attn.out_proj.lora_B.default Linear(in_features=8, out_features=1536, bias=False)
transformer.h.1.attn.out_proj.lora_embedding_A ParameterDict()
transformer.h.1.attn.out_proj.lora_embedding_B ParameterDict()
transformer.h.1.attn.out_proj.lora_magnitude_vector ModuleDict()
transformer.h.2.attn.qkv_proj lora.Linear(
  (base_layer): Linear(in_features=1536, out_features=4608, bias=False)
  (lora_dropout): ModuleDict(
    (default): Dropout(p=0.1, inplace=False)
  )
  (lora_A): ModuleDict(
    (default): Linear(in_features=1536, out_features=8, bias=False)
  )
  (lora_B): ModuleDict(
    (default): Linear(in_features=8, out_features=4608, bias=False)
  )
  (lora_embedding_A): ParameterDict()
  (lora_embedding_B): ParameterDict()
  (lora_magnitude_vector): ModuleDict()
)
transformer.h.2.attn.qkv_proj.base_layer Linear(in_features=1536, out_features=4608, bias=False)
transformer.h.2.attn.qkv_proj.lora_dropout ModuleDict(
  (default): Dropout(p=0.1, inplace=False)
)
transformer.h.2.attn.qkv_proj.lora_dropout.default Dropout(p=0.1, inplace=False)
transformer.h.2.attn.qkv_proj.lora_A ModuleDict(
  (default): Linear(in_features=1536, out_features=8, bias=False)
)
transformer.h.2.attn.qkv_proj.lora_A.default Linear(in_features=1536, out_features=8, bias=False)
transformer.h.2.attn.qkv_proj.lora_B ModuleDict(
  (default): Linear(in_features=8, out_features=4608, bias=False)
)
transformer.h.2.attn.qkv_proj.lora_B.default Linear(in_features=8, out_features=4608, bias=False)
transformer.h.2.attn.qkv_proj.lora_embedding_A ParameterDict()
transformer.h.2.attn.qkv_proj.lora_embedding_B ParameterDict()
transformer.h.2.attn.qkv_proj.lora_magnitude_vector ModuleDict()
transformer.h.2.attn.out_proj lora.Linear(
  (base_layer): Linear(in_features=1536, out_features=1536, bias=False)
  (lora_dropout): ModuleDict(
    (default): Dropout(p=0.1, inplace=False)
  )
  (lora_A): ModuleDict(
    (default): Linear(in_features=1536, out_features=8, bias=False)
  )
  (lora_B): ModuleDict(
    (default): Linear(in_features=8, out_features=1536, bias=False)
  )
  (lora_embedding_A): ParameterDict()
  (lora_embedding_B): ParameterDict()
  (lora_magnitude_vector): ModuleDict()
)
transformer.h.2.attn.out_proj.base_layer Linear(in_features=1536, out_features=1536, bias=False)
transformer.h.2.attn.out_proj.lora_dropout ModuleDict(
  (default): Dropout(p=0.1, inplace=False)
)
transformer.h.2.attn.out_proj.lora_dropout.default Dropout(p=0.1, inplace=False)
transformer.h.2.attn.out_proj.lora_A ModuleDict(
  (default): Linear(in_features=1536, out_features=8, bias=False)
)
transformer.h.2.attn.out_proj.lora_A.default Linear(in_features=1536, out_features=8, bias=False)
transformer.h.2.attn.out_proj.lora_B ModuleDict(
  (default): Linear(in_features=8, out_features=1536, bias=False)
)
transformer.h.2.attn.out_proj.lora_B.default Linear(in_features=8, out_features=1536, bias=False)
transformer.h.2.attn.out_proj.lora_embedding_A ParameterDict()
transformer.h.2.attn.out_proj.lora_embedding_B ParameterDict()
transformer.h.2.attn.out_proj.lora_magnitude_vector ModuleDict()
transformer.h.3.attn.qkv_proj lora.Linear(
  (base_layer): Linear(in_features=1536, out_features=4608, bias=False)
  (lora_dropout): ModuleDict(
    (default): Dropout(p=0.1, inplace=False)
  )
  (lora_A): ModuleDict(
    (default): Linear(in_features=1536, out_features=8, bias=False)
  )
  (lora_B): ModuleDict(
    (default): Linear(in_features=8, out_features=4608, bias=False)
  )
  (lora_embedding_A): ParameterDict()
  (lora_embedding_B): ParameterDict()
  (lora_magnitude_vector): ModuleDict()
)
transformer.h.3.attn.qkv_proj.base_layer Linear(in_features=1536, out_features=4608, bias=False)
transformer.h.3.attn.qkv_proj.lora_dropout ModuleDict(
  (default): Dropout(p=0.1, inplace=False)
)
transformer.h.3.attn.qkv_proj.lora_dropout.default Dropout(p=0.1, inplace=False)
transformer.h.3.attn.qkv_proj.lora_A ModuleDict(
  (default): Linear(in_features=1536, out_features=8, bias=False)
)
transformer.h.3.attn.qkv_proj.lora_A.default Linear(in_features=1536, out_features=8, bias=False)
transformer.h.3.attn.qkv_proj.lora_B ModuleDict(
  (default): Linear(in_features=8, out_features=4608, bias=False)
)
transformer.h.3.attn.qkv_proj.lora_B.default Linear(in_features=8, out_features=4608, bias=False)
transformer.h.3.attn.qkv_proj.lora_embedding_A ParameterDict()
transformer.h.3.attn.qkv_proj.lora_embedding_B ParameterDict()
transformer.h.3.attn.qkv_proj.lora_magnitude_vector ModuleDict()
transformer.h.3.attn.out_proj lora.Linear(
  (base_layer): Linear(in_features=1536, out_features=1536, bias=False)
  (lora_dropout): ModuleDict(
    (default): Dropout(p=0.1, inplace=False)
  )
  (lora_A): ModuleDict(
    (default): Linear(in_features=1536, out_features=8, bias=False)
  )
  (lora_B): ModuleDict(
    (default): Linear(in_features=8, out_features=1536, bias=False)
  )
  (lora_embedding_A): ParameterDict()
  (lora_embedding_B): ParameterDict()
  (lora_magnitude_vector): ModuleDict()
)
transformer.h.3.attn.out_proj.base_layer Linear(in_features=1536, out_features=1536, bias=False)
transformer.h.3.attn.out_proj.lora_dropout ModuleDict(
  (default): Dropout(p=0.1, inplace=False)
)
transformer.h.3.attn.out_proj.lora_dropout.default Dropout(p=0.1, inplace=False)
transformer.h.3.attn.out_proj.lora_A ModuleDict(
  (default): Linear(in_features=1536, out_features=8, bias=False)
)
transformer.h.3.attn.out_proj.lora_A.default Linear(in_features=1536, out_features=8, bias=False)
transformer.h.3.attn.out_proj.lora_B ModuleDict(
  (default): Linear(in_features=8, out_features=1536, bias=False)
)
transformer.h.3.attn.out_proj.lora_B.default Linear(in_features=8, out_features=1536, bias=False)
transformer.h.3.attn.out_proj.lora_embedding_A ParameterDict()
transformer.h.3.attn.out_proj.lora_embedding_B ParameterDict()
transformer.h.3.attn.out_proj.lora_magnitude_vector ModuleDict()
transformer.h.4.attn.qkv_proj lora.Linear(
  (base_layer): Linear(in_features=1536, out_features=4608, bias=False)
  (lora_dropout): ModuleDict(
    (default): Dropout(p=0.1, inplace=False)
  )
  (lora_A): ModuleDict(
    (default): Linear(in_features=1536, out_features=8, bias=False)
  )
  (lora_B): ModuleDict(
    (default): Linear(in_features=8, out_features=4608, bias=False)
  )
  (lora_embedding_A): ParameterDict()
  (lora_embedding_B): ParameterDict()
  (lora_magnitude_vector): ModuleDict()
)
transformer.h.4.attn.qkv_proj.base_layer Linear(in_features=1536, out_features=4608, bias=False)
transformer.h.4.attn.qkv_proj.lora_dropout ModuleDict(
  (default): Dropout(p=0.1, inplace=False)
)
transformer.h.4.attn.qkv_proj.lora_dropout.default Dropout(p=0.1, inplace=False)
transformer.h.4.attn.qkv_proj.lora_A ModuleDict(
  (default): Linear(in_features=1536, out_features=8, bias=False)
)
transformer.h.4.attn.qkv_proj.lora_A.default Linear(in_features=1536, out_features=8, bias=False)
transformer.h.4.attn.qkv_proj.lora_B ModuleDict(
  (default): Linear(in_features=8, out_features=4608, bias=False)
)
transformer.h.4.attn.qkv_proj.lora_B.default Linear(in_features=8, out_features=4608, bias=False)
transformer.h.4.attn.qkv_proj.lora_embedding_A ParameterDict()
transformer.h.4.attn.qkv_proj.lora_embedding_B ParameterDict()
transformer.h.4.attn.qkv_proj.lora_magnitude_vector ModuleDict()
transformer.h.4.attn.out_proj lora.Linear(
  (base_layer): Linear(in_features=1536, out_features=1536, bias=False)
  (lora_dropout): ModuleDict(
    (default): Dropout(p=0.1, inplace=False)
  )
  (lora_A): ModuleDict(
    (default): Linear(in_features=1536, out_features=8, bias=False)
  )
  (lora_B): ModuleDict(
    (default): Linear(in_features=8, out_features=1536, bias=False)
  )
  (lora_embedding_A): ParameterDict()
  (lora_embedding_B): ParameterDict()
  (lora_magnitude_vector): ModuleDict()
)
transformer.h.4.attn.out_proj.base_layer Linear(in_features=1536, out_features=1536, bias=False)
transformer.h.4.attn.out_proj.lora_dropout ModuleDict(
  (default): Dropout(p=0.1, inplace=False)
)
transformer.h.4.attn.out_proj.lora_dropout.default Dropout(p=0.1, inplace=False)
transformer.h.4.attn.out_proj.lora_A ModuleDict(
  (default): Linear(in_features=1536, out_features=8, bias=False)
)
transformer.h.4.attn.out_proj.lora_A.default Linear(in_features=1536, out_features=8, bias=False)
transformer.h.4.attn.out_proj.lora_B ModuleDict(
  (default): Linear(in_features=8, out_features=1536, bias=False)
)
transformer.h.4.attn.out_proj.lora_B.default Linear(in_features=8, out_features=1536, bias=False)
transformer.h.4.attn.out_proj.lora_embedding_A ParameterDict()
transformer.h.4.attn.out_proj.lora_embedding_B ParameterDict()
transformer.h.4.attn.out_proj.lora_magnitude_vector ModuleDict()
transformer.h.5.attn.qkv_proj lora.Linear(
  (base_layer): Linear(in_features=1536, out_features=4608, bias=False)
  (lora_dropout): ModuleDict(
    (default): Dropout(p=0.1, inplace=False)
  )
  (lora_A): ModuleDict(
    (default): Linear(in_features=1536, out_features=8, bias=False)
  )
  (lora_B): ModuleDict(
    (default): Linear(in_features=8, out_features=4608, bias=False)
  )
  (lora_embedding_A): ParameterDict()
  (lora_embedding_B): ParameterDict()
  (lora_magnitude_vector): ModuleDict()
)
transformer.h.5.attn.qkv_proj.base_layer Linear(in_features=1536, out_features=4608, bias=False)
transformer.h.5.attn.qkv_proj.lora_dropout ModuleDict(
  (default): Dropout(p=0.1, inplace=False)
)
transformer.h.5.attn.qkv_proj.lora_dropout.default Dropout(p=0.1, inplace=False)
transformer.h.5.attn.qkv_proj.lora_A ModuleDict(
  (default): Linear(in_features=1536, out_features=8, bias=False)
)
transformer.h.5.attn.qkv_proj.lora_A.default Linear(in_features=1536, out_features=8, bias=False)
transformer.h.5.attn.qkv_proj.lora_B ModuleDict(
  (default): Linear(in_features=8, out_features=4608, bias=False)
)
transformer.h.5.attn.qkv_proj.lora_B.default Linear(in_features=8, out_features=4608, bias=False)
transformer.h.5.attn.qkv_proj.lora_embedding_A ParameterDict()
transformer.h.5.attn.qkv_proj.lora_embedding_B ParameterDict()
transformer.h.5.attn.qkv_proj.lora_magnitude_vector ModuleDict()
transformer.h.5.attn.out_proj lora.Linear(
  (base_layer): Linear(in_features=1536, out_features=1536, bias=False)
  (lora_dropout): ModuleDict(
    (default): Dropout(p=0.1, inplace=False)
  )
  (lora_A): ModuleDict(
    (default): Linear(in_features=1536, out_features=8, bias=False)
  )
  (lora_B): ModuleDict(
    (default): Linear(in_features=8, out_features=1536, bias=False)
  )
  (lora_embedding_A): ParameterDict()
  (lora_embedding_B): ParameterDict()
  (lora_magnitude_vector): ModuleDict()
)
transformer.h.5.attn.out_proj.base_layer Linear(in_features=1536, out_features=1536, bias=False)
transformer.h.5.attn.out_proj.lora_dropout ModuleDict(
  (default): Dropout(p=0.1, inplace=False)
)
transformer.h.5.attn.out_proj.lora_dropout.default Dropout(p=0.1, inplace=False)
transformer.h.5.attn.out_proj.lora_A ModuleDict(
  (default): Linear(in_features=1536, out_features=8, bias=False)
)
transformer.h.5.attn.out_proj.lora_A.default Linear(in_features=1536, out_features=8, bias=False)
transformer.h.5.attn.out_proj.lora_B ModuleDict(
  (default): Linear(in_features=8, out_features=1536, bias=False)
)
transformer.h.5.attn.out_proj.lora_B.default Linear(in_features=8, out_features=1536, bias=False)
transformer.h.5.attn.out_proj.lora_embedding_A ParameterDict()
transformer.h.5.attn.out_proj.lora_embedding_B ParameterDict()
transformer.h.5.attn.out_proj.lora_magnitude_vector ModuleDict()
transformer.h.6.attn.qkv_proj lora.Linear(
  (base_layer): Linear(in_features=1536, out_features=4608, bias=False)
  (lora_dropout): ModuleDict(
    (default): Dropout(p=0.1, inplace=False)
  )
  (lora_A): ModuleDict(
    (default): Linear(in_features=1536, out_features=8, bias=False)
  )
  (lora_B): ModuleDict(
    (default): Linear(in_features=8, out_features=4608, bias=False)
  )
  (lora_embedding_A): ParameterDict()
  (lora_embedding_B): ParameterDict()
  (lora_magnitude_vector): ModuleDict()
)
transformer.h.6.attn.qkv_proj.base_layer Linear(in_features=1536, out_features=4608, bias=False)
transformer.h.6.attn.qkv_proj.lora_dropout ModuleDict(
  (default): Dropout(p=0.1, inplace=False)
)
transformer.h.6.attn.qkv_proj.lora_dropout.default Dropout(p=0.1, inplace=False)
transformer.h.6.attn.qkv_proj.lora_A ModuleDict(
  (default): Linear(in_features=1536, out_features=8, bias=False)
)
transformer.h.6.attn.qkv_proj.lora_A.default Linear(in_features=1536, out_features=8, bias=False)
transformer.h.6.attn.qkv_proj.lora_B ModuleDict(
  (default): Linear(in_features=8, out_features=4608, bias=False)
)
transformer.h.6.attn.qkv_proj.lora_B.default Linear(in_features=8, out_features=4608, bias=False)
transformer.h.6.attn.qkv_proj.lora_embedding_A ParameterDict()
transformer.h.6.attn.qkv_proj.lora_embedding_B ParameterDict()
transformer.h.6.attn.qkv_proj.lora_magnitude_vector ModuleDict()
transformer.h.6.attn.out_proj lora.Linear(
  (base_layer): Linear(in_features=1536, out_features=1536, bias=False)
  (lora_dropout): ModuleDict(
    (default): Dropout(p=0.1, inplace=False)
  )
  (lora_A): ModuleDict(
    (default): Linear(in_features=1536, out_features=8, bias=False)
  )
  (lora_B): ModuleDict(
    (default): Linear(in_features=8, out_features=1536, bias=False)
  )
  (lora_embedding_A): ParameterDict()
  (lora_embedding_B): ParameterDict()
  (lora_magnitude_vector): ModuleDict()
)
transformer.h.6.attn.out_proj.base_layer Linear(in_features=1536, out_features=1536, bias=False)
transformer.h.6.attn.out_proj.lora_dropout ModuleDict(
  (default): Dropout(p=0.1, inplace=False)
)
transformer.h.6.attn.out_proj.lora_dropout.default Dropout(p=0.1, inplace=False)
transformer.h.6.attn.out_proj.lora_A ModuleDict(
  (default): Linear(in_features=1536, out_features=8, bias=False)
)
transformer.h.6.attn.out_proj.lora_A.default Linear(in_features=1536, out_features=8, bias=False)
transformer.h.6.attn.out_proj.lora_B ModuleDict(
  (default): Linear(in_features=8, out_features=1536, bias=False)
)
transformer.h.6.attn.out_proj.lora_B.default Linear(in_features=8, out_features=1536, bias=False)
transformer.h.6.attn.out_proj.lora_embedding_A ParameterDict()
transformer.h.6.attn.out_proj.lora_embedding_B ParameterDict()
transformer.h.6.attn.out_proj.lora_magnitude_vector ModuleDict()
transformer.h.7.attn.qkv_proj lora.Linear(
  (base_layer): Linear(in_features=1536, out_features=4608, bias=False)
  (lora_dropout): ModuleDict(
    (default): Dropout(p=0.1, inplace=False)
  )
  (lora_A): ModuleDict(
    (default): Linear(in_features=1536, out_features=8, bias=False)
  )
  (lora_B): ModuleDict(

Set device and optimizer

In [10]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
optimizer = torch.optim.AdamW(model.parameters(), lr=1e-2)
# optimizer = torch.optim.AdamW(
#     filter(lambda p: p.requires_grad, model.parameters()), lr=1e-2
# )

Load protein sequence and experimental data

In [11]:
protein_seq = 'EDGINLEEIREFAKNFKIRRLSLGLTQTQVGQALTATEGPAYSQSAICRFEKLDITPKSAQKLKPVLEKWLNEAELRNQEGQQNLMEFVG'
fitness_data = df_mutation

In [12]:
len(protein_seq)

90

Making experimental tensor

In [13]:
fitness_data.reset_index(drop=True, inplace=True)

positions = np.arange(len(protein_seq))
# amino_acids = ['L', 'A', 'G', 'V', 'S', 'E', 'R', 'T', 'I',
#                'D', 'P', 'K', 'Q', 'N', 'F', 'Y', 'M', 'H', 'W', 'C']

amino_acids = 'ACDEFGHIKLMNPQRSTVWY'
aa_token_ids = [tokenizer.convert_tokens_to_ids(aa) for aa in amino_acids]

Construct df2

In [14]:
positions_col = np.repeat(positions, len(amino_acids))
amino_acids_col = np.tile(list(amino_acids), len(positions))
df2 = pd.DataFrame({'real_position': positions_col, 'mut_aa': amino_acids_col})

In [15]:
df_merged = df2.merge(
    fitness_data,
    on=['real_position', 'mut_aa'],
    how='left')

Construct experimental tensor

In [16]:
fitness_list = df_merged['normalized_fitness'].tolist()
fitness_tensor = torch.tensor(fitness_list)
exp_tensor = fitness_tensor
seq_len = exp_tensor.shape[0]

Set up train, validate, test

In [17]:
all_indices = torch.randperm(seq_len)

num_train = int(seq_len * 0.5)
num_val   = int(seq_len * 0.25)
num_test  = seq_len - num_train - num_val

train_indices = all_indices[:num_train] # len 900
val_indices   = all_indices[num_train:num_train + num_val]
test_indices  = all_indices[num_train + num_val:]

Fine-tuning model

In [19]:
train_losses = []
val_losses = []
early_stop_count = 0


vocab_dict = tokenizer.get_vocab()
seq_list = list(protein_seq)
inputs = tokenizer(protein_seq, return_tensors="pt").to(device)

for epoch in range(10):
    model.train()
    outputs = model(**inputs)
    logits = outputs.logits.squeeze(0)  # (seq_len, vocab_size)


    # Compute LLR ----
    # wt_logits = torch.log_softmax(logits, dim=-1)
    # wt_logits = wt_logits[1:-1, :]

    wt_logits = torch.log_softmax(logits, dim=-1)
    # wt_logits = wt_logits[1:-1, :]

    residue_indices = torch.arange(len(protein_seq))


    # ignoring BOS token
    seq_indices = [vocab_dict[aa] for aa in seq_list]

    wt_norm_tensor = wt_logits[residue_indices, seq_indices].unsqueeze(-1)
    LLR_tensor = wt_logits - wt_norm_tensor
    # LLR_tensor_aa_only = LLR_tensor[:, 4:24]
    LLR_tensor_aa_only = LLR_tensor[:, aa_token_ids]

    #p sure i can delete this
    #before_flatten = torch.transpose(LLR_tensor_aa_only, 0, 1)

    #flatten the LLR_tensor
    flattened_LLR_tensor = LLR_tensor_aa_only.flatten()
    flattened_exp_tensor = exp_tensor.to(device)
    flattened_LLR_tensor = flattened_LLR_tensor.to(device)

    #to stack
    combined = torch.stack([flattened_LLR_tensor, flattened_exp_tensor], dim=0)

    ft_tensor = torch.transpose(combined, 0, 1)

    predicted_scores = []
    experimental_values = []

    train_tensor = ft_tensor[train_indices]

    #drop nan
    train_tensor = train_tensor[~torch.any(train_tensor.isnan(), dim=1)]

    num_samples = 20
    positions = train_tensor[torch.randperm(len(train_tensor))[:num_samples]]

    #Get columns
    # this may be wrong!!!!
    predicts = positions[:, 1] #LLR
    targets = positions[:, 0] #exp

# Compute loss with predicts and targets
    loss = listwise_ranking_loss(predicts, targets)
    loss.backward()
    for name, param in model.named_parameters():
        if param.requires_grad:
            print(name, param.grad.abs().mean())
    optimizer.step()
    optimizer.zero_grad()

    train_losses.append(loss.item())

    # ----------- VALIDATION (no backprop) -----------
    model.eval()
    with torch.no_grad():
      val_tensor = ft_tensor[val_indices]
      val_tensor = val_tensor [~torch.any(val_tensor.isnan(), dim=1)]

      num_samples = 20
      positions = val_tensor[torch.randperm(len(val_tensor))[:num_samples]]

      predicts = positions[:, 1] #LLR
      targets = positions[:, 0] #exp

      val_loss = listwise_ranking_loss(predicts, targets)
      val_losses.append(val_loss.item())


    print(f"Epoch {epoch+1} - Training Loss: {loss.item():.4f} | Validation Loss: {val_loss.item():.4f}")

    if val_loss.item() > loss.item():
        early_stop_count += 1
    else:
        early_stop_count = 0

    # if early_stop_count > 2:
    #     print("Validation loss exceeded training loss 3 times — early stopping.")
    #     break
    print(early_stop_count)

base_model.model.transformer.h.0.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.0.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.0.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.0.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.1.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.1.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.1.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.1.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.2.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.2.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.2.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.2.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.3.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.3.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.3.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.3.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.4.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.4.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.4.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.4.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.5.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.5.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.5.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.5.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.6.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.6.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.6.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.6.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.7.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.7.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.7.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.7.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.8.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.8.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.8.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.8.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.9.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.9.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.9.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.9.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.10.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.10.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.10.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.10.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.11.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.11.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.11.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.11.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.12.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.12.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.12.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.12.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.13.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.13.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.13.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.13.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.14.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.14.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.14.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.14.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.15.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.15.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.15.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.15.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.16.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.16.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.16.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.16.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.17.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.17.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.17.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.17.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.18.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.18.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.18.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.18.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.19.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.19.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.19.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.19.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.20.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.20.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.20.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.20.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.21.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.21.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.21.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.21.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.22.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.22.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.22.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.22.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.23.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.23.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.23.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.23.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.24.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.24.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.24.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.24.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.25.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.25.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.25.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.25.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.26.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.26.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.26.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.26.attn.out_proj.lora_B.default.weight tensor(0.)
Epoch 1 - Training Loss: 2.1555 | Validation Loss: 2.1394
0
base_model.model.transformer.h.0.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.0.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.0.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.0.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.1.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.1.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.1.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.1.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.2.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.2.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.2.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.2.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.3.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.3.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.3.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.3.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.4.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.4.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.4.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.4.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.5.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.5.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.5.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.5.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.6.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.6.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.6.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.6.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.7.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.7.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.7.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.7.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.8.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.8.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.8.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.8.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.9.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.9.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.9.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.9.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.10.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.10.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.10.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.10.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.11.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.11.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.11.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.11.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.12.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.12.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.12.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.12.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.13.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.13.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.13.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.13.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.14.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.14.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.14.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.14.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.15.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.15.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.15.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.15.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.16.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.16.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.16.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.16.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.17.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.17.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.17.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.17.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.18.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.18.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.18.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.18.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.19.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.19.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.19.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.19.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.20.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.20.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.20.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.20.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.21.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.21.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.21.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.21.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.22.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.22.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.22.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.22.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.23.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.23.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.23.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.23.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.24.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.24.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.24.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.24.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.25.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.25.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.25.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.25.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.26.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.26.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.26.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.26.attn.out_proj.lora_B.default.weight tensor(0.)
Epoch 2 - Training Loss: 2.0997 | Validation Loss: 2.1100
1
base_model.model.transformer.h.0.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.0.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.0.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.0.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.1.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.1.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.1.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.1.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.2.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.2.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.2.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.2.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.3.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.3.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.3.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.3.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.4.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.4.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.4.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.4.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.5.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.5.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.5.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.5.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.6.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.6.attn.qkv_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.6.attn.out_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.6.attn.out_proj.lora_B.default.weight tensor(0.)
base_model.model.transformer.h.7.attn.qkv_proj.lora_A.default.weight tensor(0.)
base_model.model.transformer.h.7.attn.qkv_proj.lora_B.default.weight tensor(0.)

In [20]:
type(model)

peft.peft_model.PeftModelForCausalLM

In [21]:
names = list(pg_dict.keys())

In [22]:
name = 'PAI1_HUMAN'
pg_dict[name]
# pg_dict['S22A1_HUMAN']

{'sequence': 'MQMSPALTCLVLGLALVFGEGSAVHHPPSYVAHLASDFGVRVFQQVAQASKDRNVVFSPYGVASVLAMLQLTTGGETQQQIQAAMGFKIDDKGMAPALRHLYKELMGPWNKDEISTTDAIFVQRDLKLVQGFMPHFFRLFRSTVKQVDFSEVERARFIINDWVKTHTKGMISNLLGKGAVDQLTRLVLVNALYFNGQWKTPFPDSSTHRRLFHKSDGSTVSVPMMAQTNKFNYTEFTTPDGHYYDILELPYHGDTLSMFIAAPYEKEVPLSALTNILSAQLISHWKGNMTRLPRLLVLPKFSLETEVDLRKPLENLGMTDMFRQFQADFTSLSDQEPLHVAQALQKVKIEVNESGTVASSSTAVIVSARMAPEEIIMDRPFLFVVRHNPTGTVLFMGQVMEP',
 'DMS': array([[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        ...,
        [-0.97824751,         nan,         nan, ..., -0.33072981,
         -0.83554036,         nan],
        [-1.0317919 ,         nan,  1.78156975, ..., -0.73628775,
                 nan,  1.07274511],
        [-2.3878408 ,         nan,  0.79816832, ...,  0.79816832,
                 nan,  0.18826575]], shape=(402, 20)),
 'log_probs': array([[-2.9446702, -4.2355714, -4.0394654, ..., -3.3115373, -4.789496 ,
         -4.861029 ],
        [-2.1612172, -4.6932836, -3.3918843, ..., -3.157288 , -4.6646657,
         -4.6483846],
        [-2.6067436, -3.9063804, -3.832505 , ..., -2.8375633, -3.922425 ,
         -4.183259 ],
        ...,
        [-2.5426254, -4.4798584, -4.1418457, ..., -2.4754715, -5.663742 ,
         -4.26503  ],
        [-2.7469769, -5.016859 , -1.9224988, ..., -3.7034664, -6.0563946,
         -4.2189083],
        [-3.0441766, -5.2747827, -4.615557 , ..., -3.354426 , -5.528628 ,
         -4.8173394]], shape=(402, 20), dtype=float32),
 'ref_log_probs': array([[-7.83560336e-01],
        [-3.51406908e+00],
        [-2.85047984e+00],
        [-2.58216667e+00],
        [-2.71811366e+00],
        [-2.45919776e+00],
        [-1.77750635e+00],
        [-3.02511358e+00],
        [-3.57474041e+00],
        [-1.24113405e+00],
        [-2.30165029e+00],
        [-1.02799308e+00],
        [-2.93727016e+00],
        [-9.87940311e-01],
        [-2.05648613e+00],
        [-1.69480228e+00],
        [-2.43997860e+00],
        [-3.90310860e+00],
        [-2.22272801e+00],
        [-2.77965117e+00],
        [-2.43657255e+00],
        [-2.28546071e+00],
        [-2.45576406e+00],
        [-2.86808109e+00],
        [-3.46250415e+00],
        [-3.09858847e+00],
        [-2.37776995e+00],
        [-2.46156120e+00],
        [-2.17976332e+00],
        [-4.41555309e+00],
        [-2.22829747e+00],
        [-1.82660460e+00],
        [-3.15431476e+00],
        [-2.26797295e+00],
        [-2.64851522e+00],
        [-1.97990227e+00],
        [-1.98953831e+00],
        [-9.30181146e-01],
        [-1.21265852e+00],
        [-1.91853225e+00],
        [-2.55314302e+00],
        [-1.92555046e+00],
        [-1.23633242e+00],
        [-2.12293839e+00],
        [-2.19334078e+00],
        [-1.54044342e+00],
        [-1.60739839e+00],
        [-2.43219995e+00],
        [-2.57177496e+00],
        [-1.70520222e+00],
        [-2.13207245e+00],
        [-1.47189879e+00],
        [-2.69491386e+00],
        [-2.41787151e-01],
        [-1.26852691e+00],
        [-1.18189347e+00],
        [-3.55223775e-01],
        [-3.24645303e-02],
        [-1.34963458e-02],
        [-6.99388087e-01],
        [-7.13643074e-01],
        [-8.49779665e-01],
        [-8.41200948e-01],
        [-2.93931127e-01],
        [-1.34776676e+00],
        [-2.12414682e-01],
        [-5.96647024e-01],
        [-3.60021085e-01],
        [-5.30456543e-01],
        [-1.42615271e+00],
        [-2.41104528e-01],
        [-4.72564650e+00],
        [-3.47613120e+00],
        [-1.48830569e+00],
        [-1.84325874e-01],
        [-1.52578115e+00],
        [-1.36378542e-01],
        [-2.23046684e+00],
        [-1.79041505e+00],
        [-7.18103170e-01],
        [-1.32924414e+00],
        [-1.83972323e+00],
        [-2.84924197e+00],
        [-1.26235485e+00],
        [-2.54786444e+00],
        [-9.25002635e-01],
        [-9.19200420e-01],
        [-2.35873079e+00],
        [-2.89929485e+00],
        [-1.68981934e+00],
        [-1.22815371e+00],
        [-3.03628969e+00],
        [-2.71442652e+00],
        [-3.17405915e+00],
        [-2.50842667e+00],
        [-1.85605037e+00],
        [-2.00278020e+00],
        [-1.11572146e+00],
        [-1.93437040e+00],
        [-3.57795286e+00],
        [-3.92299980e-01],
        [-2.54732823e+00],
        [-2.66406059e+00],
        [-2.43971777e+00],
        [-3.77519697e-01],
        [-3.81304598e+00],
        [-2.79580140e+00],
        [-2.33063459e+00],
        [-5.18369675e+00],
        [-2.44353819e+00],
        [-2.25732350e+00],
        [-2.36908388e+00],
        [-2.36781096e+00],
        [-1.55141234e+00],
        [-1.92216432e+00],
        [-3.33948159e+00],
        [-3.37960100e+00],
        [-3.00206757e+00],
        [-6.49038672e-01],
        [-1.44412947e+00],
        [-3.09750289e-01],
        [-8.94778907e-01],
        [-1.02300131e+00],
        [-1.87975752e+00],
        [-1.54890466e+00],
        [-7.52179146e-01],
        [-2.04523611e+00],
        [-1.10143518e+00],
        [-1.96180379e+00],
        [-2.41945648e+00],
        [-2.25073647e+00],
        [-3.06894451e-01],
        [-3.48239946e+00],
        [-3.62993574e+00],
        [-3.42963648e+00],
        [-3.51354694e+00],
        [-4.58587360e+00],
        [-2.21043444e+00],
        [-1.84608305e+00],
        [-5.08335412e-01],
        [-2.53731036e+00],
        [-1.47859311e+00],
        [-2.40567422e+00],
        [-4.34518754e-01],
        [-1.74137354e+00],
        [-2.00790191e+00],
        [-7.36798704e-01],
        [-3.65057826e-01],
        [-1.02946132e-01],
        [-1.79114211e+00],
        [-1.33078909e+00],
        [-3.96389866e+00],
        [-8.98174405e-01],
        [-2.63356185e+00],
        [-2.18957320e-01],
        [-8.90655160e-01],
        [-5.52498865e+00],
        [-1.89557683e+00],
        [-2.25216970e-01],
        [-2.02477910e-02],
        [-2.11590528e+00],
        [-1.36497006e-01],
        [-2.11444944e-01],
        [-1.73950863e+00],
        [-2.77269936e+00],
        [-1.70342410e+00],
        [-1.21905971e-02],
        [-1.96936691e+00],
        [-3.85589421e-01],
        [-2.56097150e+00],
        [-9.21420231e-02],
        [-2.57459235e+00],
        [-2.29860544e+00],
        [-4.02668446e-01],
        [-3.51514369e-01],
        [-3.48315501e+00],
        [-2.87182307e+00],
        [-6.29849136e-01],
        [-1.60825157e+00],
        [-7.22566724e-01],
        [-8.18772614e-01],
        [-3.32634449e+00],
        [-5.33657074e-01],
        [-1.00022584e-01],
        [-6.30143583e-01],
        [-1.94330856e-01],
        [-4.48942810e-01],
        [-5.53771146e-02],
        [-5.14090180e-01],
        [-5.24781160e-02],
        [-5.18342853e-02],
        [-2.13388252e+00],
        [-8.67205858e-02],
        [-2.30155084e-02],
        [-3.98393536e+00],
        [-1.56383529e-01],
        [-2.17271829e+00],
        [-5.38043492e-03],
        [-1.05304253e+00],
        [-1.34959412e+00],
        [-1.03923118e+00],
        [-7.94031024e-02],
        [-1.42493165e+00],
        [-3.21840906e+00],
        [-1.78876209e+00],
        [-2.43113685e+00],
        [-5.92175797e-02],
        [-2.78412247e+00],
        [-2.87153697e+00],
        [-1.22080171e+00],
        [-2.88363004e+00],
        [-8.18091817e-03],
        [-6.23428464e-01],
        [-2.12777758e+00],
        [-1.63288891e+00],
        [-4.40259218e-01],
        [-2.30585158e-01],
        [-5.15403390e-01],
        [-9.58644629e-01],
        [-2.87300885e-01],
        [-2.12654614e+00],
        [-8.05526450e-02],
        [-2.06947595e-01],
        [-7.30507746e-02],
        [-3.07016037e-02],
        [-4.24959373e+00],
        [-2.54259825e-01],
        [-1.46823347e+00],
        [-2.22584248e+00],
        [-4.66531247e-01],
        [-1.60677463e-01],
        [-1.82688963e+00],
        [-4.06034917e-01],
        [-2.02678108e+00],
        [-1.60396254e+00],
        [-4.83849823e-01],
        [-2.39882064e+00],
        [-1.48291862e+00],
        [-1.36127770e+00],
        [-1.88444293e+00],
        [-8.91391993e-01],
        [-2.70170331e+00],
        [-4.63233328e+00],
        [-1.30593801e+00],
        [-2.16716170e+00],
        [-1.46003938e+00],
        [-6.07861698e-01],
        [-8.72902349e-02],
        [-4.46545720e-01],
        [-4.25147079e-02],
        [-3.21377739e-02],
        [-2.99742079e+00],
        [-1.24173805e-01],
        [-1.72656596e+00],
        [-1.72494113e+00],
        [-3.68444324e-01],
        [-1.19020566e-01],
        [-4.40515012e-01],
        [-9.73498821e-01],
        [-6.19657218e-01],
        [-1.04450953e+00],
        [-1.22623360e+00],
        [-7.26475641e-02],
        [-2.26595592e+00],
        [-9.53929245e-01],
        [-3.69229287e-01],
        [-1.85479152e+00],
        [-4.94114995e-01],
        [-3.32677841e-01],
        [-4.80715811e-01],
        [-6.15130842e-01],
        [-3.14678884e+00],
        [-7.43245840e-01],
        [-2.20430899e+00],
        [-2.73573399e+00],
        [-4.03254986e+00],
        [-3.58192801e-01],
        [-1.13145435e+00],
        [-2.74449110e+00],
        [-2.27323318e+00],
        [-2.05911589e+00],
        [-1.67084408e+00],
        [-2.08302975e+00],
        [-4.19458389e+00],
        [-3.62431221e-02],
        [-2.37404919e+00],
        [-2.97853470e+00],
        [-2.06674814e+00],
        [-1.75975859e-01],
        [-1.59476030e+00],
        [-1.69860876e+00],
        [-2.56740236e+00],
        [-1.34438324e+00],
        [-8.88357937e-01],
        [-3.48784328e+00],
        [-1.17393994e+00],
        [-1.81890750e+00],
        [-3.80618155e-01],
        [-7.14816758e-03],
        [-3.56088489e-01],
        [-4.28724661e-02],
        [-3.58339667e-01],
        [-5.20406187e-01],
        [-5.50421298e-01],
        [-1.25862193e+00],
        [-1.30129111e+00],
        [-1.43492472e+00],
        [-8.08911681e-01],
        [-7.11338967e-02],
        [-2.51079726e+00],
        [-1.95622301e+00],
        [-1.10356295e+00],
        [-7.23233670e-02],
        [-1.90687716e+00],
        [-3.00515389e+00],
        [-7.10160375e-01],
        [-2.04357374e-02],
        [-9.23600197e-01],
        [-1.15193427e+00],
        [-3.19352716e-01],
        [-4.51388657e-01],
        [-6.27989918e-02],
        [-4.62974405e+00],
        [-3.41529274e+00],
        [-5.50909376e+00],
        [-2.07091141e+00],
        [-8.84242132e-02],
        [-1.99440986e-01],
        [-8.11685383e-01],
        [-1.98193288e+00],
        [-3.38173437e+00],
        [-1.47884440e+00],
        [-3.16104323e-01],
        [-2.60455227e+00],
        [-2.52091980e+00],
        [-1.01874459e+00],
        [-2.65722036e+00],
        [-4.20803934e-01],
        [-2.04596257e+00],
        [-4.65353966e-01],
        [-3.29124761e+00],
        [-1.74068785e+00],
        [-5.29802680e-01],
        [-3.00792962e-01],
        [-5.93188524e-01],
        [-1.17831990e-01],
        [-2.25126243e+00],
        [-4.94429201e-01],
        [-3.19183022e-01],
        [-1.40600801e-01],
        [-5.51174432e-02],
        [-6.38069808e-01],
        [-1.65781807e-02],
        [-2.63560295e+00],
        [-6.89283200e-03],
        [-1.84095547e-01],
        [-1.71112597e+00],
        [-3.53388488e-02],
        [-6.70720100e-01],
        [-2.38902688e+00],
        [-3.15767169e+00],
        [-8.68904293e-02],
        [-1.02616799e+00],
        [-9.02995288e-01],
        [-2.21765804e+00],
        [-1.70536339e+00],
        [-1.40922546e+00],
        [-1.05845606e+00],
        [-4.29697603e-01],
        [-1.09899914e+00],
        [-1.56521237e+00],
        [-5.30868709e-01],
        [-2.80424428e+00],
        [-1.54115212e+00],
        [-1.48403823e+00],
        [-2.00426197e+00],
        [-2.77953339e+00],
        [-4.05041099e-01],
        [-1.94295332e-01],
        [-8.19475204e-03],
        [-6.94338325e-03],
        [-2.93669343e-01],
        [-1.37383521e-01],
        [-1.91808903e+00],
        [-2.27210712e+00],
        [-1.80965066e-01],
        [-7.41451144e-01],
        [-4.55132455e-01],
        [-8.27169657e-01],
        [-2.89547533e-01],
        [-7.48162389e-01],
        [-1.07385325e+00],
        [-1.29213786e+00],
        [-7.62332007e-02],
        [-6.54919818e-02],
        [-1.54387879e+00],
        [-1.44111365e-01],
        [-1.60741293e+00],
        [-9.12171662e-01],
        [-2.80867767e+00],
        [-1.89533818e+00],
        [-6.13024354e-01]], dtype=float32),
 'llr_matrix': array([[-2.16111   , -3.452011  , -3.2559052 , ..., -2.527977  ,
         -4.0059357 , -4.077469  ],
        [ 1.3528519 , -1.1792145 ,  0.12218475, ...,  0.356781  ,
         -1.1505966 , -1.1343155 ],
        [ 0.24373627, -1.0559006 , -0.98202515, ...,  0.01291656,
         -1.0719452 , -1.3327792 ],
        ...,
        [ 0.26605225, -1.6711807 , -1.333168  , ...,  0.33320618,
         -2.8550644 , -1.4563522 ],
        [-0.8516387 , -3.121521  , -0.02716064, ..., -1.8081282 ,
         -4.1610565 , -2.3235703 ],
        [-2.4311523 , -4.6617584 , -4.002533  , ..., -2.7414017 ,
         -4.9156036 , -4.204315  ]], shape=(402, 20), dtype=float32),
 'spearman_DMS': (np.float64(0.3830853868977005),
  np.float64(2.2547049974804243e-186)),
 'log_probs_forward': array([[-4.5067906, -5.769936 , -5.2112813, ..., -4.834809 , -6.299134 ,
         -5.9919972],
        [-2.1301322, -4.7947745, -2.9586768, ..., -3.3726325, -4.944341 ,
         -4.1228385],
        [-2.7194018, -4.407253 , -3.028171 , ..., -3.008861 , -4.7052035,
         -3.856525 ],
        ...,
        [-2.9216714, -5.015635 , -5.717753 , ..., -2.5226846, -7.315188 ,
         -5.4696527],
        [-3.3735933, -6.1766253, -1.2610141, ..., -4.9904146, -8.072881 ,
         -5.053853 ],
        [-5.292247 , -8.416034 , -8.081813 , ..., -5.7846937, -8.722781 ,
         -7.8027143]], shape=(402, 20), dtype=float32),
 'ref_log_probs_forward': array([[-2.15538621e-01],
        [-3.48431921e+00],
        [-4.30253935e+00],
        [-2.55888605e+00],
        [-2.90815115e+00],
        [-2.56280398e+00],
        [-2.49144626e+00],
        [-2.91157937e+00],
        [-4.23103237e+00],
        [-1.97049022e+00],
        [-2.68238139e+00],
        [-1.32726121e+00],
        [-3.09182072e+00],
        [-9.39747155e-01],
        [-1.97735786e+00],
        [-1.32179904e+00],
        [-2.50296783e+00],
        [-3.57773685e+00],
        [-2.18886232e+00],
        [-3.02007294e+00],
        [-2.37577534e+00],
        [-2.29149270e+00],
        [-2.46305752e+00],
        [-2.76396203e+00],
        [-3.78193283e+00],
        [-3.23004007e+00],
        [-2.55667949e+00],
        [-2.54543710e+00],
        [-2.18850636e+00],
        [-4.32634735e+00],
        [-2.86161184e+00],
        [-2.82041025e+00],
        [-3.44260120e+00],
        [-2.17572927e+00],
        [-3.68910551e+00],
        [-2.41689682e+00],
        [-3.42617393e+00],
        [-3.72252727e+00],
        [-2.88781834e+00],
        [-3.12625170e+00],
        [-2.93673897e+00],
        [-2.50538754e+00],
        [-3.13985753e+00],
        [-2.84179306e+00],
        [-3.12247777e+00],
        [-2.41427445e+00],
        [-1.99267948e+00],
        [-2.56649923e+00],
        [-3.38144326e+00],
        [-1.75623643e+00],
        [-3.16874599e+00],
        [-1.99198210e+00],
        [-2.99838614e+00],
        [-1.21290898e+00],
        [-1.90355754e+00],
        [-1.14745438e+00],
        [-2.63277143e-01],
        [-3.34481858e-02],
        [-1.36635751e-02],
        [-5.84710479e-01],
        [-3.77936631e-01],
        [-5.77867985e-01],
        [-5.23355961e-01],
        [-3.39338839e-01],
        [-1.16102171e+00],
        [-1.88294590e-01],
        [-6.01582885e-01],
        [-3.01378727e-01],
        [-3.41170281e-01],
        [-9.47649360e-01],
        [-7.78087601e-02],
        [-4.79316473e+00],
        [-3.41285324e+00],
        [-6.08658493e-01],
        [-2.20254034e-01],
        [-1.18352139e+00],
        [-1.91975504e-01],
        [-2.31869411e+00],
        [-1.81358993e+00],
        [-4.38490361e-01],
        [-1.37492752e+00],
        [-1.65018511e+00],
        [-2.44009018e+00],
        [-1.16934538e+00],
        [-2.39831114e+00],
        [-1.27437937e+00],
        [-6.61655366e-01],
        [-2.71490383e+00],
        [-2.68355751e+00],
        [-1.21240842e+00],
        [-7.36630023e-01],
        [-3.62147951e+00],
        [-2.45675278e+00],
        [-3.54594040e+00],
        [-3.00686097e+00],
        [-2.93298006e+00],
        [-1.95965970e+00],
        [-8.77362609e-01],
        [-1.81133127e+00],
        [-3.53753090e+00],
        [-3.00322592e-01],
        [-3.04041696e+00],
        [-3.14106250e+00],
        [-2.18216395e+00],
        [-2.63527781e-01],
        [-3.28954244e+00],
        [-3.31599021e+00],
        [-2.26347971e+00],
        [-5.52586842e+00],
        [-2.58229637e+00],
        [-1.97998667e+00],
        [-1.99912143e+00],
        [-2.60683417e+00],
        [-1.32871211e+00],
        [-1.87137747e+00],
        [-4.92235041e+00],
        [-3.02132225e+00],
        [-3.16071367e+00],
        [-1.05213833e+00],
        [-1.02696109e+00],
        [-3.22102755e-01],
        [-7.33266115e-01],
        [-9.65614021e-01],
        [-2.27744412e+00],
        [-1.77929831e+00],
        [-6.99088395e-01],
        [-1.86690140e+00],
        [-1.28950834e+00],
        [-1.42430377e+00],
        [-2.48258924e+00],
        [-1.39452565e+00],
        [-1.07595026e-01],
        [-3.35901213e+00],
        [-4.08484745e+00],
        [-3.56856322e+00],
        [-3.48905325e+00],
        [-3.74486756e+00],
        [-2.37731695e+00],
        [-1.30293262e+00],
        [-9.01139200e-01],
        [-2.53255749e+00],
        [-1.10363674e+00],
        [-2.33663368e+00],
        [-3.41114670e-01],
        [-1.23992503e+00],
        [-2.16434860e+00],
        [-7.65300632e-01],
        [-2.02649370e-01],
        [-3.59210521e-02],
        [-2.12282729e+00],
        [-1.60206032e+00],
        [-3.46992612e+00],
        [-1.98115456e+00],
        [-2.46846128e+00],
        [-2.84762293e-01],
        [-2.85850286e+00],
        [-5.44998932e+00],
        [-1.43682992e+00],
        [-1.30367264e-01],
        [-9.58974063e-02],
        [-2.07414532e+00],
        [-3.54994357e-01],
        [-1.82904258e-01],
        [-1.36743164e+00],
        [-3.19050884e+00],
        [-1.12438476e+00],
        [-2.10034475e-02],
        [-2.49576306e+00],
        [-5.89469016e-01],
        [-2.33604264e+00],
        [-1.97778493e-01],
        [-2.27906752e+00],
        [-2.20540285e+00],
        [-6.76302314e-01],
        [-5.32265842e-01],
        [-3.15059566e+00],
        [-3.25139570e+00],
        [-1.20955420e+00],
        [-2.11933327e+00],
        [-6.07613504e-01],
        [-1.01132226e+00],
        [-3.12845397e+00],
        [-4.66098636e-01],
        [-1.06763445e-01],
        [-7.41641819e-01],
        [-2.24407703e-01],
        [-1.88133121e-01],
        [-6.65593594e-02],
        [-1.66863889e-01],
        [-4.31974456e-02],
        [-4.53925654e-02],
        [-2.00152373e+00],
        [-5.37769608e-02],
        [-2.37057470e-02],
        [-4.33083057e+00],
        [-2.59504348e-01],
        [-2.24747610e+00],
        [-7.81324878e-03],
        [-1.85151803e+00],
        [-1.88324368e+00],
        [-1.67112529e+00],
        [-9.41975880e-03],
        [-1.97582996e+00],
        [-3.41856647e+00],
        [-1.50704932e+00],
        [-2.38886929e+00],
        [-3.56628336e-02],
        [-2.39667940e+00],
        [-2.95442629e+00],
        [-1.40077925e+00],
        [-2.65981627e+00],
        [-2.69691609e-02],
        [-6.31145835e-01],
        [-1.63490939e+00],
        [-1.73488700e+00],
        [-6.13069773e-01],
        [-1.08727500e-01],
        [-3.56162906e-01],
        [-9.64131773e-01],
        [-3.15327048e-01],
        [-1.72761714e+00],

In [23]:
sequence = pg_dict[name]['sequence']

In [24]:
model.eval()

amino_acids = 'ACDEFGHIKLMNPQRSTVWY'
aa_token_ids = [tokenizer.convert_tokens_to_ids(aa) for aa in amino_acids]

input = tokenizer(sequence, return_tensors="pt").to(device)
outputs = model(**inputs)

prompt1 = "1"+sequence  # run it forwards
prompt2 = "2"+sequence[::-1]  # run it backwards

input_ids1 = torch.tensor(tokenizer.encode(prompt1)).unsqueeze(0).to(model.device)
with torch.no_grad():
    logits1 = model(input_ids1).logits
shift_logits1 = logits1[:, :-1, :]  # remove last entry

input_ids2 =  torch.tensor(tokenizer.encode(prompt2)).unsqueeze(0).to(model.device)
with torch.no_grad():
    logits2 = model(input_ids2).logits
shift_logits2 = logits2[:, :-1, :] # remove last entry

shift_logits2 = shift_logits2[:, torch.arange(shift_logits2.size(1) - 1, -1, -1), :]

input_ids = input_ids1[:, 1:]

# take averages of matrices, 2nd one in reverse order
# to simulate BERT output

logits = (shift_logits1 + shift_logits2)/2

log_probs = F.log_softmax(logits, dim = -1)
# n = log_probs.size(1)

ref_log_probs = log_probs[0, torch.arange(input_ids.size(1)), input_ids[0]]
ref_log_probs = ref_log_probs.unsqueeze(1)


llr_matrix = log_probs - ref_log_probs
llr_matrix = llr_matrix[0][:, aa_token_ids]
log_probs = log_probs[0][:, aa_token_ids]

In [29]:
model.print_trainable_parameters()

trainable params: 1,990,656 || all params: 766,794,272 || trainable%: 0.2596

In [26]:
type(model)

peft.peft_model.PeftModelForFeatureExtraction

In [25]:
with torch.no_grad():
    out_peft  = model(**inputs).logits
    out_base  = base_model(**inputs).logits

check_tensor = out_peft - out_base

In [26]:
check_tensor

tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])

In [27]:
loss.backward()
for name, param in model.named_parameters():
    if param.requires_grad:
        print(name, param.grad.abs().mean())

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.