In [23]:
import os
import gzip
import gc
import pickle

from io import StringIO
from google.cloud import storage
from dotenv import load_dotenv

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [24]:
load_dotenv()
cred_path = os.getenv('GOOGLE_APPLICATION_CREDENTIALS')

os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = cred_path

client = storage.Client()
bucket = client.bucket('domainome-data')
blob = bucket.blob('SupplementaryTable2.txt')

df = pd.read_csv(StringIO(blob.download_as_text()), sep='\t')

In [25]:
df.head()

,domain_ID,uniprot_ID,aa_seq,wt_aa,position,mut_aa,STOP,input_count_rep1,input_count_rep2,input_count_rep3,output_count_rep1,output_count_rep2,output_count_rep3,mean_input_count,fitness,fitness_sigma,normalized_fitness,normalized_fitness_sigma,quality_rank
0,A0A2R8Y422_PF00240_2,A0A2R8Y422,*IFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2.0,*,True,118.0,113.0,62.0,10.0,29.0,2.0,97.66667,0.030945,0.014885,-0.819050,0.208478,339
1,A0A2R8Y422_PF00240_2,A0A2R8Y422,AIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2.0,A,False,219.0,277.0,217.0,86.0,225.0,137.0,237.66670,0.069376,0.006673,-0.280790,0.093461,339
2,A0A2R8Y422_PF00240_2,A0A2R8Y422,CIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2.0,C,False,706.0,726.0,459.0,768.0,507.0,616.0,630.33330,0.082052,0.004141,-0.103250,0.057995,339
3,A0A2R8Y422_PF00240_2,A0A2R8Y422,DIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2.0,D,False,407.0,431.0,323.0,508.0,159.0,111.0,387.00000,0.071003,0.005162,-0.258003,0.072296,339
4,A0A2R8Y422_PF00240_2,A0A2R8Y422,EIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2.0,E,False,37.0,56.0,37.0,201.0,102.0,95.0,43.33333,0.116326,0.012085,0.376783,0.169263,339

In [26]:
df = df[['domain_ID','aa_seq','wt_aa','position','mut_aa','normalized_fitness']]

In [27]:
df

,domain_ID,aa_seq,wt_aa,position,mut_aa,normalized_fitness
0,A0A2R8Y422_PF00240_2,*IFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2.0,*,-0.819050
1,A0A2R8Y422_PF00240_2,AIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2.0,A,-0.280790
2,A0A2R8Y422_PF00240_2,CIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2.0,C,-0.103250
3,A0A2R8Y422_PF00240_2,DIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2.0,D,-0.258003
4,A0A2R8Y422_PF00240_2,EIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2.0,E,0.376783
...,...,...,...,...,...,...
602877,Q9Y6V0_PF05715_1058,TWPLCKTELNIGSKDPPNFNTCTECKNQVCNLCGFNPTPHLTEIQE...,C,1059.0,W,-0.903822
602878,Q9Y6V0_PF05715_1058,TYPLCKTELNIGSKDPPNFNTCTECKNQVCNLCGFNPTPHLTEIQE...,C,1059.0,Y,-1.149495
602879,Q9Y6V0_PF05715_1058,VCPLCKTELNIGSKDPPNFNTCTECKNQVCNLCGFNPTPHLTEIQE...,T,1058.0,V,-0.201507
602880,Q9Y6V0_PF05715_1058,WCPLCKTELNIGSKDPPNFNTCTECKNQVCNLCGFNPTPHLTEIQE...,T,1058.0,W,-0.515568
602881,Q9Y6V0_PF05715_1058,YCPLCKTELNIGSKDPPNFNTCTECKNQVCNLCGFNPTPHLTEIQE...,T,1058.0,Y,NaN

In [30]:
def restore_wt_seq(row):
    if pd.isna(row["position"]):
        return None

    # extract domain start
    domain_start = int(row["domain_ID"].split("_")[2])
    
    # convert to 0-based local index
    pos = int(row["position"]) - domain_start

    seq = row["aa_seq"]

    if pos < 0 or pos >= len(seq):
        return None

    return seq[:pos] + row["wt_aa"] + seq[pos+1:]

In [31]:
df_one = df.drop_duplicates(subset=["domain_ID"]).copy()

df_one["wt_seq"] = df_one.apply(restore_wt_seq, axis=1)

In [35]:
df_one.set_index('domain_ID', inplace=True)

In [36]:
df_one.head()

,aa_seq,wt_aa,position,mut_aa,normalized_fitness,wt_seq
domain_ID,,,,,,
A0A2R8Y422_PF00240_2,*IFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2.0,*,-0.819050,QIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...
A0PJY2_PF00096_289,*CKVCGKGFRQASTLCRHKIIH,V,289.0,*,NaN,VCKVCGKGFRQASTLCRHKIIH
A1X283_PF00018_155,*QYVVVANYQKQESSEISLSVGQVVDIIEKNESGWWFVSTAEEQGW...,E,155.0,*,NaN,EQYVVVANYQKQESSEISLSVGQVVDIIEKNESGWWFVSTAEEQGW...
A1X283_PF00018_222,*EEKYTVIYPYTARDQDEMNLERGAVVEVIQKNLEGWWKIRYQGKE...,E,222.0,*,-1.047782,EEEKYTVIYPYTARDQDEMNLERGAVVEVIQKNLEGWWKIRYQGKE...
A2RRE5_PF01846_267,*QQIATAKDKYEWLVSRIVKNHNENWLSVSRKMQASPEYQDYVYLE...,S,267.0,*,-0.984201,SQQIATAKDKYEWLVSRIVKNHNENWLSVSRKMQASPEYQDYVYLE...

In [33]:
len(df_one)

522

In [34]:
len(df['domain_ID'].unique())

522

In [37]:
aa_order = list("ACDEFGHIKLMNPQRSTVWY")

def build_dict(df):
    result = {}

    for domain_id, df_domain in df.groupby("domain_ID"):
        # get all positions that should exist
        # positions = sorted(df_domain["position"].dropna().unique())
        positions = df_domain["position"].dropna()
        min_pos, max_pos = int(positions.min()), int(positions.max())
        positions = list(range(min_pos, max_pos + 1))
        
        result[domain_id] = {}
        pos_lists = []

        for pos in positions:
            df_pos = df_domain[df_domain["position"] == pos]

            # map mut_aa -> fitness
            fitness_map = dict(zip(df_pos["mut_aa"], df_pos["normalized_fitness"]))

            # build ordered list, fill missing with NaN
            row = [fitness_map.get(aa, np.nan) for aa in aa_order]

            pos_lists.append(row)

        result[domain_id]['fitness'] = pos_lists
        result[domain_id]['uniprot_id'] = domain_id.split("_")[0]
        result[domain_id]['dom_seq'] = df_one.loc[domain_id]['wt_seq']

    return result

In [38]:
dict_fitness = build_dict(df)

In [41]:
dict_fitness.keys()

dict_keys(['A0A2R8Y422_PF00240_2', 'A0PJY2_PF00096_289', 'A1X283_PF00018_155', 'A1X283_PF00018_222', 'A2RRE5_PF01846_267', 'A6NK59_PF07525_532', 'EEHEE-rd3-0037_rockdoms_1', 'EHEE-rd1-0882_rockdoms_1', 'HHH-rd1-0142_rockdoms_1', 'O00308_PF00397_440', 'O00330_PF02817_181', 'O14529_PF02376_1036', 'O14529_PF02376_895', 'O14640_PF00595_246', 'O14640_PF00778_4', 'O14776_PF01846_645', 'O14776_PF01846_727', 'O14776_PF01846_793', 'O14776_PF01846_897', 'O14776_PF01846_955', 'O14813_PF00046_92', 'O14901_PF00096_395', 'O14936_PF00595_488', 'O15151_PF00641_299', 'O15259_PF00018_152', 'O15265_PF08313_334', 'O15266_PF00046_119', 'O15344_PF00643_172', 'O15350_PF07647_487', 'O15405_PF00505_256', 'O15541_PF00642_198', 'O43167_PF00096_351', 'O43167_PF00096_435', 'O43186_PF00046_41', 'O43295_PF00018_745', 'O43353_PF00619_438', 'O43374_PF00779_682', 'O43395_PF01480_10', 'O43586_PF00018_361', 'O60281_PF00096_808', 'O60293_PF10650_1186', 'O60341_PF04433_186', 'O60481_PF00096_389', 'O60885_PF17035_607', 'O75112_PF00595_1', 'O75360_PF00046_71', 'O75366_PF02209_785', 'O75369_PF00630_1423', 'O75369_PF00630_2109', 'O75369_PF00630_2289', 'O75382_PF00643_111', 'O75400_PF00397_176', 'O75400_PF01846_395', 'O75400_PF01846_459', 'O75400_PF01846_670', 'O75400_PF01846_745', 'O75478_PF04433_375', 'O75534_PF00313_184', 'O75534_PF00313_23', 'O75534_PF00313_347', 'O75554_PF06220_8', 'O75808_PF00641_4', 'O75953_PF00226_4', 'O75970_PF00595_1003', 'O75970_PF00595_1860', 'O75970_PF00595_372', 'O75970_PF00595_693', 'O94830_PF00536_389', 'O94885_PF00536_630', 'O94929_PF00412_149', 'O94929_PF00412_210', 'O94993_PF00505_338', 'O95076_PF00046_155', 'O95155_PF04564_1229', 'O95218_PF00641_11', 'O95218_PF00641_9', 'O95267_PF00130_539', 'O95343_PF00046_212', 'O95409_PF18366_250', 'O95475_PF00046_134', 'O95714_PF11515_2555', 'O95718_PF00105_100', 'O95789_PF06467_427', 'O95789_PF06467_469', 'O95793_PF00035_183', 'O95817_PF00397_11', 'O95835_PF00627_98', 'P00519_PF00018_64', 'P01053_PF00280_22', 'P02417_PF01281_1', 'P02549_PF00018_979', 'P02585_PF13499_1', 'P02633_PF01023_1', 'P02640_PF02209_762', 'P02640_PF02209_792', 'P03034_PF01381_4', 'P04049_PF02196_58', 'P04150_PF00105_419', 'P05813_PF00030_31', 'P06239_PF00018_63', 'P06241_PF00018_83', 'P07315_PF00030_4', 'P07315_PF00030_91', 'P07316_PF00030_1', 'P07316_PF00030_87', 'P07320_PF00030_90', 'P07751_PF00018_968', 'P07814_PF00458_827', 'P08151_PF00096_363', 'P08235_PF00105_600', 'P08631_PF00018_80', 'P09086_PF00157_200', 'P09327_PF02209_793', 'P0A9X9_PF00313_3', 'P0CI26_PF00643_87', 'P10070_PF00096_565', 'P10071_PF00096_608', 'P10242_PF00249_143', 'P10242_PF00249_40', 'P10275_PF00105_557', 'P10398_PF02196_21', 'P10589_PF00105_83', 'P10826_PF00105_85', 'P11182_PF02817_171', 'P11308_PF02198_117', 'P11844_PF00030_85', 'P11961_PF02817_126', 'P12081_PF00458_8', 'P12931_PF00018_87', 'P12956_PF02037_558', 'P13796_PF13499_13', 'P13984_PF02270_177', 'P14598_PF00018_157', 'P14653_PF00046_208', 'P14859_PF00157_285', 'P14921_PF02198_55', 'P15056_PF02196_153', 'P15498_PF00018_592', 'P15498_PF00018_782', 'P16157_PF00531_1405', 'P16885_PF00018_772', 'P16989_PF00313_84', 'P17480_PF00505_408', 'P19793_PF00105_132', 'P19873_PF00280_1', 'P19878_PF00018_241', 'P19878_PF00018_456', 'P19878_PF00564_353', 'P20264_PF00046_408', 'P20264_PF00157_320', 'P20265_PF00046_356', 'P20265_PF00157_262', 'P20929_PF14604_6609', 'P20936_PF00018_281', 'P22492_PF00538_44', 'P22681_PF00627_854', 'P22914_PF00030_96', 'P23759_PF00046_219', 'P25490_PF00096_384', 'P25685_PF00226_4', 'P26367_PF00046_213', 'P26651_PF00642_105', 'P28069_PF00157_130', 'P28360_PF00046_174', 'P32081_PF00313_1', 'P32243_PF00046_40', 'P35251_PF00533_405', 'P35548_PF00046_144', 'P35711_PF00505_557', 'P35712_PF00505_622', 'P35713_PF00505_87', 'P35716_PF00505_50', 'P36075_PF02845_9', 'P37275_PF00096_933', 'P39880_PF00046_1246', 'P39880_PF02376_548', 'P39880_PF02376_941', 'P39940_PF00397_324', 'P40040_PF02037_1', 'P41002_PF00646_28', 'P41016_PF00313_1', 'P41225_PF00505_140', 'P41229_PF00628_319', 'P42766_PF00831_9', 'P43320_PF00030_106', 'P43354_PF00105_260', 'P45973_PF00385_21', 'P46934_PF00397_836', 'P46937_PF00397_162', 'P46937_PF00397_165', 'P46937_PF00397_226', 'P47974_PF00642_193', 'P48431_PF00505_42', 'P49335_PF00046_280', 'P49792_PF00641_1414', 'P49792_PF00641_1478', 'P50539_PF00010_70', 'P51451_PF00018_59', 'P51508_PF00096_331', 'P51508_PF00096_555', 'P51532_PF07533_612', 'P51608_PF01429_91', 'P51687_PF00173_87', 'P53673_PF00030_14', 'P53674_PF00030_57', 'P53804_PF13639_1957', 'P54277_PF00505_572', 'P54727_PF00627_186', 'P54727_PF00627_361', 'P54821_PF00046_96', 'P55072_PF02359_26', 'P55265_PF02295_136', 'P55265_PF02295_296', 'P55895_PF13341_415', 'P56915_PF00046_162', 'P57071_PF00096_1085', 'P57073_PF00505_103', 'P60002_PF05129_3', 'P60321_PF05741_63', 'P61024_PF01111_1', 'P61086_PF00627_158', 'P61960_PF03671_4', 'P61978_PF00013_385', 'P62993_PF00018_159', 'P67809_PF00313_52', 'P78352_PF00595_157', 'P78352_PF00595_309', 'P78352_PF00595_60', 'P78424_PF00046_609', 'P78545_PF02198_50', 'P78563_PF00035_80', 'P82979_PF02037_3', 'P98175_PF00641_214', 'P98175_PF00641_216', 'Q00839_PF02037_6', 'Q00987_PF00641_299', 'Q01484_PF00531_3571', 'Q01543_PF02198_116', 'Q01826_PF02376_371', 'Q01826_PF02376_494', 'Q01826_PF16557_178', 'Q01851_PF00157_266', 'Q01860_PF00157_134', 'Q03052_PF00157_247', 'Q03164_PF02008_1148', 'Q03181_PF00105_71', 'Q05066_PF00505_61', 'Q05086_PF16558_30', 'Q05195_PF00010_58', 'Q05655_PF00130_228', 'Q06187_PF00018_215', 'Q06546_PF02198_172', 'Q06787_PF00013_217', 'Q06945_PF00505_60', 'Q08881_PF00018_172', 'Q09472_PF02172_567', 'Q12824_PF04855_181', 'Q12830_PF00628_2862', 'Q12837_PF00157_256', 'Q12873_PF00628_374', 'Q12899_PF00643_97', 'Q12929_PF00018_533', 'Q12929_PF18016_720', 'Q12955_PF00531_4094', 'Q12965_PF00018_1051', 'Q13009_PF00595_843', 'Q13148_PF18694_5', 'Q13158_PF01335_1', 'Q13163_PF00564_15', 'Q13263_PF00628_620', 'Q13368_PF00595_132', 'Q13424_PF00595_79', 'Q13472_PF06839_812', 'Q13472_PF06839_896', 'Q13501_PF00569_120', 'Q13501_PF16577_389', 'Q13526_PF00397_1', 'Q13642_PF00412_160', 'Q13642_PF00412_99', 'Q13813_PF13499_2327', 'Q14151_PF02037_27', 'Q14160_PF00595_857', 'Q14192_PF00412_38', 'Q14202_PF06467_350', 'Q14202_PF06467_405', 'Q14202_PF06467_589', 'Q14202_PF06467_629', 'Q14839_PF00385_623', 'Q14839_PF00628_365', 'Q14839_PF00628_444', 'Q14863_PF00157_139', 'Q14995_PF00105_103', 'Q14CM0_PF00595_75', 'Q14CS0_PF00789_256', 'Q15319_PF00157_185', 'Q15365_PF00013_278', 'Q15424_PF02037_26', 'Q15475_PF00046_131', 'Q15554_PF00249_489', 'Q15699_PF00046_134', 'Q15811_PF00018_1003', 'Q15811_PF00018_1156', 'Q15811_PF00018_909', 'Q15811_PF07653_1003', 'Q15911_PF00046_2147', 'Q15911_PF00046_2244', 'Q15911_PF00046_2643', 'Q15942_PF00412_504', 'Q16512_PF02185_129', 'Q1KMD3_PF02037_1', 'Q2Q1W2_PF00643_274', 'Q3SY89_PF08711_3', 'Q5F1R6_PF12171_315', 'Q5HYK7_PF00018_664', 'Q5K651_PF07647_4', 'Q5SQQ9_PF00046_102', 'Q5TCQ9_PF00397_287', 'Q5U5Q3_PF00013_325', 'Q5VTD9_PF00096_221', 'Q5VVJ2_PF00249_120', 'Q5VWI1_PF01846_448', 'Q61234_PF00595_80', 'Q68CP9_PF02257_523', 'Q68DC2_PF00536_774', 'Q6NWY9_PF01846_274', 'Q6P0N0_PF00249_878', 'Q6XZF7_PF00018_146', 'Q6XZF7_PF00018_1516', 'Q6XZF7_PF00018_242', 'Q6XZF7_PF14604_147', 'Q6ZN01_PF02037_170', 'Q6ZSG1_PF13639_293', 'Q6ZVD7_PF10264_112', 'Q6ZWJ1_PF00397_493', 'Q7L590_PF09329_383', 'Q7Z3T8_PF01363_744', 'Q7Z4I7_PF00412_13', 'Q7Z5Q1_PF16366_513', 'Q7Z6B7_PF00018_744', 'Q7Z6G8_PF00536_812', 'Q7Z6W7_PF00226_3', 'Q7Z6Z7_PF00627_1316', 'Q86U86_PF00505_1383', 'Q86UL8_PF00397_296', 'Q86UL8_PF00595_1144', 'Q86UL8_PF00595_601', 'Q86UL8_PF00595_774', 'Q86UP3_PF00046_2086', 'Q86UP3_PF00046_2183', 'Q86UP3_PF00046_2562', 'Q86VP1_PF18112_729', 'Q86WN1_PF14604_467', 'Q86XK2_PF02207_849', 'Q86XN8_PF00013_273', 'Q86YT6_PF18346_247', 'Q8IV48_PF02037_65', 'Q8IWR0_PF00642_906', 'Q8IWT3_PF01485_2234', 'Q8IWT3_PF11515_367', 'Q8IX12_PF02037_625', 'Q8IYH5_PF00249_653', 'Q8IZQ8_PF02037_363', 'Q8IZT6_PF00612_1877', 'Q8N157_PF00018_1053', 'Q8N1P7_PF00030_1358', 'Q8N1W1_PF00130_651', 'Q8N3X1_PF00397_200', 'Q8N3X1_PF00397_593', 'Q8N5C8_PF02845_12', 'Q8N8B7_PF08711_30', 'Q8NB78_PF07496_139', 'Q8ND56_PF12701_7', 'Q8NEA6_PF00096_414', 'Q8NEA6_PF00096_473', 'Q8NEZ5_PF00646_25', 'Q8NFW5_PF00046_73', 'Q8NHM5_PF16866_656', 'Q8TAQ2_PF00249_599', 'Q8TAT5_PF00641_316', 'Q8TDD2_PF00096_325', 'Q8TDI0_PF00628_338', 'Q8TDI0_PF00628_411', 'Q8TDI0_PF08073_132', 'Q8TEW0_PF00595_457', 'Q8TEW8_PF00595_380', 'Q8WU90_PF18044_104', 'Q8WWH4_PF07647_273', 'Q8WXI2_PF00536_9', 'Q8WXI9_PF00320_415', 'Q92734_PF00564_6', 'Q92796_PF00595_222', 'Q92796_PF00595_383', 'Q92922_PF00249_620', 'Q92945_PF00013_142', 'Q92997_PF00778_2', 'Q969G3_PF00505_67', 'Q969V6_PF02037_341', 'Q96AE4_PF00013_184', 'Q96AE4_PF00013_98', 'Q96CB8_PF00628_155', 'Q96DX7_PF00643_174', 'Q96FX2_PF05207_6', 'Q96GE6_PF13499_123', 'Q96GE6_PF13499_48', 'Q96GM8_PF00642_298', 'Q96I24_PF00013_75', 'Q96J02_PF00397_428', 'Q96J02_PF00397_474', 'Q96JN0_PF05225_353', 'Q96JY0_PF09011_3', 'Q96JY6_PF00412_284', 'Q96K80_PF00642_138', 'Q96KC8_PF00249_494', 'Q96L93_PF00787_1213', 'Q96PU5_PF00397_184', 'Q96PU5_PF00397_381', 'Q96PU5_PF00397_539', 'Q96QS3_PF00046_330', 'Q96QZ7_PF00397_294', 'Q96QZ7_PF00397_352', 'Q96RT1_PF00595_1321', 'Q96T51_PF01363_639', 'Q99501_PF02187_209', 'Q99543_PF00249_451', 'Q99615_PF00226_382', 'Q99684_PF00096_256', 'Q99684_PF00096_313', 'Q9BRP0_PF00096_215', 'Q9BTC0_PF00628_263', 'Q9BTC8_PF00249_265', 'Q9BUJ2_PF02037_1', 'Q9BV68_PF14369_11', 'Q9BY11_PF14604_387', 'Q9BYM8_PF01485_369', 'Q9BYW2_PF00397_2382', 'Q9BZM3_PF00046_204', 'Q9C030_PF00643_93', 'Q9C0A1_PF00046_1859', 'Q9GZV5_PF00397_116', 'Q9H000_PF00642_37', 'Q9H0A6_PF00612_189', 'Q9H0M0_PF00397_343', 'Q9H161_PF00046_216', 'Q9H2P0_PF00046_770', 'Q9H347_PF00627_613', 'Q9H3D4_PF07647_545', 'Q9H3Z4_PF00226_16', 'Q9H4A3_PF12202_481', 'Q9H6I2_PF00505_69', 'Q9H7E2_PF00567_554', 'Q9H9D4_PF00096_383', 'Q9H9L4_PF13891_28', 'Q9HA38_PF12171_246', 'Q9HAU4_PF00397_150', 'Q9HAZ2_PF00096_282', 'Q9HC78_PF00096_635', 'Q9HC78_PF00096_663', 'Q9HC78_PF00096_716', 'Q9NP66_PF00505_104', 'Q9NPB3_PF13499_155', 'Q9NPC8_PF00046_131', 'Q9NQ86_PF00643_208', 'Q9NQV8_PF00096_668', 'Q9NQX1_PF00096_433', 'Q9NSC2_PF00096_1030', 'Q9NU63_PF00096_176', 'Q9NUP7_PF11722_18', 'Q9NW38_PF11793_305', 'Q9NWH9_PF02037_19', 'Q9NYL2_PF00536_330', 'Q9NYS7_PF07525_369', 'Q9NZM3_PF14604_1129', 'Q9P0J7_PF05605_76', 'Q9P2D1_PF07533_2564', 'Q9P2F5_PF10264_64', 'Q9P2K3_PF00249_87', 'Q9P2P5_PF00397_800', 'Q9P2R6_PF00320_502', 'Q9UBF6_PF12678_48', 'Q9UBS4_PF00226_25', 'Q9UBW7_PF06467_463', 'Q9UBX0_PF00046_110', 'Q9UDY2_PF00595_26', 'Q9UDY2_PF00595_509', 'Q9UHA3_PF01246_2', 'Q9UHC7_PF00642_89', 'Q9UHD4_PF02017_36', 'Q9UIF8_PF00628_1927', 'Q9UJ78_PF06467_334', 'Q9UJQ4_PF00096_383', 'Q9UJQ4_PF00096_627', 'Q9UJQ4_PF00096_899', 'Q9UJV3_PF00643_191', 'Q9UKI9_PF00157_186', 'Q9UKL0_PF00249_383', 'Q9UKS6_PF14604_365', 'Q9UKW6_PF02198_47', 'Q9UKY1_PF18387_100', 'Q9UL15_PF02179_280', 'Q9ULJ8_PF07647_987', 'Q9ULL8_PF00595_7', 'Q9ULT8_PF18410_1892', 'Q9ULZ3_PF00619_114', 'Q9UNF0_PF00018_428', 'Q9UPQ7_PF00595_244', 'Q9UPQ7_PF00595_414', 'Q9UPW6_PF02376_358', 'Q9UPW6_PF02376_482', 'Q9UQR1_PF00096_172', 'Q9Y222_PF00249_226', 'Q9Y2G7_PF00096_411', 'Q9Y2T7_PF00313_86', 'Q9Y3R0_PF00595_666', 'Q9Y462_PF00096_506', 'Q9Y4I5_PF03638_368', 'Q9Y4J8_PF00569_235', 'Q9Y5K6_PF00018_271', 'Q9Y5K6_PF14604_1', 'Q9Y5K6_PF14604_109', 'Q9Y618_PF00249_613', 'Q9Y6N9_PF00595_207', 'Q9Y6V0_PF05715_1058'])

In [43]:
df[df['domain_ID']=='O14776_PF01846_955']

,domain_ID,aa_seq,wt_aa,position,mut_aa,normalized_fitness
22139,O14776_PF01846_955,*KKREHFRQLLDETSAITLTSTWKEVKKIIKEDPRCIKFSSSDRKK...,K,955.0,*,NaN
22140,O14776_PF01846_955,AKKREHFRQLLDETSAITLTSTWKEVKKIIKEDPRCIKFSSSDRKK...,K,955.0,A,-0.579791
22141,O14776_PF01846_955,CKKREHFRQLLDETSAITLTSTWKEVKKIIKEDPRCIKFSSSDRKK...,K,955.0,C,NaN
22142,O14776_PF01846_955,DKKREHFRQLLDETSAITLTSTWKEVKKIIKEDPRCIKFSSSDRKK...,K,955.0,D,NaN
22143,O14776_PF01846_955,EKKREHFRQLLDETSAITLTSTWKEVKKIIKEDPRCIKFSSSDRKK...,K,955.0,E,-0.182228
...,...,...,...,...,...,...
23255,O14776_PF01846_955,SKKREHFRQLLDETSAITLTSTWKEVKKIIKEDPRCIKFSSSDRKK...,K,955.0,S,-0.223652
23256,O14776_PF01846_955,TKKREHFRQLLDETSAITLTSTWKEVKKIIKEDPRCIKFSSSDRKK...,K,955.0,T,-0.928017
23257,O14776_PF01846_955,VKKREHFRQLLDETSAITLTSTWKEVKKIIKEDPRCIKFSSSDRKK...,K,955.0,V,0.277028
23258,O14776_PF01846_955,WKKREHFRQLLDETSAITLTSTWKEVKKIIKEDPRCIKFSSSDRKK...,K,955.0,W,-0.397834
23259,O14776_PF01846_955,YKKREHFRQLLDETSAITLTSTWKEVKKIIKEDPRCIKFSSSDRKK...,K,955.0,Y,NaN

In [42]:
dict_fitness['O14776_PF01846_955']

{'fitness': [[-0.579790665196086,
   nan,
   nan,
   -0.182227612872974,
   nan,
   0.244230579632941,
   nan,
   nan,
   nan,
   -1.26874301459624,
   -0.223897056418318,
   nan,
   nan,
   -0.338761128239441,
   -0.462575583453117,
   -0.223652389693654,
   -0.928016549748226,
   0.2770281949883,
   -0.397833822286963,
   nan],
  [-0.312306027208061,
   0.374955437822491,
   0.181349594827608,
   0.0568199599572219,
   -0.0684428568037957,
   -0.144464654088651,
   -0.640025403443257,
   -0.51150238211901,
   nan,
   -0.408511601852644,
   -0.333376823730116,
   -0.0403659181527373,
   -0.591278381631574,
   -0.0367703810685465,
   -0.335098491919724,
   0.185827241373965,
   -0.623962664741562,
   -0.430457143286625,
   -0.95862591174206,
   -0.374812238234478],
  [-0.483019574921351,
   -0.803478650215903,
   -0.159061192665754,
   -0.303772150045789,
   -0.34633761387042,
   -0.338731670038478,
   -0.0609261058581026,
   -0.327691390944282,
   nan,
   -0.206544539484465,
   -0.744562002805149,
   -0.388750876990077,
   -0.539508539259421,
   -0.263456147178016,
   -0.326209479779177,
   -0.244928575339089,
   -0.741097718371915,
   -0.377466749454576,
   -0.899339973050901,
   0.0842365439366958],
  [-0.123677801892543,
   nan,
   -0.129967946081477,
   -0.193701582148013,
   -0.445881784624129,
   -0.355964717601759,
   -0.0005482498512535,
   -0.780105367975256,
   -0.0904833191075453,
   -0.69304255514118,
   -0.636256308458393,
   -0.677940399275883,
   -0.440396831261514,
   -0.338761128239441,
   nan,
   -0.283542548817895,
   -0.440396831261514,
   -0.296486155007638,
   0.0125148257090605,
   -0.229971992083551],
  [nan,
   nan,
   nan,
   nan,
   nan,
   nan,
   nan,
   nan,
   nan,
   nan,
   nan,
   nan,
   nan,
   nan,
   nan,
   nan,
   nan,
   nan,
   nan,
   nan],
  [0.307732641508575,
   -0.140310229469525,
   0.350827534667178,
   0.309586053319155,
   -0.324025481491124,
   -0.106619866968319,
   nan,
   -0.493680170536471,
   -0.109676973601577,
   0.183367481593565,
   0.161178910001641,
   0.220551914042311,
   -0.773572602770059,
   0.274938299286656,
   -0.262973359995569,
   0.0963438645324367,
   -0.189634713848416,
   -0.221064159425722,
   -0.559821196248362,
   -0.0938587379678746],
  [-0.799784346330151,
   -0.740029449445331,
   -0.440396831261514,
   -0.47941830985364,
   nan,
   -0.587878250613771,
   -0.823713324800629,
   -0.521685918535203,
   -0.667054366595061,
   -0.708190862187986,
   -0.627165916782931,
   -0.552655570692479,
   -0.950925456182029,
   -0.519594386266839,
   -0.811480970507468,
   -0.546191786774537,
   -0.298078534426353,
   -0.892118704226533,
   -0.924808388006697,
   -0.254901812931742],
  [-0.443612684866628,
   -0.735863650687501,
   -0.660386339150443,
   -0.578685573518298,
   -0.747910909284612,
   -0.616304596259584,
   -0.312248747372855,
   -0.487370387546896,
   -0.520028894731041,
   -0.537785725473109,
   -0.756914562923906,
   -0.419349764956901,
   -0.935391983157634,
   -0.855518444268547,
   nan,
   -0.771528449108243,
   -0.811294729214714,
   -0.641269603292258,
   -0.166755511100585,
   0.355114521190636],
  [-0.199192263494148,
   -0.717501044773966,
   -0.26441681184275,
   -0.258508805982974,
   -0.848042280177514,
   -0.817244631182526,
   -0.542942629036668,
   -0.680499007686181,
   -0.264781766221346,
   -0.911272999290945,
   -0.666944716624811,
   -0.22504265312243,
   -0.804661069671219,
   nan,
   -0.603197988024513,
   -0.389157563820037,
   -0.330416274533347,
   -0.827575213118526,
   -1.17637741464117,
   -0.854668002372416],
  [-0.751158348627424,
   -0.655742908395334,
   -0.427157006495423,
   -0.683041741399293,
   -0.653357776057373,
   -0.596095206630684,
   -0.650005514616134,
   -0.864341911911952,
   -0.521685918535203,
   nan,
   -0.321306325885579,
   -0.581990210867981,
   -0.585120553861966,
   -0.929871188983847,
   -1.0160726767531,
   -0.544866822357896,
   -0.605210474120293,
   -0.734224301803917,
   -0.886320102851999,
   -0.617478914709634],
  [-0.771427227456601,
   -0.787303806693878,
   -0.35361788092505,
   -1.04342895324894,
   -0.961552338522713,
   -0.84938991104323,
   -0.673510458649419,
   -1.02742185781573,
   -0.833599497043769,
   nan,
   -0.717545150247074,
   -0.706057270154913,
   -0.863922541689911,
   -0.644092026257846,
   -0.941385499628538,
   -0.713183618109513,
   -0.710253672710411,
   -0.719900415242392,
   -0.999169970182286,
   -1.05497894104813],
  [-0.352558203973747,
   -0.584045984153509,
   nan,
   -0.0536368376865115,
   -0.742444858267615,
   -0.61268410153291,
   -0.941289842303745,
   nan,
   -0.884388463152195,
   -0.627741824611755,
   -0.422467424558805,
   -0.387155224437921,
   -0.574290655419646,
   -0.391024068164379,
   -0.461712294508233,
   -0.267982890725978,
   -0.486983339517578,
   -0.604232707333334,
   -0.8948599534828,
   -0.813812014315327],
  [-0.454103077542851,
   -0.734589828980864,
   -0.540263651144103,
   nan,
   -0.663218827001359,
   -0.964036483147244,
   nan,
   -0.896254390156712,
   -0.729436771349098,
   -0.458514443137041,
   -0.334607521903676,
   -0.677940399275883,
   -0.668917679634299,
   -0.655803706848988,
   -1.00086168920092,
   -0.918618074387694,
   -0.586332267861572,
   -0.773586186273836,
   -0.317301647121348,
   nan],
  [-0.419550244380121,
   -0.0888532986542665,
   -0.754265452373984,
   -0.712954580597026,
   0.187824671055919,
   -0.909136543266113,
   -0.576199792327048,
   -0.0433804740512712,
   -0.674990569591131,
   -0.362419336746069,
   -0.325739785130491,
   -0.315089827199052,
   -1.02589706860256,
   -0.262304822490384,
   -0.964586451393553,
   -0.800538312618129,
   nan,
   -0.171293710615587,
   -0.976027771162525,
   -0.630439704849938],
  [-0.065236822599003,
   -0.238471501344699,
   -0.085085922064459,
   -0.0744302361494997,
   -0.494729209804094,
   -0.10918845843561,
   -0.585280528258861,
   -0.277315412447688,
   0.0093546153724322,
   -0.301252655580103,
   -0.798490640337865,
   -0.368519639195464,
   -0.385540751368484,
   -0.0892125250493414,
   -0.327843591649256,
   nan,
   -0.0102203591673968,
   -0.189758274635788,
   -0.618642759132676,
   -0.117585682276749],
  [nan,
   0.0107677907352901,
   0.004338538375143,
   -0.0645126418253322,
   -0.372263285567829,
   0.158494122297219,
   0.424477128491161,
   -0.497374719907232,
   -0.245381904320574,
   -0.390303160524148,
   0.143193860030446,
   -0.243446664173985,
   -0.5400279855364,
   -0.354445165402091,
   -0.555376117379737,
   0.0850785575142181,
   -0.287210913121133,
   -0.455785468131175,
   -0.325968086187953,
   -0.427214286330628],
  [-0.67688276803298,
   -0.39411226956532,
   -0.816960686856579,
   -1.007166726147,
   -0.816491974147925,
   -0.690633528929105,
   -0.640025403443257,
   nan,
   -0.590607307447973,
   -0.378745726346381,
   -0.635233454258294,
   -1.02797452639713,
   -0.579126710077717,
   -0.865396760991431,
   -0.978416422118934,
   -0.835128132188734,
   -0.601462981816136,
   -0.135398892742326,
   -0.83081872470121,
   -0.896706246228149],
  [-0.646027511889443,
   -0.363554295766499,
   -0.142211101714991,
   -0.0616421037981724,
   nan,
   -0.313580912683065,
   0.22401898063897,
   -0.800383820719746,
   -0.824232280107592,
   -0.252395410999818,
   -0.652006381088202,
   -0.302062756106582,
   -0.64253982455211,
   -0.192898846171774,
   -0.710443841763293,
   -0.0518235217605747,
   nan,
   -0.75220362379159,
   -0.984390136132525,
   -0.397833822286963],
  [0.131333661009449,
   -0.171888602618365,
   -0.107145204885491,
   0.18793513930953,
   -0.34530984997016,
   -0.244564439243854,
   -0.485278855278532,
   -0.190565102028827,
   -0.450845491486373,
   nan,
   -0.158625047634832,
   -0.36335790776008,
   0.0282037725718708,
   -0.0271899194887321,
   -0.334100186220427,
   -0.105811403008561,
   -0.505607468792995,
   -0.0217720653616437,
   -0.405551052655876,
   -0.380439572901746],
  [-0.37657727544217,
   -0.381528708054013,
   0.0302142947875868,
   -0.268021350043902,
   -0.333428375581801,
   -0.182432183712994,
   -0.217720653616436,
   -0.528927726271909,
   -0.249711441578756,
   -0.32070816074936,
   -0.18926648633638,
   -0.048688678208109,
   -0.36520150017034,
   -0.450737478082843,
   -0.371976886391801,
   -0.0788898804619346,
   nan,
   -0.61899503011919,
   -0.501802451168623,
   -0.481267630247421],
  [-0.533078468615914,
   -0.657497389747681,
   -0.776223922685053,
   -0.809764539331365,
   -0.854668002372416,
   -0.625407507670455,
   nan,
   -0.5288377151023,
   -0.809701040542622,
   -0.906850177729714,
   -0.456046500523041,
   -0.245292711434325,
   -0.731921570600316,
   -0.730468708494494,
   -0.933266164816482,
   nan,
   -0.075212515041736,
   -1.10522072107367,
   -1.01569692103415,
   -0.673598342282292],
  [-0.420939689525537,
   -0.576889441542923,
   -0.101315754228282,
   -0.237185978186014,
   -0.866120368966749,
   -0.717745056871941,
   -0.4925378469658,
   -1.00006729971495,
   -0.444126566816758,
   -0.575097482812684,
   -0.797803282315398,
   -0.0398233962850042,
   -0.582123509227338,
   -0.300989168338157,
   -0.689650525128641,
   -0.0793923064450237,
   nan,
   -0.629304745829507,
   -0.315296034605793,
   -0.978768611277112],
  [-0.719341691364129,
   -0.694626015271271,
   -0.673373150701598,
   -0.266485432177032,
   -0.521685918535203,
   -0.403842477000029,
   0.144221623930707,
   -0.440396831261514,
   -0.302183862043874,
   -0.96030961158376,
   -0.966823228958331,
   -0.282269299909611,
   -0.325818340333059,
   -0.29024919923711,
   -0.643957418645113,
   -0.591460858820872,
   -0.328654510459095,
   -0.597416979742221,
   nan,
   -0.718914383793495],
  [0.134784361938906,
   -0.316363894390697,
   -0.217075028045332,
   0.345282846619277,
   -0.387093034902555,
   -0.1712217016799,
   -0.0053982153264466,
   -0.167699810098117,
   nan,
   -0.0908294529688591,
   -0.0698625784335341,
   -0.0715212388044159,
   -0.175189557692927,
   0.0646910275978295,
   -0.383918913748806,
   0.0972848903965285,
   -0.281550847119461,
   -0.127659568722691,
   0.19982561481485,
   -0.151955219966821],
  [-0.676522559697873,
   -0.481837973749396,
   -0.204561838902992,
   nan,
   -0.886102684963226,
   -0.967012743384526,
   nan,
   -0.958046976264803,
   -0.808182552111322,
   -0.938501214440929,
   -0.796492228715878,
   -0.92742304882716,
   nan,
   -0.579028025104492,
   -0.972079635778476,
   -0.62606786234204,
   -0.757124698090774,
   -0.799290021352327,
   -0.509222644677827,
   -0.769616366380745],
  [-0.420525638145336,
   -0.500036595677571,
   -0.446178821483838,
   -0.756448632378676,
   -0.875075989372807,
   -0.566831102480822,
   -0.764181410131431,
   0.190432540124494,
   -0.840970920864712,
   -0.930764099786366,
   -0.175781176562265,
   nan,
   -0.896785374229068,
   -0.650888033219981,
   -0.822335908420607,
   -0.76426135641571,
   -0.503150163862675,
   nan,
   -1.00525447976283,
   -0.520911004193207],
  [-0.536605597211202,
   -0.32633958683343,
   -0.401926875654082,
   -0.227996656052318,
   0.117584863993389,
   -0.75944084914148,
   -0.530918118716967,
   -0.62783069018466,
   nan,
   -0.393307897022361,
   -0.773190137127557,
   -0.838803288243861,
   -0.378722814412299,
   -0.581172500306253,
   -0.138131140881633,
   -0.574239512709641,
   -0.505242514414399,
   -0.566524164392456,
   -0.492624585001968,
   0.0051240904008197],
  [-0.0346133861313761,
   -0.0605226921615833,
   -0.100788779744391,
   0.316893323724668,
   -0.518012644531805,
   -0.143166038396204,
   -0.184716012570976,
   -0.474641171597494,
   nan,
   -0.0259289448308492,
   -0.342776444687353,
   0.158215087671431,
   0.0671548787950298,
   0.162662457733465,
   -0.778896763452418,
   -0.0261343339542292,
   -0.402980824621865,
   -0.377931534403102,
   -0.47654613525976,
   -0.724166044570152],
  [-0.431340071032151,
   -0.27599879452132,
   -0.211332315424293,
   -0.238245655137317,
   -0.468963103361901,
   -0.56551620294951,
   -0.374981622890014,
   nan,
   -0.449589426528651,
   0.100023684802716,
   -0.0730677943549667,
   -0.140578626411632,
   -0.346088037445596,
   -0.346402258255867,
   -0.290438222693288,
   -0.327274884714001,
   -0.30491611018318,
   -0.124480537868781,
   -0.165559180828148,
   0.0098071260705564],
  [-0.862133528779768,
   -0.560318467046283,
   -0.30521969330977,
   -0.338201422421147,
   -0.542200036887396,
   -0.854384876329829,
   -0.632149507930825,
   nan,
   -0.714359082156267,
   -0.859535642768187,
   -0.838558539690861,
   -0.508396996767507,
   0.110616362898949,
   nan,
   -0.92715555199675,
   -0.804092690049307,
   -0.733820315309045,
   -0.317204271401499,
   -0.518195121721102,
   -1.02213746570467],
  [0.297476277873334,
   0.166785787584907,
   -0.155108884036569,
   0.311334724859646,
   -0.33239652026474,
   0.27067095156384,
   -0.0295866714504057,
   -0.406001108503919,
   nan,
   -0.4785992082102,
   -0.0615725497125656,
   0.0113692290049488,
   -0.674441992426534,
   -0.0408487053351844,
   -0.0401457999288758,
   0.0510862484531427,
   -0.204910427614386,
   -0.462060883219627,
   -0.265618051815347,
   -0.29968318809547],
  [-0.30953204661739,
   -0.532294880470301,
   0.038839001402828,
   nan,
   -0.442991607796327,
   -0.166163892231247,
   -0.166673682764577,
   -0.758832619119933,
   -0.63427033474348,
   -0.36786583079076,
   0.0345201018283268,
   -0.640025403443257,
   -1.0381257406206,
   -0.558343212843386,
   -0.43666709570627,
   -0.180665509938581,
   0.260641252419342,
   -0.924111210583909,
   -0.395699739283875,
   nan],
  [-0.0719819323361409,
   -0.596283657288511,
   nan,
   -0.196928891720168,
   0.154786480392697,
   -0.708727574243862,
   -1.24501968709982,
   -0.350894633902705,
   nan,
   0.161828626989544,
   0.0980794435391662,
   -1.22379038909091,
   -0.909179503142517,
   -0.590472372521896,
   -0.997445356172582,
   -0.850594342320931,
   -0.717545150247074,
   -0.0786083909860672,
   -0.031024395314066,
   -0.699308805455999],
  [-0.354272507613114,
   -0.661319836807622,
   0.275030765306345,
   0.0530002132323692,
   -0.320143545230905,
   -0.658761883024013,
   -0.677940399275883,
   -0.132720651304785,
   -0.460500416851955,
   -0.414135663386473,
   -0.359924390781185,
   nan,
   nan,
   -0.55764660821895,
   -0.644121320802137,
   -0.459415373116489,
   -0.0467935339461641,
   -0.52155253834751,
   -0.488394060030356,
   -0.652274205231956],
  [-0.853300405392715,
   -0.801810170444701,
   -0.570501757977468,
   -0.460253295277211,
   -0.812000007642767,
   -0.698804497421182,
   nan,
   -0.657330950912241,
   -0.7673989821316,
   -0.97220213279748,
   -0.608114070795201,
   -0.192292498201955,
   -0.535689365332921,
   -1.03201668253925,
   nan,
   -0.749661544705166,
   -0.91566562619619,
   -0.758449826164088,
   -1.00973818160605,
   -0.826663481798725],
  [-0.433467607768358,
   nan,
   -0.356170925008499,
   -0.429566850990858,
   0.29261812956454,
   -0.560945926726792,
   -0.708296175256428,
   -0.524724204651179,
   -0.916430230167848,
   -0.864811688388974,
   -0.694044624943934,
   -0.559347573839548,
   -0.60784002769791,
   -0.642486145163689,
   -1.01340556396926,
   -0.44671316051797,
   -0.62969744001401,
   -0.664646731464698,
   -0.74362400458949,
   0.316235423903164],
  [-0.152406094098225,
   -0.488565899535972,
   -0.236564901115714,
   -0.0763032867607224,
   -0.802935146408139,
   -0.751785317337918,
   -0.187047301863844,
   nan,
   0.0067819324883414,
   -0.324770937632157,
   -0.0961883906940219,
   -0.296055737960236,
   -0.268463223058345,
   -0.516443995330532,
   -0.434933971549621,
   -0.366112249550109,
   -0.331630607039706,
   -0.151659819673832,
   -0.405807175347581,
   -0.231237876441594],
  [0.244281313201266,
   -0.159985852862644,
   0.0029188167454045,
   0.222293221032561,
   -0.247422703020612,
   -0.0567962297397796,
   -0.204711584757887,
   -0.440396831261514,
   nan,
   -0.181257947091279,
   0.0971294165581134,
   0.302405616834455,
   -0.853394098837444,
   0.176513540169536,
   -0.0703960991843063,
   0.0476846445252908,
   -0.205419399864356,
   -0.270701228048163,
   -0.351908486985843,
   -0.13379914877337],
  [-0.55339799918508,
   -0.603398140134389,
   -0.49674709657005,
   -0.440036786583079,
   nan,
   -0.778414958210003,
   -0.595202623141509,
   -0.651473433135782,
   -0.965527231772637,
   -0.802023251431666,
   -0.540980303710861,
   -0.516448905030692,
   -0.779396079958739,
   -0.558759064446979,
   -0.877617986630895,
   -0.679111935562509,
   -0.671877737861052,
   -0.673391807562207,
   -0.763316320963154,
   -0.261221415321638],
  [-0.229479385500782,
   -0.35494431825174,
   -0.241466418442592,
   -0.378143469793362,
   -0.712432597641631,
   -0.32316873881312,
   -0.355733961694217,
   -0.90980156215285,
   -0.789645570013754,
   -0.872449217958615,
   -0.831630461794409,
   -0.471203563201799,
   -0.654298065466441,
   -0.610150859906775,
   -0.770152587466605,
   nan,
   -0.420024030445607,
   -0.717781552309801,
   -0.666256458490647,
   -0.819779263890373],
  [-0.110790657254646,
   -0.313021206864771,
   -0.0557586464391986,
   -0.170463153005106,
   -0.48874346702511,
   -0.313246234788793,
   0.126258667610235,
   -0.397550696244375,
   0.210504212663892,
   -0.304782729995487,
   -0.232613410769888,
   -0.283778214425598,
   -0.226909157466772,
   -0.4189234393263,
   -0.0039539451959057,
   nan,
   -0.18751863307925,
   -0.0304106827940062,
   -0.242936055357295,
   -0.353058993390116],
  [-0.0153976379866219,
   nan,
   nan,
   nan,
   -0.5288377151023,
   -0.440396831261514,
   nan,
   nan,
   nan,
   -0.637906131368986,
   -0.397833822286963,
   nan,
   -0.440396831261514,
   nan,
   nan,
   nan,
   nan,
   0.116210147948454,
   -0.640025403443257,
   -0.0374970166922974],
  [-0.882098906310692,
   -0.847746716227853,
   nan,
   -0.177718871558934,
   -0.641488248606072,
   -0.86464860451531,
   -0.653583049466403,
   0.0323189195897122,
   -0.636256308458393,
   -0.246754165515427,
   -0.687450815800075,
   -0.82119841272176,
   -0.806241583981213,
   -0.375378490319653,
   -1.1017593006322,
   -0.839365121598892,
   nan,
   -0.190466908025617,
   -0.459188708625747,
   -1.04969594001878],
  [0.145349218400897,
   -0.12723897107561,
   -0.176705018475795,
   0.10857965561571,
   -0.0536294731362708,
   -0.287873722642798,
   -0.17470677051048,
   -0.14333542305174,
   0.0924521088718972,
   -0.228846034180081,
   -0.0970696818728277,
   0.14086993528782,
   -0.256864056429213,
   0.0290138730983497,
   nan,
   0.0966319002751849,
   0.12641823286545,
   -0.0564034537269414,
   -0.0243742064466973,
   -0.0751347781225285],
  [0.115985120024433,
   -0.383308474362186,
   0.394811901838188,
   0.388464477814049,
   -0.193886514187391,
   -0.295912538372222,
   -0.616717829356424,
   0.043554768406968,
   nan,
   -0.0647965861512802,
   0.187163498100975,
   -0.238415039792854,
   -0.36109535426946,
   -0.197541785956867,
   -0.0146251784947066,
   -0.11360146059652,
   0.32716605302711,
   0.231067673502697,
   -0.298238099681569,
   -0.246457946939078],
  [-0.10478691224174,
   0.150868539664635,
   -0.546069535240541,
   -0.504405410537037,
   -0.895167955339535,
   -0.558971245322247,
   -0.387570912384842,
   -0.163811327571017,
   nan,
   0.0856628118333151,
   -0.403001281705867,
   -0.767487847704505,
   -0.643453274266967,
   0.0946729299111538,
   0.0704435596191907,
   -0.675022809955519,
   -0.601128794891879,
   -0.483588281856607,
   -0.49386837570929,
   -0.509887090766212],
  [-0.268788899835656,
   -0.357914686848829,
   -0.205880911679441,
   -0.250429894368906,
   -0.725479880333096,
   -0.482843643998934,
   -0.579729212115744,
   -0.996318252672408,
   0.285762551573792,
   -0.589710714370334,
   -0.608621079165106,
   -0.181485429865381,
   -0.479029625257602,
   nan,
   -0.233342501243719,
   -0.391196725953356,
   -0.739813668123278,

In [44]:
load_dotenv()
cred_path = os.getenv('GOOGLE_APPLICATION_CREDENTIALS')

os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = cred_path

client = storage.Client()
bucket = client.bucket('domainome-data')

data = dict_fitness
compressed_data = gzip.compress(pickle.dumps(data))

blob_name = "dict_fitness.pkl.gz"
blob = bucket.blob("ESM2/"+blob_name)

blob.upload_from_string(compressed_data)

In [22]:
fitn = dict_fitness['A0A2R8Y422_PF00240_2']
for i in range(len(fitn)):
    print(fitn[i])

[-0.280789669693156, -0.103250266182212, -0.258003463940259, 0.376782636488238, 0.149046632098227, -0.187511607393213, -0.111728040072573, 0.28014749897967, 0.179340002571484, 0.133359739131628, -0.170486170149888, 0.213562029209033, -0.728559271446471, nan, -0.06181253769339, -0.040570763010855, 0.160116898879892, 0.0749988165010841, -0.203489963228899, 0.267453947886271]
[-0.658535772340188, -0.458064361612281, -0.955485314389134, -1.48141990737615, -0.252340176524816, -1.0048814778358, -1.00963634229646, nan, -1.38335060728201, -0.0586843189615014, 0.0091776489296827, -1.18316759213014, -0.869488221454636, -1.1257808641811, -1.02035926265076, -1.09083221122697, -0.626917163199318, -0.268435061484519, -0.526229277214102, -0.422089496047954]
[-0.0531473648031064, -0.0472066204229054, -0.0222738697725414, -0.100256224013795, nan, -0.219191702454087, -0.134904310261034, 0.289581876135704, -0.0288922198041806, -0.0614616897899479, -0.226416508143173, 0.0269285920172507, -0.869880106657763, -0.117297347869968, -0.0786973556572508, -0.0273694978855287, 0.0055744899819968, 0.145791239755031, -0.194508817136952, 0.0723046407443522]
[-0.226996212523351, 0.0057370985312568, -0.989267415571708, -0.655001242323714, 0.0359163208842319, -0.899099644446113, -1.24074837048306, 0.111517811448594, -1.38940366500902, 0.07711678935372, -0.153966065934756, -0.922204064345365, -0.555572066960548, -0.967739920440861, -1.14390610105596, -1.10691182975095, -0.267437000742033, nan, -0.603030233425203, 0.0019703506210078]
[0.247471724180045, 0.296499392283811, 0.370055600639005, 0.275108174602085, 0.240311905887046, 0.266368490300771, -0.12579557038065, 0.291895651530859, nan, 0.166649252658951, 0.202012760499316, 0.256945317868201, -0.81112379734801, -0.149907715096376, -0.0061240816678679, 0.206570281767982, 0.190695989801461, 0.287440373363795, 0.117848900382445, 0.141264251357802]
[-0.0758758662301681, -0.0891275526110787, 0.27800039384603, 0.0317865399337745, -0.086481277047152, 0.42184243189559, -0.197731995900192, -0.0825260096646342, -0.217959743109305, -0.176591343846912, -0.128758799559542, 0.011619578349449, -0.0541196546816276, -0.224435372975832, -0.220764985687366, -0.114165487602954, nan, -0.0316036228232375, -0.225207378422448, -0.0805045374928255]
[0.416259678430039, 0.345994857592167, 0.668140461292863, 0.742387160731478, 0.0836064251245755, 0.338840641660899, 0.527801299915992, 0.298801962955504, 0.560066701718777, nan, 0.0400864388391571, 0.480255456490238, 0.446130070592559, 0.323387927414681, 0.400623486837111, 0.468227185852468, 0.505327425829633, 0.418447400686233, 0.405704828927683, 0.384085315005394]
[0.125831845672862, 0.29612263345736, 0.462056184405098, 0.591157008148355, -0.103503492932481, 0.28126236896426, 0.190166566617823, 0.11625152699372, 0.0467487674103894, -0.100660854589861, nan, 0.31295632987042, 0.436716702293019, 0.275246833054943, 0.137620195169476, 0.258614821664221, 0.32468067238425, 0.174300678193899, 0.143313875397312, 0.286532790763274]
[0.0462005763149513, -0.0029378784920571, 0.167528823450814, 0.223438992941865, -0.113747971594906, nan, 0.019920177550048, -0.600142636129687, -0.0460638786887, -0.0521106477646718, -0.227517652341521, 0.133034802151195, 0.187546061917862, 0.110086548085211, 0.0150965440991304, 0.0158916592878893, -0.147919717035914, -0.459353324987682, -0.140402888241567, -0.12018606563783]
[-0.0278153058203217, -0.0801797405714354, 0.03919860456374, 0.0723935782368414, -0.0216490663804234, -0.185878518948448, -0.0553224817454046, -0.0612646267160383, nan, -0.181449011645349, -0.0915707425622345, -0.0712284270557095, -0.073169645395713, -0.333252285833616, -0.0544712028802862, -0.0386645594316741, -0.0990405115180355, -0.0646647000509535, -0.109239050814261, -0.127853177785627]
[0.103407412428783, 0.0024070547179868, 0.179576702354645, 0.0644525106003687, -0.0592070193110607, 0.0789868576997319, 0.0581449515857905, 0.125359846696974, 0.239297878413624, 0.28365037565236, 0.260591054765047, 0.252707131218236, 0.0995241353945169, 0.087473315250777, 0.0792963881854034, 0.0851586995013617, nan, 0.164369091434185, -0.0391536456108437, -0.0422179974189919]
[-0.0563453329385536, -0.124138111662352, -0.17514481404781, -0.244498970986209, 0.0712976162230951, -0.434838370463453, 0.285712044769593, nan, -0.0980948328577396, 0.152017284406414, 0.0286761087003838, -0.124841908354886, -1.08998065224376, 0.0486608534693885, -0.064890755346824, -0.193260610943149, 0.0232681489208591, 0.0163418090530243, -0.0280909420175169, 0.128546189931828]
[-0.0655423100162104, 0.0645011110883905, 0.146353576813842, 0.176523415210916, 0.0919113661555166, 0.0282618140503311, 0.158045425629628, 0.19435293142177, 0.146648961336141, 0.150564872127494, -0.0417235889961772, 0.20356321410854, 0.110183468943168, -0.0010024025728287, 0.219541149767096, 0.0305309106106771, nan, 0.242985633023457, -0.149953934580662, 0.033908294380579]
[-0.005514264593382, 0.0296729089114807, -0.83523398123713, -0.771568182282923, 0.0140951219396048, -0.932964240405185, -0.459256824306855, -0.0924612379594743, -0.334660439454857, nan, 0.143513319474958, -0.964630049443643, -0.778233171975978, -0.495286593016152, -0.936000300286589, -0.670668527024252, -0.0523918863235986, -0.0130422981111919, -0.795216591506315, 0.0034497942952831]
[0.0600505949287982, -0.0629925351331108, 0.0693349688494682, nan, -0.122369586122726, 0.0613677101719, -0.129971150638263, -0.106056209055489, 0.0549559472291138, 0.0380849951105388, -0.131783234540353, 0.0108881900253871, 0.0031014674546202, -0.158831997216747, -0.0403307018106552, 0.0141531063835269, -0.16083876318901, 0.0307482822458635, -0.196025796634829, -0.157568944764355]
[0.0172831458829785, -0.0976938438167995, -0.59182424943059, -0.468296375019853, 0.0181459095896466, 0.0290733161471549, -0.0051456291914418, 0.0380018000388244, -0.828886225277128, -0.182619765188213, -0.140609615389464, -0.188998894373912, -0.0328267584482915, -0.0693999562455549, -0.536798272679831, 0.068803164662095, -0.062518855448703, nan, 0.0147795904841645, 0.153275014615161]
[-0.0277133428368064, 0.0241820341783282, 0.0066984638044013, nan, 0.0378530573348501, -0.0878789262401458, 0.0472875745499272, -0.093660143370039, -0.120859329458927, -0.0268816722377486, -0.051501390926359, -0.0010745329801231, 0.0287749903849466, 0.0852756488025092, 0.0365283789034106, -0.0468815433834287, -0.102624342317747, 0.0264117741475096, -0.0760145246830254, -0.0716393602887233]
[-0.132802304139333, -0.141980793423276, -0.0441383469615452, 0.0175262883821303, -0.0038972829385956, -0.22463663782104, -0.0072213042130039, -0.0824789498260887, -0.0556632453977299, nan, -0.0650299740358546, -0.217556513123672, -0.0171716588845194, -0.457111960117907, -0.156296648415106, -0.256140538605455, -0.159087885088838, -0.110325628872107, -0.195430265582759, -0.076051500270454]
[-0.112387157930297, -0.318294120069256, -0.387845620199651, -0.25058103494109, -0.110666532583476, 0.0319910261369782, -0.0412590131495833, 0.0235879037166908, -0.168698036344201, -0.0246227999875629, -0.215520894988491, -0.0270568861009047, -0.12358165708336, -0.231298966392272, -0.066272577867926, nan, 0.0534654388904186, -0.17413722929038, -0.165446145477087, 0.0340573172026399]
[0.0974648472810197, -0.0055592235462781, nan, -0.10269045018618, 0.138824422823686, 0.0146202032929001, -0.0362493812891762, 0.116666661998032, 0.188039069750244, 0.021602566778051, -0.0600783266193697, -0.0012085694845519, -0.741421453627992, -0.0614454429409262, 0.0806116826609425, 0.053001983516171, 0.0732580226520291, 0.073063060463769, 0.107902467364142, 0.0721491752063]
[-0.149220165252864, -0.185497278232612, -0.112818959960761, -0.113510151339399, -0.0135903491475867, -0.0555329904874699, 0.0181369458108761, -0.0517820692491127, 0.12045932083129, -0.185435652253564, -0.378434492844804, 0.0010340559166121, -0.11525290601506, 0.104301129184019, -0.0633281166008342, -0.154464956246956, nan, -0.0175306302124724, -0.111827481993309, -0.0217515896001118]
[0.111535879065179, -0.0320427079239525, -0.928171980179965, -0.516640274874276, -0.160237069539035, -0.0330269028211533, -0.241129850699861, nan, -1.05375522105099, -0.0133892243614218, -0.239422530962152, -0.21520114019266, 0.0137140212828119, 0.0086916440494655, -0.413804163283074, 0.0766791048434379, -0.0215966842982328, -0.107883139216168, -0.424013627184676, -0.28693742133934]
[-0.136918079185462, -0.122264121663128, nan, -0.169598896110644, 0.0335190702992753, 0.0200086948654074, -0.200176306323694, -0.0423862083299836, 0.0632848383564575, -0.113398944459026, 0.0136892308321495, 0.0573711253716117, 0.0084508825540494, -0.15864697922056, -0.0340207617923412, -0.0646914513282219, -0.0239435136276049, -0.0426217876407979, -0.0048733544112856, -0.0046827340533675]
[0.0786742459151079, -0.0190443883523538, 0.077221973695231, 0.0240881946193238, -0.0308071070440456, -0.0387717045997912, -0.0202483358884771, 0.0126289838744421, -0.154930792624939, -0.144207872270634, 0.0686161858393023, nan, 0.21758452493233, 0.168656298749301, 0.0115823226439338, 0.0370045796505975, -0.0683233223797824, 0.108771253609672, -0.166966486392003, -0.051403909832229]
[-0.0633484251621113, -0.0367918299638395, -1.20249753285995, -1.34034623435856, -0.191763659888463, -0.809947301384372, -0.726066080416861, -0.101567876954209, -1.03114450927933, -0.205274595558504, 0.217167148983325, -0.960311188784744, -0.830826043026698, -0.551514976653558, -1.20168279539923, -0.329460887531748, 0.0900609060755653, nan, -0.709847103144802, -0.821598673136647]
[-0.0032647762990966, 0.0434793691628643, -1.03295099081969, -0.0483989430584357, 0.247807865883942, -0.193111728180132, 0.0104617102385681, 0.152057901528969, nan, 0.37802355961179, 0.184663646806948, -0.130775929901009, -0.878037845634206, -0.0635936685469126, -0.129504193787933, 0.020685880339716, 0.146973198021358, 0.0882097457003975, 0.437757340984665, 0.0467136125905236]
[nan, 0.0257376699721534, 0.111544142548733, 0.290325589655575, 0.0022246978436228, -0.0333294303546603, 0.0123871019066797, -0.0191569958231592, -0.011729524698432, -0.192256387602758, -0.223311259094384, -0.103552513597632, -8.12342451083714e-05, -0.157231122351939, -0.152282416175363, -0.0323810905725418, -0.0960886271216495, 0.0304418330591443, 0.0561902875776312, -0.0705137057577993]
[0.157951586070624, 0.128722804385417, 0.120279064842575, 0.0594766329693945, 0.0595376987122692, 0.0526599593324562, 0.0882685704985794, 0.0307793753534739, nan, 0.0596610907294079, 0.06663925244326, 0.0360415336689334, -0.824473805177311, -0.0486181354611851, 0.0732130636991331, 0.139378496398942, 0.0928916393995052, 0.0443756069808789, 0.0504377825516124, -0.0484810176578037]
[-0.0618637993032343, -0.0069726994111637, -0.994349037780367, -1.15170468662769, -0.0931385634928261, -1.04914993964856, -1.01692319414172, nan, -1.04893985108362, 0.0197654123072123, 0.0568924035616454, -1.06552690352145, -0.987281518396895, -0.545586837587253, -0.912538169590773, -0.710098929304638, -0.200150395400685, -0.0339723013633628, -0.769096980523109, -0.212594921515114]
[0.0951097544680936, -0.0917490377243431, -0.0704982992630373, 0.0479581772492011, -0.0515862667065928, 0.0805340899509597, -0.0680032874658642, 0.119548937049903, 0.0298406996453424, 0.0486803216764059, -0.0852603823667906, -0.109028822190283, 0.0951435086975265, nan, -0.133349934998598, -0.0746602937934516, -0.116820586886608, 0.104960247041743, -0.0961291041851603, -0.193876730674583]
[-0.0226981086146675, -0.13336366078484, nan, 0.0294339681836275, -0.0915305456168101, -0.0361586230291241, 0.0134126142216512, -0.0327888024475598, -0.495099053957186, -0.0139605251990029, 0.0100520375369441, -0.105343588643228, 0.259491591275218, -0.0172633975578745, -0.082638757194483, -0.0841809473201523, -0.0836247728592466, 0.0064053202267948, -0.342249678774584, -0.178277654728127]
[0.293355066761944, 0.133226402922416, 0.288993628153885, 0.0715210103971431, 0.0701991331465693, 0.180692972929668, 0.129088638606491, 0.0681545512326176, nan, 0.130639092215714, 0.0637316267045536, 0.0717142918768836, 0.0566767126349783, -0.0392477652879348, 0.0375180361032998, 0.108595479510342, 0.0393631739396059, 0.148182467801126, 0.169520463046402, 0.0690132532270305]
[-0.171955809691133, -0.315723756506793, -0.1252851952269, nan, -0.292622978142666, -0.168032335711443, -0.441706445769279, -0.281850897064166, -0.609993548880466, -0.344594407218307, -0.462932393779922, -0.259158110693144, -0.405928783337904, -0.285540052264433, -0.361148405721916, -0.345253805194118, -0.280601570398017, -0.237860592511379, -0.57644296529645, -0.310090581785658]
[0.0472552209109272, -0.134253455886864, 0.0414552358692331, 0.20610108397296, -0.127110724797145, nan, 0.107578650856055, -0.111604087819261, 0.14249901188345, -0.0655624785184443, -0.0570995508866717, 0.0571233609240312, -0.249860711281448, -0.0588920265227008, -0.0423003521364466, -0.116090879271066, -0.0147997589863984, 0.0050349825472426, -0.307281277495341, -0.162564570720433]
[0.0020598483496702, -0.0216626521076224, 0.251288333109706, 0.143162891748645, 0.175841327670093, 0.0502968831540625, -0.0122739341997013, nan, -0.0419479635835283, 0.0051851258416497, 0.0480552381662013, 0.0197984662414287, -0.0031773794560834, -0.134918316165363, -0.0765718196162774, 0.11386267995136, 0.147352758028675, -0.0379296696315298, -0.0956936606195708, 0.0021619513922288]
[-0.134311440330786, -0.106524146319122, 0.106969954253915, 0.0368642404892206, -0.0796549393362265, -0.240740206441428, -0.132372182817388, 0.141436103803919, 0.0316093652440123, -0.0653774605222578, -0.171543755985773, -0.0410615298985441, nan, 0.0122915816391557, -0.17948244261851, 0.0059441057972399, -0.0236464483967863, -0.0636134168720166, -0.0493465825453377, -0.0186096450819808]
[0.233097464567163, 0.0682799040763625, 0.202204641388624, -0.0522323590732909, 0.169003645176661, 0.0787543596878699, 0.196376784597315, 0.130858424677507, 0.22604689232793, 0.149258121253596, 0.122013135857552, 0.0975439806404789, nan, 0.151501867127106, 0.0405010136072964, 0.0727326611806474, 0.160479651802014, 0.112436178595449, 0.0566359554533809, 0.0733487809120813]
[-0.0194499993417226, -0.0871412352591358, nan, -0.32508166142519, -0.239023222629732, -0.0198649942869916, -0.10779042012951, -0.187240313026359, -0.399045441596359, -0.102718461994839, -0.10662961077872, -0.162051394385817, -0.119867991550518, -0.10659809749398, -0.222834638170067, -0.141606695718647, -0.125824842720697, -0.102998860199506, -0.245536108201774, -0.247464020932664]
[-0.0892558466947327, -0.0022161542419821, -0.0284622385412795, 0.126091094961992, -0.205671102710059, -0.0240981388113974, -0.142848599255502, 0.170061090953502, 0.2254922585165, -0.0100845312349874, -0.131301711549521, -0.214781103121832, 0.123818496925564, nan, 0.388750681737393, -0.10969830441721, 0.11820324976197, 0.0324078418498101, -0.165506931101875, -0.106440250952191]
[-0.0567449213890608, -0.134325586294158, -0.190367971522075, -0.496315886925292, -0.165592647236369, 0.0951552736571629, -0.0273486290880784, -0.17522100616736, -0.112612092753821, -0.0155908124629019, -0.110428012032753, -0.0882160483573456, -0.319085733781933, nan, -0.211320384221172, 0.0359142199985825, 0.0082966775473868, -0.0971609191570798, 0.337601119127779, -0.212254998217048]
[0.141447308527383, 0.05522906236353, 0.484797571264142, 0.35099496543763, 0.0576407390299455, -0.0387857105041202, 0.225880222066414, 0.196077058244674, 0.118252970722338, 0.227848051624643, 0.159086064321275, 0.308232138340239, -0.292898054103688, 0.253645526808281, nan, 0.148524211866755, 0.25637107579071, 0.270063247862769, 0.0692673203315591, 0.121547439538612]
[-0.783528524284698, -0.257507094690838, -0.98285215115284, -0.600745310192965, 0.0886981315843507, -0.874218435523679, -0.858434341581037, -0.0074589844094676, -1.18648875620006, nan, 0.178824585292176, -1.101007500722, -0.995118522164204, -0.837138504107792, -0.953052488807182, -0.921194938938459, -0.920296880352881, 0.0489862106269518, 0.0938053845979312, 0.0407195057148291]
[0.292493703645709, 0.180740593004387, 0.596143110089489, 0.594696300172301, 0.258480364982662, 0.331707434586124, 0.27279439920693, nan, 0.450188981667112, 0.206515658741099, 0.169587691387181, 0.401304173787502, -0.710046407163404, 0.593183662504766, 0.211465345330978, 0.315284111169905, 0.354517450376381, 0.0738531335269696, 0.200213001793036, 0.371043016894202]
[0.304907136652527, 0.0702866700486257, 0.220486548309305, -0.02423021448922, nan, 0.269714500844976, 0.0666266471293639, -0.135407822521662, -0.0097675776200215, 0.184555801343614, 0.204605253390619, 0.145847263372347, -0.712908793831127, 0.144804803913138, 0.109589198422487, 0.151178330737105, -0.0470487738811173, -0.23900697578071, -0.196014872029453, -0.237905971641405]
[nan, 0.0819250163098757, 0.354622494658848, 0.401227141313692, 5.43429087966011e-05, 0.0073881145335627, 0.117386145303414, 0.300101710877237, -0.101986653493647, 0.281185336490451, 0.160118299470325, 0.356091714022964, -0.154322656258973, 0.114444485217188, 0.22444041510139, 0.138252001513758, 0.0468921878707188, 0.0677151860138159, -0.0137579998224052, 0.0358327056353877]
[-0.129961066387146, -0.0927350533891067, 0.241121447157264, 0.0797623646224302, -0.0429236148790884, nan, 0.0167909784048564, -0.121187207679269, -0.322978534831143, -0.139706514678328, -0.335872370356447, 0.11979530090705, -0.309475022290397, 0.170177339959433, -0.134527271316496, -0.0674588779645947, 0.0080234223539274, -0.151012640888893, -0.323197727233893, -0.275200613570657]
[0.268186456682679, 0.375178960442564, 0.543518725754029, 0.367035927665667, 0.355500664860278, 0.237677395282755, 0.254725382032049, 0.465073056197571, nan, 0.384403249033663, 0.0474566258151786, 0.346731568159874, -0.227374091822149, 0.260861368718597, 0.0771894799971877, 0.271623505605023, 0.439468862493673, 0.458068703442623, 0.359469938147125, 0.251347157907888]
[0.0146709046665713, -0.143448332078871, 0.357090335001623, 0.231785111331533, -0.0809447430658869, 0.0986701954075759, 0.101272352372866, -0.176523415210916, -0.341939868170826, -0.256350907288476, -0.19691167008364, 0.0138798511900678, 0.198542097406583, nan, -0.13159751624895, -0.200044090586828, 0.248646819553251, -0.157427064953502, 0.33893308062947, 0.270833572600866]
[0.0389022396281376, 0.0846949640090277, -0.989889417782961, -1.17942038245643, -0.225491698280327, -0.662309943379731, -0.944278069863132, 0.196733935157705, -0.736600341239853, nan, 0.0701765836405995, -0.94026986016225, -0.640668860364775, -1.04065886014908, -0.69942825097348, -0.75513533485176, 0.218791833885493, 0.160976861405694, -0.533412765485418, -0.704116027152406]
[-0.0254808016867591, 0.130537969586459, -0.115680646333268, nan, -0.04291899293066, 0.0900495612930587, 0.224997850093685, 0.085778320708878, 0.390231105824972, 0.110315684680034, 0.178103281219231, 0.121249533953533, 0.0934797473222812, -0.0019471008198216, 0.332589806558853, 0.0686576433161164, 0.0263784400952066, 0.0848752199977423, 0.138074686764953, 0.054752441439213]
[0.0391743743492507, -0.0018798724790423, nan, -0.337964992522248, -0.154607256234938, -0.0629194243125133, -0.129210209856067, -0.0826811950845998, -0.163938689994154, -0.08119474845816, -0.243558894687645, -0.11518777855993, 0.0428558263021359, -0.229804956577495, 0.0238236230865483, -0.0670845001418799, -0.145044725054294, -0.0547797529526547, -0.200738923500591, -0.244268853978083]
[0.037959222089664, -0.0409514434905178, -0.113828645603841, 0.119631711944487, -0.168454753786006, nan, 0.124494842045613, -0.0612901174619172, -0.240027025792993, -0.0254723981441616, -0.0447218329358925, -0.0273162754490782, 0.0693381902074637, 0.0576324755463912, 0.0150120884960264, 0.0305442162197897, -0.107638175949453, 0.141727566673007, -0.459482179307509, -0.120825575229494]

In [11]:
df[df['domain_ID']=='A0PJY2_PF00096_289'][['aa_seq','position','mut_aa','normalized_fitness']][0:40]

                      aa_seq  position mut_aa  normalized_fitness
1368  ACKVCGKGFRQASTLCRHKIIH     289.0      A           -0.252455
1369  CCKVCGKGFRQASTLCRHKIIH     289.0      C           -0.801103
1370  DCKVCGKGFRQASTLCRHKIIH     289.0      D            0.213685
1371  ECKVCGKGFRQASTLCRHKIIH     289.0      E           -0.170356
1372  FCKVCGKGFRQASTLCRHKIIH     289.0      F           -0.314744
1373  GCKVCGKGFRQASTLCRHKIIH     289.0      G           -0.116247
1374  HCKVCGKGFRQASTLCRHKIIH     289.0      H           -0.202370
1375  ICKVCGKGFRQASTLCRHKIIH     289.0      I            0.215031
1376  KCKVCGKGFRQASTLCRHKIIH     289.0      K           -0.413446
1377  LCKVCGKGFRQASTLCRHKIIH     289.0      L           -0.280329
1378  MCKVCGKGFRQASTLCRHKIIH     289.0      M            0.179151
1379  NCKVCGKGFRQASTLCRHKIIH     289.0      N            0.054597
1380  PCKVCGKGFRQASTLCRHKIIH     289.0      P           -0.779434
1381  QCKVCGKGFRQASTLCRHKIIH     289.0      Q           -0.496913
1382  RCKVCGKGFRQASTLCRHKIIH     289.0      R           -0.422942
1383  SCKVCGKGFRQASTLCRHKIIH     289.0      S           -0.588839
1384  TCKVCGKGFRQASTLCRHKIIH     289.0      T           -0.250399
1385  V*KVCGKGFRQASTLCRHKIIH     290.0      *           -0.641633
1386  VAKVCGKGFRQASTLCRHKIIH     290.0      A           -1.089481
1387  VC*VCGKGFRQASTLCRHKIIH     291.0      *           -1.063845
1388  VCAVCGKGFRQASTLCRHKIIH     291.0      A           -0.159890
1389  VCCVCGKGFRQASTLCRHKIIH     291.0      C           -0.193617
1390  VCDVCGKGFRQASTLCRHKIIH     291.0      D           -0.061939
1391  VCEVCGKGFRQASTLCRHKIIH     291.0      E            0.217698
1392  VCFVCGKGFRQASTLCRHKIIH     291.0      F           -0.692475
1393  VCGVCGKGFRQASTLCRHKIIH     291.0      G           -0.186859
1394  VCHVCGKGFRQASTLCRHKIIH     291.0      H           -0.630002
1395  VCIVCGKGFRQASTLCRHKIIH     291.0      I            0.275591
1396  VCK*CGKGFRQASTLCRHKIIH     292.0      *           -0.934139
1397  VCKACGKGFRQASTLCRHKIIH     292.0      A           -0.317871
1398  VCKCCGKGFRQASTLCRHKIIH     292.0      C           -0.370362
1399  VCKDCGKGFRQASTLCRHKIIH     292.0      D            0.330562
1400  VCKECGKGFRQASTLCRHKIIH     292.0      E            0.360846
1401  VCKFCGKGFRQASTLCRHKIIH     292.0      F           -0.728839
1402  VCKGCGKGFRQASTLCRHKIIH     292.0      G            0.052733
1403  VCKHCGKGFRQASTLCRHKIIH     292.0      H           -0.011239
1404  VCKICGKGFRQASTLCRHKIIH     292.0      I            0.031685
1405  VCKKCGKGFRQASTLCRHKIIH     292.0      K           -0.562844
1406  VCKLCGKGFRQASTLCRHKIIH     292.0      L           -0.340312
1407  VCKMCGKGFRQASTLCRHKIIH     292.0      M           -0.696894

In [8]:
df = df.dropna(subset=["normalized_fitness"]).reset_index(drop=True)

In [9]:
df

,domain_ID,uniprot_ID,aa_seq,wt_aa,position,mut_aa,STOP,input_count_rep1,input_count_rep2,input_count_rep3,output_count_rep1,output_count_rep2,output_count_rep3,mean_input_count,fitness,fitness_sigma,normalized_fitness,normalized_fitness_sigma,quality_rank
0,A0A2R8Y422_PF00240_2,A0A2R8Y422,*IFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2.0,*,True,118.0,113.0,62.0,10.0,29.0,2.0,97.66667,0.030945,0.014885,-0.819050,0.208478,339
1,A0A2R8Y422_PF00240_2,A0A2R8Y422,AIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2.0,A,False,219.0,277.0,217.0,86.0,225.0,137.0,237.66670,0.069376,0.006673,-0.280790,0.093461,339
2,A0A2R8Y422_PF00240_2,A0A2R8Y422,CIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2.0,C,False,706.0,726.0,459.0,768.0,507.0,616.0,630.33330,0.082052,0.004141,-0.103250,0.057995,339
3,A0A2R8Y422_PF00240_2,A0A2R8Y422,DIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2.0,D,False,407.0,431.0,323.0,508.0,159.0,111.0,387.00000,0.071003,0.005162,-0.258003,0.072296,339
4,A0A2R8Y422_PF00240_2,A0A2R8Y422,EIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2.0,E,False,37.0,56.0,37.0,201.0,102.0,95.0,43.33333,0.116326,0.012085,0.376783,0.169263,339
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
563529,Q9Y6V0_PF05715_1058,Q9Y6V0,TVPLCKTELNIGSKDPPNFNTCTECKNQVCNLCGFNPTPHLTEIQE...,C,1059.0,V,False,146.0,118.0,99.0,10.0,22.0,8.0,121.00000,0.009509,0.013942,-1.113722,0.157535,380
563530,Q9Y6V0_PF05715_1058,Q9Y6V0,TWPLCKTELNIGSKDPPNFNTCTECKNQVCNLCGFNPTPHLTEIQE...,C,1059.0,W,False,118.0,121.0,83.0,13.0,47.0,4.0,107.33330,0.028085,0.013317,-0.903822,0.150480,380
563531,Q9Y6V0_PF05715_1058,Q9Y6V0,TYPLCKTELNIGSKDPPNFNTCTECKNQVCNLCGFNPTPHLTEIQE...,C,1059.0,Y,False,177.0,168.0,126.0,12.0,6.0,29.0,157.00000,0.006343,0.013753,-1.149495,0.155403,380
563532,Q9Y6V0_PF05715_1058,Q9Y6V0,VCPLCKTELNIGSKDPPNFNTCTECKNQVCNLCGFNPTPHLTEIQE...,T,1058.0,V,False,20.0,19.0,23.0,46.0,43.0,8.0,20.66667,0.090240,0.021806,-0.201507,0.246396,380
563533,Q9Y6V0_PF05715_1058,Q9Y6V0,WCPLCKTELNIGSKDPPNFNTCTECKNQVCNLCGFNPTPHLTEIQE...,T,1058.0,W,False,36.0,27.0,16.0,16.0,10.0,34.0,26.33333,0.062446,0.020810,-0.515568,0.235147,380